# Generated by Django 5.2.11 on 2026-02-09 19:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_hod_teaching_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, numbers, spaces, and @/./+/-/_ characters.', max_length=150, unique=True, validators=[accounts.models.UsernameValidator()]),
        ),
    ]
