# Generated by Django 5.2.11 on 2026-02-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_allow_spaces_in_username'),
        ('accounts', '0004_merge_0003_conflicts'),
    ]

    operations = [
    ]
