# Generated by Django 4.2.28 on 2026-02-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sync_iqac_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, default='', help_text='Optional mobile number (leave empty if unknown).', max_length=32, verbose_name='Mobile no'),
        ),
    ]
