# Generated by Django 5.2.5 on 2026-02-24 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notification_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Query, doubt, error, or bug description')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('REVIEWED', 'Reviewed'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('FIXED', 'Fixed'), ('LATER', 'Later'), ('CLOSED', 'Closed')], default='SENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes by admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Query',
                'verbose_name_plural': 'User Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
