# Generated by Django 4.2.28 on 2026-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Response or notes from admin (visible to user)'),
        ),
    ]
