# Generated by Django 4.2.28 on 2026-03-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_updated',
            field=models.BooleanField(default=False),
        ),
    ]
