# Generated by Django 4.2.28 on 2026-03-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_ps_permissions'),
        ('accounts', '0015_fix_feedback_permissions_lowercase'),
    ]

    operations = [
    ]
