# Generated by Django 4.2.28 on 2026-03-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_profile_image_updated'),
        ('accounts', '0016_merge_20260312_1541'),
    ]

    operations = [
    ]
