# Generated by Django 4.2.28 on 2026-03-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_library_role'),
        ('accounts', '0017_merge_20260312_1546'),
    ]

    operations = [
    ]
