# Generated by Django 4.2.28 on 2026-03-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_0016_add_library_role_0017_merge_20260312_1546'),
        ('accounts', '0018_user_name_email_edited'),
    ]

    operations = [
    ]
