# Generated by Django 4.2.28 on 2026-03-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20260314_2022'),
        ('accounts', '0020_add_security_scan_permission'),
        ('accounts', '0020_profile_image_update_request'),
    ]

    operations = [
    ]
