# Generated by Django 4.2.28 on 2026-05-25 07:43

from django.db import migrations


def create_visual_admin_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.get_or_create(
        name='VISUAL_ADMIN',
        defaults={'description': 'Manages Power BI URL assignments for staff academic dashboards.'},
    )


def delete_visual_admin_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(name='VISUAL_ADMIN').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_site_configuration'),
    ]

    operations = [
        migrations.RunPython(create_visual_admin_role, delete_visual_admin_role),
    ]
