# Generated by Django 4.2.28 on 2026-05-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_add_academic_calendar_admin_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='app_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Application access conditions. Shape: {"application": {"require_profile": true, "require_phone": true}, "marks": {"require_profile": true, "require_phone": true}}'),
        ),
    ]
