# Generated by Django 4.2.28 on 2026-07-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_add_roles_and_sidebar_keys'),
        ('accounts', '0030_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Features assigned to this role', related_name='roles', to='college.featurecatalog'),
        ),
    ]
