# Generated by Django
from django.db import migrations


def create_db_reader_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.get_or_create(name='DB_READER', defaults={'description': 'Database read-only role'})


def remove_db_reader_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(name='DB_READER').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_add_visual_admin_role'),
    ]

    operations = [
        migrations.RunPython(create_db_reader_role, remove_db_reader_role),
    ]
