# Generated by Django 4.2.28 on 2026-06-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_add_app_conditions_to_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='login_lockdown',
            field=models.BooleanField(default=False, help_text='When True, only superusers can log in (via impersonation). Regular staff/student login is blocked.'),
        ),
    ]
