# Generated by Django 4.2.28 on 2026-07-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_role_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='forwarded_to_super_admin',
            field=models.BooleanField(default=False, help_text='Indicates if this query was escalated/forwarded to the Super Admin'),
        ),
    ]
