# Generated by Django
from django.db import migrations

def create_coder_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    
    roles = [
        ('CODE_ADMIN', 'Coder Admin - full access to coding platform'),
        ('CODE_COURSE_INCHARGE', 'Coder Course Incharge - can create sessions and questions'),
        ('CODE_SECTION_INCHARGE', 'Coder Section Incharge - can view student analytics'),
    ]
    
    for name, desc in roles:
        Role.objects.get_or_create(name=name, defaults={'description': desc})

def remove_coder_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(name__in=['CODE_ADMIN', 'CODE_COURSE_INCHARGE', 'CODE_SECTION_INCHARGE']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_add_db_reader_role'),
    ]

    operations = [
        migrations.RunPython(create_coder_roles, remove_coder_roles),
    ]
