# Generated by Django 4.2.28 on 2026-07-22 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_userquery_forwarded_to_super_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuserimpersonationlog',
            name='superuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='superuserimpersonationlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
