# Generated by Django 4.2.28 on 2026-08-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_add_coder_roles'),
        ('accounts', '0032_login_lockdown'),
    ]

    operations = [
    ]
