# Generated by Django 4.2.28 on 2026-08-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_add_pbas_admin_role'),
        ('accounts', '0033_merge_0032_add_coder_roles_0032_login_lockdown'),
    ]

    operations = [
    ]
