# Generated by Django 4.2.28 on 2026-08-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_login_lockdown'),
        ('accounts', '0033_alter_superuserimpersonationlog_superuser_and_more'),
    ]

    operations = [
    ]
