# Generated by Django 4.2.28 on 2026-08-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_merge_20260819_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='app_conditions',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='login_lockdown',
        ),
    ]
