# Generated by ChatGPT on 2026-01-29
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CdapRevision',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('subject_id', models.CharField(max_length=64, unique=True)),
                ('status', models.TextField(default='draft')),
                ('rows', models.JSONField(default=list)),
                ('books', models.JSONField(default=dict)),
                ('active_learning', models.JSONField(default=dict)),
                ('created_by', models.IntegerField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(null=True, blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cdap_revisions',
            },
        ),
        migrations.CreateModel(
            name='CdapActiveLearningAnalysisMapping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mapping', models.JSONField(default=dict)),
                ('updated_by', models.IntegerField(null=True, blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cdap_active_learning_analysis_mapping',
            },
        ),
    ]
