# Generated by Django 6.0.1 on 2026-02-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0003_obeassessmentmasterconfig'),
        ('academics', '0007_roleassignment_staffdepartmentassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cia1PublishedSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cia1_published_sheet', to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(choices=[('ssa1', 'SSA1'), ('cia1', 'CIA1'), ('formative1', 'Formative1')], max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_drafts', to='academics.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'assessment'), name='unique_obe_draft_per_subject_assessment')],
            },
        ),
        migrations.CreateModel(
            name='Formative1Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skill2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('att1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('att2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formative1_marks', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formative1_marks', to='academics.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'student'), name='unique_formative1_mark_per_subject_student')],
            },
        ),
        migrations.CreateModel(
            name='Ssa1Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssa1_marks', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssa1_marks', to='academics.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'student'), name='unique_ssa1_mark_per_subject_student')],
            },
        ),
    ]
