# Generated by Django 6.0.1 on 2026-02-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0004_cia1publishedsheet_assessmentdraft_formative1mark_and_more'),
        ('academics', '0007_roleassignment_staffdepartmentassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdraft',
            name='assessment',
            field=models.CharField(
                choices=[
                    ('ssa1', 'SSA1'),
                    ('ssa2', 'SSA2'),
                    ('cia1', 'CIA1'),
                    ('cia2', 'CIA2'),
                    ('formative1', 'Formative1'),
                    ('formative2', 'Formative2'),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='Ssa2Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssa2_marks', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssa2_marks', to='academics.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'student'), name='unique_ssa2_mark_per_subject_student')],
            },
        ),
        migrations.CreateModel(
            name='Formative2Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skill2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('att1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('att2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formative2_marks', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formative2_marks', to='academics.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'student'), name='unique_formative2_mark_per_subject_student')],
            },
        ),
        migrations.CreateModel(
            name='Cia2Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cia2_marks', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cia2_marks', to='academics.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'student'), name='unique_cia2_mark_per_subject_student')],
            },
        ),
        migrations.CreateModel(
            name='Cia2PublishedSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cia2_published_sheet', to='academics.subject')),
            ],
        ),
    ]
