# Generated by Django 6.0.1 on 2026-02-05 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0005_ssa2_cia2_formative2'),
        ('academics', '0029_periodattendancesession_periodattendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObeDueSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(db_index=True, max_length=64)),
                ('subject_name', models.CharField(blank=True, default='', max_length=255)),
                ('assessment', models.CharField(choices=[('ssa1', 'SSA1'), ('ssa2', 'SSA2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2')], max_length=20)),
                ('due_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_due_schedules', to='academics.academicyear')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obe_due_schedules', to='academics.subject')),
            ],
            options={
                'indexes': [models.Index(fields=['academic_year', 'assessment'], name='OBE_obedues_academi_d8b8f5_idx'), models.Index(fields=['subject_code', 'assessment'], name='OBE_obedues_subject_917a98_idx'), models.Index(fields=['due_at'], name='OBE_obedues_due_at_f795dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'subject_code', 'assessment'), name='unique_obe_due_schedule')],
            },
        ),
        migrations.CreateModel(
            name='ObePublishRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(db_index=True, max_length=64)),
                ('subject_name', models.CharField(blank=True, default='', max_length=255)),
                ('assessment', models.CharField(choices=[('ssa1', 'SSA1'), ('ssa2', 'SSA2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('approved_until', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obe_publish_requests', to='academics.academicyear')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obe_publish_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_publish_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='OBE_obepubl_status_0dfb17_idx'), models.Index(fields=['staff_user', 'assessment'], name='OBE_obepubl_staff_u_33cee3_idx'), models.Index(fields=['academic_year', 'assessment'], name='OBE_obepubl_academi_92ff97_idx')],
            },
        ),
    ]
