# Generated by Django 6.0.1 on 2026-02-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0007_obeglobalpublishcontrol'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obeglobalpublishcontrol',
            new_name='OBE_obeglob_academi_d0809f_idx',
            old_name='OBE_obeglo_academi_e47b9f_idx',
        ),
        migrations.RenameIndex(
            model_name='obeglobalpublishcontrol',
            new_name='OBE_obeglob_assessm_70f6d2_idx',
            old_name='OBE_obeglo_assessm_299f79_idx',
        ),
    ]
