# Generated by Django 6.0.1 on 2026-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0009_labpublishedsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdraft',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('ssa2', 'SSA2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obedueschedule',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('ssa2', 'SSA2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obeglobalpublishcontrol',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('ssa2', 'SSA2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obepublishrequest',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('ssa2', 'SSA2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL')], max_length=20),
        ),
    ]
