# Generated by Django 6.0.1 on 2026-02-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0010_alter_assessmentdraft_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpublishedsheet',
            name='assessment',
            field=models.CharField(choices=[('cia1', 'CIA 1 LAB'), ('cia2', 'CIA 2 LAB'), ('model', 'MODEL LAB'), ('formative1', 'Lab 1 (Formative1)'), ('formative2', 'Lab 2 (Formative2)')], max_length=20),
        ),
    ]
