# Generated by Django 6.0.1 on 2026-02-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0013_obeeditrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obeeditrequest',
            new_name='OBE_obeedit_status_38948b_idx',
            old_name='OBE_obeedit_status_4e3a6d_idx',
        ),
        migrations.RenameIndex(
            model_name='obeeditrequest',
            new_name='OBE_obeedit_staff_u_a55941_idx',
            old_name='OBE_obeedit_staff_u_9e98a5_idx',
        ),
        migrations.RenameIndex(
            model_name='obeeditrequest',
            new_name='OBE_obeedit_academi_e98d0c_idx',
            old_name='OBE_obeedit_academi_5e7b0e_idx',
        ),
        migrations.RenameIndex(
            model_name='obeeditrequest',
            new_name='OBE_obeedit_subject_7470a2_idx',
            old_name='OBE_obeedit_subject_5d53a6_idx',
        ),
    ]
