# Generated by Django 6.0.1 on 2026-02-07 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0014_rename_obe_obeedit_status_4e3a6d_idx_obe_obeedit_status_38948b_idx_and_more'),
        ('academics', '0029_periodattendancesession_periodattendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObeMarkTableLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(db_index=True, max_length=64)),
                ('subject_name', models.CharField(blank=True, default='', max_length=255)),
                ('section_name', models.CharField(blank=True, default='', max_length=64)),
                ('assessment', models.CharField(choices=[('ssa1', 'SSA1'), ('ssa2', 'SSA2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL')], db_index=True, max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_blocked', models.BooleanField(default=False)),
                ('mark_entry_blocked', models.BooleanField(default=False)),
                ('mark_manager_locked', models.BooleanField(default=False)),
                ('mark_entry_unblocked_until', models.DateTimeField(blank=True, null=True)),
                ('mark_manager_unlocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obe_mark_table_locks', to='academics.academicyear')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_mark_table_locks', to=settings.AUTH_USER_MODEL)),
                ('teaching_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obe_mark_table_locks', to='academics.teachingassignment')),
            ],
            options={
                'indexes': [models.Index(fields=['subject_code', 'assessment'], name='OBE_obemark_subject_890384_idx'), models.Index(fields=['staff_user', 'assessment'], name='OBE_obemark_staff_u_b11c27_idx'), models.Index(fields=['academic_year', 'assessment'], name='OBE_obemark_academi_db9343_idx'), models.Index(fields=['assessment', 'updated_at'], name='OBE_obemark_assessm_e4b8c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff_user', 'subject_code', 'assessment', 'section_name'), name='unique_obe_mark_table_lock')],
            },
        ),
    ]
