# Generated by Copilot on 2026-02-07

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0015_obemarktablelock'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='obemarktablelock',
            name='unique_obe_mark_table_lock',
        ),
        migrations.AddConstraint(
            model_name='obemarktablelock',
            constraint=models.UniqueConstraint(
                fields=('teaching_assignment', 'assessment'),
                condition=Q(teaching_assignment__isnull=False),
                name='unique_obe_mark_table_lock_ta',
            ),
        ),
        migrations.AddConstraint(
            model_name='obemarktablelock',
            constraint=models.UniqueConstraint(
                fields=('staff_user', 'subject_code', 'assessment', 'section_name', 'academic_year'),
                condition=Q(teaching_assignment__isnull=True),
                name='unique_obe_mark_table_lock_fallback',
            ),
        ),
    ]
