# Generated by Django 6.0.1 on 2026-02-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0017_obeeditrequest_ta_section'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obeeditrequest',
            new_name='OBE_obeedit_teachin_3eece5_idx',
            old_name='OBE_obeedit_teachin_7b5e2a_idx',
        ),
    ]
