# Generated by Django 6.0.1 on 2026-02-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0018_rename_obe_obeedit_teachin_7b5e2a_idx_obe_obeedit_teachin_3eece5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTypeWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('THEORY', 'Theory'), ('TCPR', 'Theory + Practical'), ('TCPL', 'Theory + Practical + Lab'), ('LAB', 'Lab')], max_length=16, unique=True)),
                ('ssa1', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('cia1', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('formative1', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Type Weights',
                'verbose_name_plural': 'Class Type Weights',
                'db_table': 'obe_class_type_weights',
            },
        ),
    ]
