# Generated by Django 6.0.1 on 2026-02-10

from django.db import migrations, models
import django.db.models.deletion


def backfill_due_schedule_semester(apps, schema_editor):
    ObeDueSchedule = apps.get_model('OBE', 'ObeDueSchedule')
    Semester = apps.get_model('academics', 'Semester')
    CurriculumDepartment = apps.get_model('curriculum', 'CurriculumDepartment')
    CurriculumMaster = apps.get_model('curriculum', 'CurriculumMaster')

    # Build quick lookup maps (case-insensitive) from curriculum rows.
    dept_map = {}
    for r in CurriculumDepartment.objects.select_related('semester').all():
        code = (getattr(r, 'course_code', None) or '').strip().lower()
        if not code:
            continue
        sem_id = getattr(r, 'semester_id', None)
        if sem_id and code not in dept_map:
            dept_map[code] = sem_id

    master_map = {}
    for r in CurriculumMaster.objects.select_related('semester').all():
        code = (getattr(r, 'course_code', None) or '').strip().lower()
        if not code:
            continue
        sem_id = getattr(r, 'semester_id', None)
        if sem_id and code not in master_map:
            master_map[code] = sem_id

    # Update schedules that do not have semester populated.
    qs = ObeDueSchedule.objects.filter(semester__isnull=True)
    for row in qs.iterator():
        code = (getattr(row, 'subject_code', None) or '').strip().lower()
        if not code:
            continue
        sem_id = dept_map.get(code) or master_map.get(code)
        if not sem_id:
            continue
        # ensure semester exists (defensive)
        if not Semester.objects.filter(id=sem_id).exists():
            continue
        row.semester_id = sem_id
        row.save(update_fields=['semester'])


def backfill_global_control_semester(apps, schema_editor):
    ObeGlobalPublishControl = apps.get_model('OBE', 'ObeGlobalPublishControl')
    # There isn't a reliable backfill from academic_year -> semester.
    # Leave semester NULL for existing rows.
    for _row in ObeGlobalPublishControl.objects.filter(semester__isnull=True).iterator():
        # no-op
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0022_classtypeweights_internal_mark_weights'),
        ('academics', '0029_periodattendancesession_periodattendancerecord'),
        ('curriculum', '0005_alter_curriculumdepartment_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obedueschedule',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obe_due_schedules', to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='obedueschedule',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obe_due_schedules', to='academics.academicyear'),
        ),
        migrations.AddIndex(
            model_name='obedueschedule',
            index=models.Index(fields=['semester', 'assessment'], name='OBE_obedues_sem_assess_idx'),
        ),
        migrations.RemoveConstraint(
            model_name='obedueschedule',
            name='unique_obe_due_schedule',
        ),
        migrations.AddConstraint(
            model_name='obedueschedule',
            constraint=models.UniqueConstraint(fields=('semester', 'subject_code', 'assessment'), name='unique_obe_due_schedule_semester'),
        ),
        migrations.AddField(
            model_name='obeglobalpublishcontrol',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obe_global_publish_controls', to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='obeglobalpublishcontrol',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obe_global_publish_controls', to='academics.academicyear'),
        ),
        migrations.AddIndex(
            model_name='obeglobalpublishcontrol',
            index=models.Index(fields=['semester', 'assessment'], name='OBE_obeglo_sem_assess_idx'),
        ),
        migrations.RemoveConstraint(
            model_name='obeglobalpublishcontrol',
            name='unique_obe_global_publish_control',
        ),
        migrations.AddConstraint(
            model_name='obeglobalpublishcontrol',
            constraint=models.UniqueConstraint(fields=('semester', 'assessment'), name='unique_obe_global_publish_control_semester'),
        ),
        migrations.RunPython(backfill_due_schedule_semester, migrations.RunPython.noop),
        migrations.RunPython(backfill_global_control_semester, migrations.RunPython.noop),
    ]
