# Generated by Django 6.0.1 on 2026-02-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0023_semester_due_schedules'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obedueschedule',
            new_name='OBE_obedues_semeste_23f4f2_idx',
            old_name='OBE_obedues_sem_assess_idx',
        ),
        migrations.RenameIndex(
            model_name='obeglobalpublishcontrol',
            new_name='OBE_obeglob_semeste_041d1d_idx',
            old_name='OBE_obeglo_sem_assess_idx',
        ),
        migrations.AlterField(
            model_name='internalmarkmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='obedueschedule',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obeeditrequest',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obeglobalpublishcontrol',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obemarktablelock',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='obepublishrequest',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL')], max_length=20),
        ),
    ]
