# Generated by Django 6.0.1 on 2026-02-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0025_obe_qp_pattern_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassTypeWeights',
        ),
        migrations.RemoveField(
            model_name='internalmarkmapping',
            name='subject',
        ),
        migrations.RemoveConstraint(
            model_name='obeqppatternconfig',
            name='unique_qp_pattern_per_key',
        ),
        migrations.DeleteModel(
            name='ObeQpPatternConfig',
        ),
        migrations.DeleteModel(
            name='InternalMarkMapping',
        ),
    ]
