# Generated by Django 6.0.1 on 2026-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0026_delete_classtypeweights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObeQpPatternConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=50)),
                ('question_paper_type', models.CharField(blank=True, max_length=50, null=True)),
                ('exam', models.CharField(max_length=50)),
                ('pattern', models.JSONField(default=list)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('class_type', 'question_paper_type', 'exam'), name='unique_qp_pattern_per_class_type_qp_exam')],
            },
        ),
    ]
