# Generated by GitHub Copilot on 2026-02-14

from django.db import migrations


DEFAULT_HEADER = ['CO1', 'CO1', 'CO1', 'CO2', 'CO2', 'CO2', 'CO3', 'CO3', 'CO3', 'CO4', 'CO4', 'CO4', 'CO1', 'CO2', 'CO3', 'CO4', 'CO5']
DEFAULT_CYCLES = ['ssa', 'cia', 'fa', 'ssa', 'cia', 'fa', 'ssa', 'cia', 'fa', 'ssa', 'cia', 'fa', 'ME', 'ME', 'ME', 'ME', 'ME']
DEFAULT_WEIGHTS = [1.5, 3.0, 2.5, 1.5, 3.0, 2.5, 1.5, 3.0, 2.5, 1.5, 3.0, 2.5, 2.0, 2.0, 2.0, 2.0, 4.0]


def _to_num(x, fallback=0.0):
    try:
        n = float(x)
        return n if n == n else float(fallback)
    except Exception:
        return float(fallback)


def _round2(x: float) -> float:
    try:
        return round(float(x) * 100.0) / 100.0
    except Exception:
        return 0.0


def _split_cycle_weight(total: float) -> list:
    """Split a single total weight into [ssa, cia, fa] using 1.5:3:2.5 ratio (sum=7)."""
    t = _to_num(total, 0.0)
    if t <= 0:
        return [0.0, 0.0, 0.0]
    ssa_w, cia_w, fa_w = 1.5, 3.0, 2.5
    s = ssa_w + cia_w + fa_w
    return [_round2(t * ssa_w / s), _round2(t * cia_w / s), _round2(t * fa_w / s)]


def upgrade_internal_mark_weights(apps, schema_editor):
    # 1) ClassTypeWeights.internal_mark_weights (used by InternalMarkCoursePage)
    try:
        ClassTypeWeights = apps.get_model('OBE', 'ClassTypeWeights')
    except Exception:
        ClassTypeWeights = None

    if ClassTypeWeights is not None:
        for row in ClassTypeWeights.objects.all().iterator():
            raw = getattr(row, 'internal_mark_weights', None)
            if not isinstance(raw, list):
                continue
            weights = [_to_num(x, 0.0) for x in raw]

            if len(weights) == 13:
                co1 = _split_cycle_weight(weights[0] if len(weights) > 0 else 0.0)
                co2 = _split_cycle_weight(weights[1] if len(weights) > 1 else 0.0)
                weights = co1 + co2 + weights[2:]

            # Pad/truncate to 17
            while len(weights) < len(DEFAULT_WEIGHTS):
                weights.append(DEFAULT_WEIGHTS[len(weights)] if len(weights) < len(DEFAULT_WEIGHTS) else 0.0)
            if len(weights) > len(DEFAULT_WEIGHTS):
                weights = weights[: len(DEFAULT_WEIGHTS)]

            if raw != weights:
                row.internal_mark_weights = weights
                row.save(update_fields=['internal_mark_weights'])

    # 2) InternalMarkMapping.mapping.weights (IQAC per-subject mapping editor)
    try:
        InternalMarkMapping = apps.get_model('OBE', 'InternalMarkMapping')
    except Exception:
        InternalMarkMapping = None

    if InternalMarkMapping is not None:
        for obj in InternalMarkMapping.objects.select_related('subject').all().iterator():
            m = getattr(obj, 'mapping', None)
            if not isinstance(m, dict):
                continue

            weights = m.get('weights')
            weights = weights if isinstance(weights, list) else []
            weights = [_to_num(x, 0.0) for x in weights]

            if len(weights) == 13:
                co1 = _split_cycle_weight(weights[0] if len(weights) > 0 else 0.0)
                co2 = _split_cycle_weight(weights[1] if len(weights) > 1 else 0.0)
                weights = co1 + co2 + weights[2:]

            while len(weights) < len(DEFAULT_WEIGHTS):
                weights.append(DEFAULT_WEIGHTS[len(weights)] if len(weights) < len(DEFAULT_WEIGHTS) else 0.0)
            if len(weights) > len(DEFAULT_WEIGHTS):
                weights = weights[: len(DEFAULT_WEIGHTS)]

            # Only force header/cycles when missing or wrong length.
            header = m.get('header')
            cycles = m.get('cycles')
            changed = False

            if not isinstance(header, list) or len(header) != len(DEFAULT_HEADER):
                m['header'] = DEFAULT_HEADER
                changed = True
            if not isinstance(cycles, list) or len(cycles) != len(DEFAULT_CYCLES):
                m['cycles'] = DEFAULT_CYCLES
                changed = True

            if m.get('weights') != weights:
                m['weights'] = weights
                changed = True

            if changed:
                obj.mapping = m
                obj.save(update_fields=['mapping'])


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0029_restore_internal_mark_mapping'),
    ]

    operations = [
        migrations.RunPython(upgrade_internal_mark_weights, migrations.RunPython.noop),
    ]
