# Generated by GitHub Copilot on 2026-02-15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0030_upgrade_internal_mark_weights_split_co1_co2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LcaRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=64, unique=True)),
                ('status', models.TextField(default='draft')),
                ('data', models.JSONField(default=dict)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lca_revisions',
            },
        ),
    ]
