# Generated by Django 6.0.2 on 2026-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0031_lca_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdraft',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL'), ('cdap', 'CDAP'), ('articulation', 'Articulation'), ('lca', 'LCA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obedueschedule',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL'), ('cdap', 'CDAP'), ('articulation', 'Articulation'), ('lca', 'LCA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obeeditrequest',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL'), ('cdap', 'CDAP'), ('articulation', 'Articulation'), ('lca', 'LCA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obeglobalpublishcontrol',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL'), ('cdap', 'CDAP'), ('articulation', 'Articulation'), ('lca', 'LCA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obemarktablelock',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL'), ('cdap', 'CDAP'), ('articulation', 'Articulation'), ('lca', 'LCA')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='obepublishrequest',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL'), ('cdap', 'CDAP'), ('articulation', 'Articulation'), ('lca', 'LCA')], max_length=20),
        ),
    ]
