# Generated by Django 6.0.2 on 2026-02-17 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0032_alter_assessmentdraft_assessment_and_more'),
        ('academics', '0038_alter_teachingassignment_custom_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IqacResetNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(max_length=50)),
                ('reset_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iqac_resets', to=settings.AUTH_USER_MODEL)),
                ('teaching_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_notifications', to='academics.teachingassignment')),
            ],
            options={
                'db_table': 'obe_iqac_reset_notifications',
                'ordering': ['-reset_at'],
                'indexes': [models.Index(fields=['teaching_assignment', 'is_read'], name='obe_iqac_re_teachin_ec2c22_idx')],
            },
        ),
    ]
