# Generated by Django 4.2.28 on 2026-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0035_obeassessmentcontrol'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obeassessmentcontrol',
            new_name='OBE_obeasse_semeste_beb9cd_idx',
            old_name='obe_assessctrl_sem_assess_idx',
        ),
        migrations.RenameIndex(
            model_name='obeassessmentcontrol',
            new_name='OBE_obeasse_academi_2a4929_idx',
            old_name='obe_assessctrl_ay_assess_idx',
        ),
        migrations.RenameIndex(
            model_name='obeassessmentcontrol',
            new_name='OBE_obeasse_subject_1b3806_idx',
            old_name='obe_assessctrl_code_assess_idx',
        ),
        migrations.AlterField(
            model_name='obeassessmentcontrol',
            name='assessment',
            field=models.CharField(choices=[('ssa1', 'SSA1'), ('review1', 'Review1'), ('ssa2', 'SSA2'), ('review2', 'Review2'), ('cia1', 'CIA1'), ('cia2', 'CIA2'), ('formative1', 'Formative1'), ('formative2', 'Formative2'), ('model', 'MODEL'), ('cdap', 'CDAP'), ('articulation', 'Articulation'), ('lca', 'LCA')], max_length=20),
        ),
    ]
