# Generated by Django 4.2.28 on 2026-02-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0037_add_cqi_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obecqiconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
