# Generated by Django 4.2.28 on 2026-02-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0039_modelpublishedsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpublishedsheet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
