# Generated by Django 4.2.28 on 2026-02-21 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0039_periodattendancesession_teaching_assignment'),
        ('OBE', '0040_alter_modelpublishedsheet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdapPublished',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(db_index=True, max_length=64)),
                ('rows', models.JSONField(default=list)),
                ('books', models.JSONField(default=dict)),
                ('active_learning', models.JSONField(default=dict)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teaching_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdap_published', to='academics.teachingassignment')),
            ],
            options={
                'db_table': 'cdap_published',
            },
        ),
        migrations.CreateModel(
            name='CdapDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(db_index=True, max_length=64)),
                ('rows', models.JSONField(default=list)),
                ('books', models.JSONField(default=dict)),
                ('active_learning', models.JSONField(default=dict)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teaching_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdap_drafts', to='academics.teachingassignment')),
            ],
            options={
                'db_table': 'cdap_drafts',
            },
        ),
        migrations.AddConstraint(
            model_name='cdappublished',
            constraint=models.UniqueConstraint(fields=('subject_code', 'teaching_assignment'), name='unique_cdap_published_per_subject_ta'),
        ),
        migrations.AddConstraint(
            model_name='cdapdraft',
            constraint=models.UniqueConstraint(fields=('subject_code', 'teaching_assignment'), name='unique_cdap_draft_per_subject_ta'),
        ),
    ]
