# Generated by Django 4.2.28 on 2026-02-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0041_cdappublished_cdapdraft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdappublished',
            name='teaching_assignment',
        ),
        migrations.DeleteModel(
            name='CdapDraft',
        ),
        migrations.DeleteModel(
            name='CdapPublished',
        ),
    ]
