# Generated by Django 4.2.28 on 2026-02-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0043_obeeditrequest_hod_preapproval'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obeeditrequest',
            new_name='OBE_obeedit_hod_use_419357_idx',
            old_name='obeedit_hodstat_idx',
        ),
    ]
