# Generated by Django 4.2.28 on 2026-02-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0044_rename_obeedit_hodstat_idx_obe_obeedit_hod_use_419357_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpublishedsheet',
            name='assessment',
            field=models.CharField(choices=[('cia1', 'CIA 1 LAB'), ('cia2', 'CIA 2 LAB'), ('model', 'MODEL LAB'), ('formative1', 'Lab 1 (Formative1)'), ('formative2', 'Lab 2 (Formative2)'), ('review1', 'Review 1 (Lab-style)'), ('review2', 'Review 2 (Lab-style)')], max_length=20),
        ),
    ]
