# Generated by Django 4.2.28 on 2026-03-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0047_obepublishrequest_hod_preapproval'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obepublishrequest',
            new_name='OBE_obepubl_hod_use_55268b_idx',
            old_name='obe_pubreq_hod_idx',
        ),
    ]
