# Generated by Django 5.2.5 on 2026-03-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0049_obe_cqi_draft_and_published'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obecqidraft',
            new_name='obe_cqi_dra_subject_200ba4_idx',
            old_name='obe_cqi_draft_subj_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='obecqidraft',
            new_name='obe_cqi_dra_teachin_957517_idx',
            old_name='obe_cqi_draft_ta_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='obecqipublished',
            new_name='obe_cqi_pub_subject_b988af_idx',
            old_name='obe_cqi_pub_subj_pubat_idx',
        ),
        migrations.RenameIndex(
            model_name='obecqipublished',
            new_name='obe_cqi_pub_teachin_c4e3bb_idx',
            old_name='obe_cqi_pub_ta_pubat_idx',
        ),
    ]
