# Generated by Django 4.2.28 on 2026-03-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0054_review2publishedsheet_review1publishedsheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review2publishedsheet',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='review2publishedsheet',
            name='teaching_assignment',
        ),
        migrations.DeleteModel(
            name='Review1PublishedSheet',
        ),
        migrations.DeleteModel(
            name='Review2PublishedSheet',
        ),
    ]
