# Generated by Django 4.2.28 on 2026-03-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0055_remove_review2publishedsheet_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obeeditrequest',
            name='assessment',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='obemarktablelock',
            name='assessment',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
