# Generated by Django 4.2.28 on 2026-03-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0056_cqi_assessment_key_length'),
        ('OBE', '0056_obe_batch_qp_pattern_override'),
    ]

    operations = [
    ]
