# Generated by Django 4.2.28 on 2026-04-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0085_add_internal_external_ids'),
        ('OBE', '0060_rename_obe_final_i_subject_8c1d53_idx_obe_final_i_subject_b203e4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCourseQpPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=50)),
                ('pattern', models.JSONField(default=dict)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teaching_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_qp_patterns', to='academics.teachingassignment')),
            ],
            options={
                'db_table': 'obe_special_course_qp_pattern',
                'indexes': [models.Index(fields=['teaching_assignment', 'exam'], name='obe_special_teachin_1200df_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='specialcourseqppattern',
            constraint=models.UniqueConstraint(fields=('teaching_assignment', 'exam'), name='unique_special_qp_per_ta_exam'),
        ),
    ]
