# Generated migration for CourseQuestionBankLog

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0083_merge_20260424_1934'),
        ('OBE', '0061_add_course_question_bank'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS obe_course_question_bank_log (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                action VARCHAR(20) NOT NULL,
                old_values JSONB DEFAULT '{}'::JSONB,
                new_values JSONB DEFAULT '{}'::JSONB,
                edited_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                edited_by_id BIGINT REFERENCES academics_staffprofile(id) ON DELETE SET NULL,
                question_bank_id BIGINT NOT NULL REFERENCES obe_course_question_bank(id) ON DELETE CASCADE
            )
            """,
            reverse_sql="DROP TABLE IF EXISTS obe_course_question_bank_log",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS obe_log_question_bank_idx ON obe_course_question_bank_log(question_bank_id, edited_at)",
            reverse_sql="DROP INDEX IF EXISTS obe_log_question_bank_idx",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS obe_log_edited_by_idx ON obe_course_question_bank_log(edited_by_id, edited_at)",
            reverse_sql="DROP INDEX IF EXISTS obe_log_edited_by_idx",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS obe_log_action_idx ON obe_course_question_bank_log(action, edited_at)",
            reverse_sql="DROP INDEX IF EXISTS obe_log_action_idx",
        ),
    ]

