# Generated by Django 4.2.28 on 2026-04-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0084_alter_staffprofile_internal_id'),
        ('OBE', '0062_add_course_question_bank_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuestionBankLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('finalized', 'Finalized'), ('unfinalezed', 'Unfinalized')], max_length=20)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'obe_course_question_bank_log',
                'ordering': ('-edited_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='coursequestionbank',
            new_name='obe_course__course__7a7a96_idx',
            old_name='obe_question_bank_course_idx',
        ),
        migrations.RenameIndex(
            model_name='coursequestionbank',
            new_name='obe_course__is_fina_e0a092_idx',
            old_name='obe_question_bank_finalized_idx',
        ),
        migrations.AddField(
            model_name='coursequestionbank',
            name='question_type',
            field=models.CharField(choices=[('D', 'Descriptive'), ('O', 'Objective')], default='D', help_text='D=Descriptive, O=Objective', max_length=1),
        ),
        migrations.AddField(
            model_name='coursequestionbanklog',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_logs', to='academics.staffprofile'),
        ),
        migrations.AddField(
            model_name='coursequestionbanklog',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='OBE.coursequestionbank'),
        ),
        migrations.AddIndex(
            model_name='coursequestionbanklog',
            index=models.Index(fields=['question_bank', 'edited_at'], name='obe_course__questio_9d4517_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequestionbanklog',
            index=models.Index(fields=['edited_by', 'edited_at'], name='obe_course__edited__f67685_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequestionbanklog',
            index=models.Index(fields=['action', 'edited_at'], name='obe_course__action_e235c3_idx'),
        ),
    ]
