# Generated by Django 4.2.28 on 2026-04-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0085_add_internal_external_ids'),
        ('OBE', '0062_special_course_co_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_exam_marks', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_exam_marks', to='academics.subject')),
                ('teaching_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_exam_marks', to='academics.teachingassignment')),
            ],
        ),
        migrations.CreateModel(
            name='ModelExamCOMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_num', models.IntegerField()),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('model_exam_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_marks', to='OBE.modelexammark')),
            ],
        ),
        migrations.CreateModel(
            name='LabExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_exam_marks', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_exam_marks', to='academics.subject')),
                ('teaching_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_exam_marks', to='academics.teachingassignment')),
            ],
        ),
        migrations.CreateModel(
            name='LabExamCOMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_num', models.IntegerField()),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lab_exam_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_marks', to='OBE.labexammark')),
            ],
        ),
        migrations.AddConstraint(
            model_name='modelexammark',
            constraint=models.UniqueConstraint(condition=models.Q(('teaching_assignment__isnull', False)), fields=('subject', 'student', 'teaching_assignment'), name='unique_model_mark_subject_student_ta'),
        ),
        migrations.AddConstraint(
            model_name='modelexammark',
            constraint=models.UniqueConstraint(condition=models.Q(('teaching_assignment__isnull', True)), fields=('subject', 'student'), name='unique_model_mark_subject_student_legacy'),
        ),
        migrations.AddConstraint(
            model_name='modelexamcomark',
            constraint=models.UniqueConstraint(fields=('model_exam_mark', 'co_num'), name='unique_model_co_mark'),
        ),
        migrations.AddConstraint(
            model_name='labexammark',
            constraint=models.UniqueConstraint(condition=models.Q(('teaching_assignment__isnull', False)), fields=('subject', 'student', 'teaching_assignment'), name='unique_lab_mark_subject_student_ta'),
        ),
        migrations.AddConstraint(
            model_name='labexammark',
            constraint=models.UniqueConstraint(condition=models.Q(('teaching_assignment__isnull', True)), fields=('subject', 'student'), name='unique_lab_mark_subject_student_legacy'),
        ),
        migrations.AddConstraint(
            model_name='labexamcomark',
            constraint=models.UniqueConstraint(fields=('lab_exam_mark', 'co_num'), name='unique_lab_co_mark'),
        ),
    ]
