# Generated by Django 4.2.28 on 2026-04-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0063_modelexammark_modelexamcomark_labexammark_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='labexammark',
            name='unique_lab_mark_subject_student_ta',
        ),
        migrations.RemoveConstraint(
            model_name='labexammark',
            name='unique_lab_mark_subject_student_legacy',
        ),
        migrations.AddField(
            model_name='labexammark',
            name='assessment',
            field=models.CharField(choices=[('cia1', 'CIA 1 LAB'), ('cia2', 'CIA 2 LAB'), ('model', 'MODEL LAB'), ('formative1', 'Lab 1 (Formative1)'), ('formative2', 'Lab 2 (Formative2)'), ('review1', 'Review 1 (Lab-style)'), ('review2', 'Review 2 (Lab-style)')], default='model', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='labexammark',
            constraint=models.UniqueConstraint(condition=models.Q(('teaching_assignment__isnull', False)), fields=('subject', 'student', 'assessment', 'teaching_assignment'), name='unique_lab_mark_subject_student_assessment_ta'),
        ),
        migrations.AddConstraint(
            model_name='labexammark',
            constraint=models.UniqueConstraint(condition=models.Q(('teaching_assignment__isnull', True)), fields=('subject', 'student', 'assessment'), name='unique_lab_mark_subject_student_assessment_legacy'),
        ),
    ]
