# Generated by Django 4.2.28 on 2026-04-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0064_remove_labexammark_unique_lab_mark_subject_student_ta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtypeweights',
            name='exam_assignments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
