# Generated by Django 4.2.28 on 2026-04-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0065_add_college_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequestionbank',
            name='subtopics',
            field=models.TextField(blank=True, help_text='Subtopics from CDAP/LCA', null=True),
        ),
    ]
