# Generated by Django 4.2.28 on 2026-05-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0066_coursequestionbank_subtopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('active_columns', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'obe_question_bank_type',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='CourseQuestionBankTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_bank_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='OBE.questionbanktype')),
            ],
            options={
                'db_table': 'obe_course_question_bank_type_mapping',
            },
        ),
    ]
