# Generated by Django 4.2.28 on 2026-04-30 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OBE', '0067_projectmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObeTemplatePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obe_template_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'obe_template_preset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObeAuditChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=64)),
                ('before_snapshot', models.JSONField(default=dict)),
                ('after_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obe_audit_changes', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_changes', to='OBE.obetemplatepreset')),
            ],
            options={
                'db_table': 'obe_audit_change',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_code', 'created_at'], name='obe_audit_c_subject_1c2c47_idx'), models.Index(fields=['template', 'created_at'], name='obe_audit_c_templat_bbfd46_idx')],
            },
        ),
    ]
