# Generated by Django 4.2.28 on 2026-05-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0067_questionbanktype_coursequestionbanktypemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankTypeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('question_text', models.TextField(blank=True, default='')),
                ('subtopics', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('D', 'Descriptive'), ('O', 'Objective')], default='D', max_length=1)),
                ('course_outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('part', models.CharField(blank=True, max_length=10, null=True)),
                ('btl', models.IntegerField(blank=True, null=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('college', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_bank_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='OBE.questionbanktype')),
            ],
            options={
                'db_table': 'obe_question_bank_type_template',
                'ordering': ('s_no',),
            },
        ),
    ]
