# Generated by Django 4.2.28 on 2026-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0068_questionbanktypetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuestionBankDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('mandatory_cos', models.JSONField(default=list, help_text='List of CO strings that are mandatory, e.g. ["CO1", "CO2"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'obe_course_question_bank_deadline',
            },
        ),
    ]
