# Generated by Django 4.2.28 on 2026-05-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0065_classtypeweights_exam_assignments'),
        ('OBE', '0069_coursequestionbankdeadline'),
    ]

    operations = [
    ]
