# Generated by Django 4.2.28 on 2026-06-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0070_merge_20260530_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseQuestionBankDeadline',
        ),
        migrations.RemoveField(
            model_name='questionbanktypetemplate',
            name='question_bank_type',
        ),
        migrations.DeleteModel(
            name='CourseQuestionBankTypeMapping',
        ),
        migrations.DeleteModel(
            name='QuestionBankType',
        ),
        migrations.DeleteModel(
            name='QuestionBankTypeTemplate',
        ),
    ]
