# Generated by Django
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('OBE', '0071_delete_coursequestionbankdeadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdapTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.TextField()),
                ('header_row_line', models.PositiveIntegerField(default=12)),
                ('field_definitions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cdap_templates',
            },
        ),
    ]
