# Generated by Django 4.2.28 on 2026-08-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0070_seed_tamil_tam_theory_patterns'),
        ('OBE', '0073_cdap_template_sheet_number'),
    ]

    operations = [
    ]
