# Generated by Django 4.2.28 on 2026-08-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('OBE', '0073_harden_college_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdraft',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentdrafts', to='college.college'),
        ),
        migrations.AlterField(
            model_name='cdapactivelearninganalysismapping',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdapactivelearninganalysismappings', to='college.college'),
        ),
        migrations.AlterField(
            model_name='cdaprevision',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdaprevisions', to='college.college'),
        ),
        migrations.AlterField(
            model_name='cia1mark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cia1marks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='cia1publishedsheet',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cia1publishedsheets', to='college.college'),
        ),
        migrations.AlterField(
            model_name='cia2mark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cia2marks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='cia2publishedsheet',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cia2publishedsheets', to='college.college'),
        ),
        migrations.AlterField(
            model_name='classtypeweights',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classtypeweights', to='college.college'),
        ),
        migrations.AlterField(
            model_name='cotargetrevision',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotargetrevisions', to='college.college'),
        ),
        migrations.AlterField(
            model_name='finalinternalmark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalinternalmarks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='formative1mark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formative1marks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='formative2mark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formative2marks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='internalmarkmapping',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internalmarkmappings', to='college.college'),
        ),
        migrations.AlterField(
            model_name='iqacresetnotification',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iqacresetnotifications', to='college.college'),
        ),
        migrations.AlterField(
            model_name='labexamcomark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labexamcomarks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='labexammark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labexammarks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='labpublishedsheet',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labpublishedsheets', to='college.college'),
        ),
        migrations.AlterField(
            model_name='lcarevision',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcarevisions', to='college.college'),
        ),
        migrations.AlterField(
            model_name='modelexamcomark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelexamcomarks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='modelexammark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelexammarks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='modelpublishedsheet',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelpublishedsheets', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obeassessmentcontrol',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obeassessmentcontrols', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obeassessmentmasterconfig',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obeassessmentmasterconfigs', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obeauditchange',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obeauditchanges', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obebatchqppatternoverride',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obebatchqppatternoverrides', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obecqiconfig',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obecqiconfigs', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obecqidraft',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obecqidrafts', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obecqipublished',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obecqipublisheds', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obedueschedule',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obedueschedules', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obeeditnotificationlog',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obeeditnotificationlogs', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obeeditrequest',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obeeditrequests', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obeglobalpublishcontrol',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obeglobalpublishcontrols', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obemarktablelock',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obemarktablelocks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obepublishrequest',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obepublishrequests', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obeqppatternconfig',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obeqppatternconfigs', to='college.college'),
        ),
        migrations.AlterField(
            model_name='obetemplatepreset',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obetemplatepresets', to='college.college'),
        ),
        migrations.AlterField(
            model_name='projectmark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectmarks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='review1mark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review1marks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='review2mark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review2marks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='specialcoursecoweights',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialcoursecoweights', to='college.college'),
        ),
        migrations.AlterField(
            model_name='specialcourseqppattern',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialcourseqppatterns', to='college.college'),
        ),
        migrations.AlterField(
            model_name='ssa1mark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssa1marks', to='college.college'),
        ),
        migrations.AlterField(
            model_name='ssa2mark',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssa2marks', to='college.college'),
        ),
    ]
