# Generated by Django 4.2.28 on 2026-08-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0074_merge_20260817_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequestionbanklog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('finalized', 'Finalized'), ('unfinalized', 'Unfinalized')], max_length=20),
        ),
    ]
