# Generated by Django 4.2.28 on 2026-08-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0075_add_course_question_bank'),
    ]

    operations = [
    ]

