# Generated by Django 4.2.28 on 2026-08-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0076_delete_cdaptemplate_remove_obeauditchange_changed_by_and_more'),
    ]

    operations = [
    ]

