# Generated by Django 4.2.28 on 2026-08-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0077_remove_specialcoursecoweights_teaching_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obetemplatepreset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectmark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='projectmark',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='projectmark',
            name='teaching_assignment',
        ),
        migrations.AlterField(
            model_name='coursequestionbanklog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('finalized', 'Finalized'), ('unfinalezed', 'Unfinalized')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ObeAuditChange',
        ),
        migrations.DeleteModel(
            name='ObeTemplatePreset',
        ),
        migrations.DeleteModel(
            name='ProjectMark',
        ),
    ]
