# Generated by Django manual creation
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('COE', '0001_seed_coe_permissions'),
        ('academics', '0001_initial'), # Assuming exists, usually safe dependency
    ]

    operations = [
        migrations.CreateModel(
            name='CoeExamDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('semester', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coe_dummies', to='academics.studentprofile')),
            ],
        ),
    ]
