# Generated by Django 4.2.28 on 2026-04-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COE', '0005_coeassignmentstore'),
        ('COE', '0005_rename_coe_coearre_departm_86f297_idx_coe_coearre_departm_1a75b7_idx_and_more'),
    ]

    operations = [
    ]
