# Generated by Django 4.2.28 on 2026-04-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COE', '0006_merge_20260402_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoeCourseSelectionStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_key', models.CharField(db_index=True, help_text='department::semester, e.g. "BCA::SEM1"', max_length=64, unique=True)),
                ('selections', models.JSONField(blank=True, default=dict, help_text='Map of courseKey -> {selected, qpType, eseType}')),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
