# Generated by Django 4.2.28 on 2026-07-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0084_staffprofile_college_studentprofile_college'),
        ('COE', '0008_coekeyvaluestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalStaffProfile',
            fields=[
            ],
            options={
                'verbose_name': 'External Staff Profile',
                'verbose_name_plural': 'External Staff Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academics.staffprofile',),
        ),
    ]
