# Generated by Django 4.2.28 on 2026-04-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COE', '0009_externalstaffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoeStudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('marks', models.JSONField(blank=True, default=dict, help_text='{"q1": "10", "q2": "5", ...}')),
                ('qp_type', models.CharField(default='QP1', help_text='Question paper type: QP1, OE, etc.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'COE Student Marks',
                'verbose_name_plural': 'COE Student Marks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExternalStaffProfile',
        ),
    ]
