# Generated by Django 4.2.28 on 2026-04-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COE', '0010_add_coestudentmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoeFinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(db_index=True, max_length=64)),
                ('student_name', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(db_index=True, max_length=32)),
                ('semester', models.CharField(db_index=True, max_length=16)),
                ('course_code', models.CharField(db_index=True, max_length=64)),
                ('course_name', models.CharField(blank=True, default='', max_length=255)),
                ('dummy_number', models.CharField(db_index=True, max_length=64)),
                ('qp_type', models.CharField(default='QP1', max_length=16)),
                ('total_marks', models.IntegerField(default=0, help_text='Computed total, capped by QP type max')),
                ('max_marks', models.IntegerField(default=100, help_text='Max possible mark for this QP type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'COE Final Result',
                'verbose_name_plural': 'COE Final Results',
                'ordering': ['department', 'semester', 'course_code', 'reg_no'],
                'indexes': [models.Index(fields=['department', 'semester'], name='COE_coefina_departm_9df789_idx'), models.Index(fields=['reg_no', 'semester'], name='COE_coefina_reg_no_c3b407_idx'), models.Index(fields=['dummy_number'], name='COE_coefina_dummy_n_343bb7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='coefinalresult',
            constraint=models.UniqueConstraint(fields=('department', 'semester', 'reg_no', 'course_code'), name='uniq_coe_final_result_dept_sem_reg_course'),
        ),
    ]
