# Generated by generate_college_migrations.py
# Harden: make college FK non-nullable on all COE models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('COE', '0013_backfill_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coeexamdummy',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coeexamdummys',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='coearrearstudent',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coearrearstudents',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='coeassignmentstore',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coeassignmentstores',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='coecourseselectionstore',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coecourseselectionstores',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='coekeyvaluestore',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coekeyvaluestores',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='coestudentmarks',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coestudentmarks',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='coefinalresult',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coefinalresults',
                to='college.college',
            ),
        ),
    ]
