# Generated by Django 4.2.28 on 2026-08-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('COE', '0014_harden_college_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coearrearstudent',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coearrearstudents', to='college.college'),
        ),
        migrations.AlterField(
            model_name='coeassignmentstore',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coeassignmentstores', to='college.college'),
        ),
        migrations.AlterField(
            model_name='coecourseselectionstore',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coecourseselectionstores', to='college.college'),
        ),
        migrations.AlterField(
            model_name='coeexamdummy',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coeexamdummys', to='college.college'),
        ),
        migrations.AlterField(
            model_name='coefinalresult',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coefinalresults', to='college.college'),
        ),
        migrations.AlterField(
            model_name='coekeyvaluestore',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coekeyvaluestores', to='college.college'),
        ),
        migrations.AlterField(
            model_name='coestudentmarks',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coestudentmarks', to='college.college'),
        ),
    ]
