# Generated by Django 4.2.28 on 2026-03-10 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0050_rename_obe_cqi_draft_subj_upd_idx_obe_cqi_dra_subject_200ba4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoTargetRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=64, unique=True)),
                ('status', models.TextField(default='draft')),
                ('data', models.JSONField(default=dict)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'co_target_revisions',
            },
        ),
    ]
