# Generated by Django 4.2.28 on 2026-02-27 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('powerbi_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powerbi_led_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PowerBI Room',
                'verbose_name_plural': 'PowerBI Rooms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoomSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('base_view', models.CharField(default='bi_obe_student_subject_wide', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerbi_created_room_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PowerBI Room Sheet',
                'verbose_name_plural': 'PowerBI Room Sheets',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('base_view', models.CharField(default='bi_obe_student_subject_wide', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerbi_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PowerBI Sheet',
                'verbose_name_plural': 'PowerBI Sheets',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='powerbiexportlog',
            name='export_type',
            field=models.CharField(default='xlsx', max_length=8),
        ),
        migrations.CreateModel(
            name='SheetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_view', models.CharField(max_length=128)),
                ('source_column', models.CharField(max_length=128)),
                ('header_label', models.CharField(max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='powerbi_portal.sheet')),
            ],
            options={
                'verbose_name': 'PowerBI Sheet Column',
                'verbose_name_plural': 'PowerBI Sheet Columns',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoomSheetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_view', models.CharField(max_length=128)),
                ('source_column', models.CharField(max_length=128)),
                ('header_label', models.CharField(max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='powerbi_portal.roomsheet')),
            ],
            options={
                'verbose_name': 'PowerBI Room Sheet Column',
                'verbose_name_plural': 'PowerBI Room Sheet Columns',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='roomsheet',
            name='created_from_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pushed_copies', to='powerbi_portal.sheet'),
        ),
        migrations.AddField(
            model_name='roomsheet',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_sheets', to='powerbi_portal.room'),
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', 'Leader'), ('CO_LEADER', 'Co-Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='powerbi_portal.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerbi_room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PowerBI Room Member',
                'verbose_name_plural': 'PowerBI Room Members',
            },
        ),
        migrations.AddField(
            model_name='powerbiexportlog',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerbi_portal.room'),
        ),
        migrations.AddField(
            model_name='powerbiexportlog',
            name='room_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerbi_portal.roomsheet'),
        ),
        migrations.AddConstraint(
            model_name='sheetcolumn',
            constraint=models.UniqueConstraint(fields=('sheet', 'source_view', 'source_column'), name='uniq_powerbi_sheet_column_once'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_powerbi_sheet_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='roomsheetcolumn',
            constraint=models.UniqueConstraint(fields=('room_sheet', 'source_view', 'source_column'), name='uniq_powerbi_room_sheet_column_once'),
        ),
        migrations.AddConstraint(
            model_name='roomsheet',
            constraint=models.UniqueConstraint(fields=('room', 'name'), name='uniq_powerbi_room_sheet_name'),
        ),
        migrations.AddConstraint(
            model_name='roommember',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='uniq_powerbi_room_user'),
        ),
        migrations.AddConstraint(
            model_name='roommember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'LEADER')), fields=('room',), name='uniq_powerbi_one_leader_per_room'),
        ),
    ]
