# Generated by Django 4.2.28 on 2026-02-27 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('powerbi_portal', '0002_room_roomsheet_sheet_powerbiexportlog_export_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('decided_reason', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerbi_room_join_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='powerbi_portal.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerbi_room_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PowerBI Room Join Request',
                'verbose_name_plural': 'PowerBI Room Join Requests',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='roomjoinrequest',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='uniq_powerbi_room_join_request'),
        ),
    ]
