# Generated by Django 4.2.28 on 2026-02-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_portal', '0003_roomjoinrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sql_server_database',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='sql_server_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='sql_server_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='sql_server_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='sql_server_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
