# Generated by Django 4.2.28 on 2026-02-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_portal', '0004_room_sql_server_database_room_sql_server_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='postgres_database',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='postgres_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='postgres_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='postgres_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='postgres_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
