# Generated by Django 4.2.28 on 2026-02-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_portal', '0005_room_postgres_database_room_postgres_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='public_bi_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
