# Generated by Django 4.2.28 on 2026-03-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcsscan', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gatepassofflinescan',
            new_name='idcsscan_ga_status_f53172_idx',
            old_name='idcsscan_ga_status_69a4cd_idx',
        ),
        migrations.RenameIndex(
            model_name='gatepassofflinescan',
            new_name='idcsscan_ga_uid_76b5e4_idx',
            old_name='idcsscan_ga_uid_2df2ee_idx',
        ),
    ]
