# Generated by Django 4.2.28 on 2026-04-09 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idcsscan', '0002_rename_idcsscan_ga_status_69a4cd_idx_idcsscan_ga_status_f53172_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.CharField(choices=[('L_THUMB', 'Left Thumb'), ('L_INDEX', 'Left Index'), ('L_MIDDLE', 'Left Middle'), ('L_RING', 'Left Ring'), ('L_LITTLE', 'Left Little'), ('R_THUMB', 'Right Thumb'), ('R_INDEX', 'Right Index'), ('R_MIDDLE', 'Right Middle'), ('R_RING', 'Right Ring'), ('R_LITTLE', 'Right Little')], max_length=16)),
                ('template', models.BinaryField(help_text='Raw fingerprint template bytes from the scanner SDK.')),
                ('template_format', models.CharField(choices=[('ISO_19794_2', 'ISO 19794-2'), ('ANSI_378', 'ANSI 378'), ('ESSL_PROPRIETARY', 'ESSL Proprietary'), ('RAW', 'Raw / Other')], default='ISO_19794_2', max_length=24)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, help_text='Enrollment quality score (0-100) reported by the device.', null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.CharField(blank=True, default='', help_text='Scanner model, e.g. ESSL-X990, SecuGen-Hamster-Pro.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_by', models.ForeignKey(blank=True, help_text='Admin/security user who performed the enrollment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'finger'),
                'indexes': [models.Index(fields=['user', 'is_active'], name='idcsscan_fi_user_id_a1a62f_idx')],
                'unique_together': {('user', 'finger')},
            },
        ),
    ]
