# Generated by Django 4.2.28 on 2026-08-24 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idcsscan', '0003_fingerprint_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricFingerprintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('staff_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('finger_name', models.CharField(blank=True, default='Right Index', max_length=32)),
                ('slot_id', models.IntegerField(blank=True, db_index=True, help_text='Hardware sensor slot number (1-300)', null=True)),
                ('template_b64', models.TextField(help_text='Base64 encoded template data')),
                ('template_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('quality_score', models.IntegerField(default=80)),
                ('device_type', models.CharField(default='esp32_r307', max_length=64)),
                ('device_ip', models.CharField(blank=True, default='', max_length=64)),
                ('sensor_raw_output', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_fingerprint_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [
                    models.Index(fields=['slot_id', 'is_active'], name='idcsscan_bi_slot_id_45bf89_idx'),
                    models.Index(fields=['reg_no', 'is_active'], name='idcsscan_bi_reg_no_3e21a8_idx'),
                    models.Index(fields=['staff_id', 'is_active'], name='idcsscan_bi_staff_i_89de12_idx'),
                    models.Index(fields=['template_hash', 'is_active'], name='idcsscan_bi_templat_a912bc_idx'),
                ],
            },
        ),
    ]
