# Generated by generate_college_migrations.py
# Add nullable college FK to all tenant models in idcsscan

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('idcsscan', '0003_fingerprint_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintenrollment',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fingerprintenrollments',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='gatepassofflinescan',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gatepassofflinescans',
                to='college.college',
            ),
        ),
    ]
