# Generated by Django 4.2.28 on 2026-08-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcsscan', '0004_biometricfingerprintdata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='biometricfingerprintdata',
            new_name='idcsscan_bi_slot_id_66c4b2_idx',
            old_name='idcsscan_bi_slot_id_45bf89_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricfingerprintdata',
            new_name='idcsscan_bi_reg_no_d6cf98_idx',
            old_name='idcsscan_bi_reg_no_3e21a8_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricfingerprintdata',
            new_name='idcsscan_bi_staff_i_c6ca8c_idx',
            old_name='idcsscan_bi_staff_i_89de12_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricfingerprintdata',
            new_name='idcsscan_bi_templat_7a82cf_idx',
            old_name='idcsscan_bi_templat_a912bc_idx',
        ),
    ]
