# Generated by generate_college_migrations.py
# Harden: make college FK non-nullable on all idcsscan models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('idcsscan', '0005_backfill_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintenrollment',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fingerprintenrollments',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='gatepassofflinescan',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gatepassofflinescans',
                to='college.college',
            ),
        ),
    ]
