# Generated by Django 4.2.28 on 2026-08-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcsscan', '0005_rename_idcsscan_bi_slot_id_45bf89_idx_idcsscan_bi_slot_id_66c4b2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintenrollment',
            name='finger',
            field=models.CharField(choices=[('L_THUMB', 'Left Thumb'), ('L_INDEX', 'Left Index'), ('L_MIDDLE', 'Left Middle'), ('L_RING', 'Left Ring'), ('L_LITTLE', 'Left Little'), ('R_THUMB', 'Right Thumb'), ('R_INDEX', 'Right Index'), ('R_MIDDLE', 'Right Middle'), ('R_RING', 'Right Ring'), ('R_LITTLE', 'Right Little'), ('R_INDEX_1', 'Right Index (Sample 1)'), ('R_INDEX_2', 'Right Index (Sample 2)'), ('R_INDEX_3', 'Right Index (Sample 3)'), ('R_INDEX_4', 'Right Index (Sample 4)'), ('R_INDEX_5', 'Right Index (Sample 5)')], max_length=16),
        ),
    ]
