# Generated by Django 4.2.28 on 2026-08-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('idcsscan', '0006_harden_college_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintenrollment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fingerprintenrollments', to='college.college'),
        ),
        migrations.AlterField(
            model_name='gatepassofflinescan',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gatepassofflinescans', to='college.college'),
        ),
    ]
