# Generated by Django 4.2.28 on 2026-08-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcsscan', '0006_alter_fingerprintenrollment_finger'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricfingerprintdata',
            name='sample_index',
            field=models.PositiveSmallIntegerField(default=1, help_text='Sample index (1-5) for multi-sample finger registration'),
        ),
    ]
