# Generated by Django 4.2.28 on 2026-08-24 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0095_remove_systemtransitionlog_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idcsscan', '0007_biometricfingerprintdata_sample_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioSecureClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Class Group (e.g. AI&DS Year 2 Lab Batch)', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sections', models.ManyToManyField(blank=True, related_name='biosecure_groups', to='academics.section')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BioSecureBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Optional batch label (e.g. Morning Session)', max_length=128)),
                ('start_time', models.TimeField(help_text='Batch Start Time (e.g. 08:45:00)')),
                ('end_time', models.TimeField(help_text='Batch End Time (e.g. 17:00:00)')),
                ('days', models.CharField(default='MON,TUE,WED,THU,FRI', help_text='Active days (SUN,MON,TUE,WED,THU,FRI,SAT)', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='idcsscan.biosecureclassgroup')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='BioSecureAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('placed', models.BooleanField(default=False, help_text='True if biometric finger placed on time')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('finger_name', models.CharField(blank=True, default='', max_length=32)),
                ('slot_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='idcsscan.biosecurebatch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='idcsscan.biosecureclassgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biosecure_attendance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['student', 'date'], name='idcsscan_bi_student_b06068_idx'), models.Index(fields=['batch', 'date'], name='idcsscan_bi_batch_i_996f72_idx')],
                'unique_together': {('student', 'batch', 'date')},
            },
        ),
    ]
