# Generated by Django 4.2.28 on 2026-03-05 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField(help_text='Upload date used to determine columns')),
                ('processed_rows', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('file', models.FileField(blank=True, null=True, upload_to='attendance_uploads/%Y/%m/')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_attendance_upload_log',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('morning_in', models.TimeField(blank=True, null=True)),
                ('evening_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('partial', 'Partial')], default='absent', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_attendance_record',
                'ordering': ['-date', 'user'],
                'indexes': [models.Index(fields=['user', 'date'], name='staff_atten_user_id_5bf3b4_idx'), models.Index(fields=['date', 'status'], name='staff_atten_date_6edd73_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
