# Generated by Django 4.2.28 on 2026-03-05 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalfDayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Staff reason for half-day attendance request')),
                ('status', models.CharField(choices=[('pending', 'Pending HOD Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='HOD review comments')),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halfday_requests', to='staff_attendance.attendancerecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_halfday_requests', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halfday_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_attendance_halfday_request',
                'ordering': ['-requested_at'],
                'unique_together': {('staff_user', 'attendance_record')},
            },
        ),
    ]
