# Generated by Django 4.2.28 on 2026-03-06 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_attendance', '0003_holiday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='halfdayrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='halfdayrequest',
            name='attendance_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date for which period attendance access is requested'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='halfdayrequest',
            name='reason',
            field=models.TextField(help_text='Staff reason for requesting period attendance access'),
        ),
        migrations.AlterField(
            model_name='halfdayrequest',
            name='review_notes',
            field=models.TextField(blank=True, help_text='HOD/AHOD review comments'),
        ),
        migrations.AlterField(
            model_name='halfdayrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='halfdayrequest',
            name='staff_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='halfdayrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='halfdayrequest',
            unique_together={('staff_user', 'attendance_date')},
        ),
        migrations.RemoveField(
            model_name='halfdayrequest',
            name='attendance_record',
        ),
    ]
