# Generated by Django 4.2.28 on 2026-03-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0007_attendance_settings_and_holiday_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='an_status',
            field=models.CharField(default='absent', help_text='Afternoon attendance status', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='fn_status',
            field=models.CharField(default='absent', help_text='Forenoon attendance status', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='mid_time_split',
            field=models.TimeField(default='13:00:00', help_text='Time that splits FN (Forenoon) and AN (Afternoon) sessions'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='attendance_in_time_limit',
            field=models.TimeField(default='08:45:00', help_text='If morning_in is after this time, mark FN as absent'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='attendance_out_time_limit',
            field=models.TimeField(default='17:00:00', help_text='If evening_out is before this time, mark AN as absent'),
        ),
    ]
