# Generated by Django 4.2.28 on 2026-03-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0008_attendancerecord_an_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='an_status',
            field=models.CharField(blank=True, help_text='Afternoon attendance status', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='fn_status',
            field=models.CharField(blank=True, help_text='Forenoon attendance status', max_length=20, null=True),
        ),
    ]
