# Generated by Django 4.2.28 on 2026-03-16 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_merge_20260310_1159'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_attendance', '0010_holiday_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Type 1', 'Engineering Depts', 'CSE/Mech')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of which departments use these settings')),
                ('attendance_in_time_limit', models.TimeField(default='08:45:00', help_text='If morning_in is after this time, mark FN as absent')),
                ('attendance_out_time_limit', models.TimeField(default='17:00:00', help_text='If evening_out is before this time, mark AN as absent')),
                ('mid_time_split', models.TimeField(default='13:00:00', help_text='Time that splits FN (Forenoon) and AN (Afternoon) sessions')),
                ('apply_time_based_absence', models.BooleanField(default=True, help_text='Enable time-based absence marking for these departments')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable this configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dept_attendance_settings', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(help_text='Departments using this time limit configuration', related_name='attendance_settings', to='academics.department')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dept_attendance_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Attendance Settings',
                'verbose_name_plural': 'Department Attendance Settings',
                'db_table': 'staff_attendance_dept_settings',
                'ordering': ['name'],
            },
        ),
    ]
