# Generated by Django 4.2.28 on 2026-04-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0014_staff_time_limit_override'),
    ]

    operations = [
    ]
