# Generated by Django 4.2.28 on 2026-03-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0014_rename_staff_biome_user_id_16fc4d_idx_staff_biome_user_id_04f2e6_idx_and_more'),
        ('staff_attendance', '0014_staff_time_limit_override'),
    ]

    operations = [
    ]
