# Generated by Django 4.2.28 on 2026-04-02 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0015_merge_0014_staff_attendance'),
        ('staff_attendance', '0015_merge_20260328_1114'),
    ]

    operations = [
    ]
