# Generated by Django 4.2.28 on 2026-04-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0016_add_lunch_time_fields'),
        ('staff_attendance', '0017_merge_20260403_0001'),
    ]

    operations = [
    ]
