# Generated by Django 4.2.28 on 2026-04-10 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0017_attendancesettings_essl_skip_minutes'),
        ('staff_attendance', '0018_merge_20260409_1632'),
    ]

    operations = [
    ]
