# Generated by Django 4.2.28 on 2026-04-18 04:35

from django.db import migrations


def rename_indexes_forward(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(
        'ALTER INDEX IF EXISTS staff_biome_user_id_16fc4d_idx RENAME TO staff_biome_user_id_04f2e6_idx;'
    )
    schema_editor.execute(
        'ALTER INDEX IF EXISTS staff_biome_source_9bbd35_idx RENAME TO staff_biome_source_2bf6a8_idx;'
    )


def rename_indexes_backward(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(
        'ALTER INDEX IF EXISTS staff_biome_user_id_04f2e6_idx RENAME TO staff_biome_user_id_16fc4d_idx;'
    )
    schema_editor.execute(
        'ALTER INDEX IF EXISTS staff_biome_source_2bf6a8_idx RENAME TO staff_biome_source_9bbd35_idx;'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0019_merge_20260410_0001'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_indexes_forward, rename_indexes_backward),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='staffbiometricpunchlog',
                    old_name='staff_biome_user_id_16fc4d_idx',
                    new_name='staff_biome_user_id_04f2e6_idx',
                ),
                migrations.RenameIndex(
                    model_name='staffbiometricpunchlog',
                    old_name='staff_biome_source_9bbd35_idx',
                    new_name='staff_biome_source_2bf6a8_idx',
                ),
            ],
        ),
    ]
