# Generated by Django 4.2.28 on 2026-04-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0019_merge_20260410_0001'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('public.staff_biome_user_id_16fc4d_idx') IS NOT NULL
                           AND to_regclass('public.staff_biome_user_id_04f2e6_idx') IS NULL THEN
                            ALTER INDEX public.staff_biome_user_id_16fc4d_idx RENAME TO staff_biome_user_id_04f2e6_idx;
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('public.staff_biome_user_id_04f2e6_idx') IS NOT NULL
                           AND to_regclass('public.staff_biome_user_id_16fc4d_idx') IS NULL THEN
                            ALTER INDEX public.staff_biome_user_id_04f2e6_idx RENAME TO staff_biome_user_id_16fc4d_idx;
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='staffbiometricpunchlog',
                    new_name='staff_biome_user_id_04f2e6_idx',
                    old_name='staff_biome_user_id_16fc4d_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('public.staff_biome_source_9bbd35_idx') IS NOT NULL
                           AND to_regclass('public.staff_biome_source_2bf6a8_idx') IS NULL THEN
                            ALTER INDEX public.staff_biome_source_9bbd35_idx RENAME TO staff_biome_source_2bf6a8_idx;
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('public.staff_biome_source_2bf6a8_idx') IS NOT NULL
                           AND to_regclass('public.staff_biome_source_9bbd35_idx') IS NULL THEN
                            ALTER INDEX public.staff_biome_source_2bf6a8_idx RENAME TO staff_biome_source_9bbd35_idx;
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='staffbiometricpunchlog',
                    new_name='staff_biome_source_2bf6a8_idx',
                    old_name='staff_biome_source_9bbd35_idx',
                ),
            ],
        ),
    ]
