# Generated by Django 4.2.28 on 2026-08-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('staff_attendance', '0023_harden_college_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendancerecords', to='college.college'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendancesettings', to='college.college'),
        ),
        migrations.AlterField(
            model_name='departmentattendancesettings',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmentattendancesettings', to='college.college'),
        ),
        migrations.AlterField(
            model_name='halfdayrequest',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halfdayrequests', to='college.college'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='college.college'),
        ),
        migrations.AlterField(
            model_name='specialdepartmentdateattendancelimit',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialdepartmentdateattendancelimits', to='college.college'),
        ),
        migrations.AlterField(
            model_name='staffattendancetimelimitoverride',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffattendancetimelimitoverrides', to='college.college'),
        ),
        migrations.AlterField(
            model_name='staffbiometricpunchlog',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffbiometricpunchlogs', to='college.college'),
        ),
        migrations.AlterField(
            model_name='uploadlog',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadlogs', to='college.college'),
        ),
    ]
