# Generated by Django 4.2.28 on 2026-04-12 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0085_add_internal_external_ids'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2ClassType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('short_code', models.CharField(max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('total_internal_marks', models.DecimalField(decimal_places=2, default=40, max_digits=6)),
                ('allow_customize_questions', models.BooleanField(default=False)),
                ('exam_assignments', models.JSONField(blank=True, default=list)),
                ('default_co_count', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acv2_class_types', to='college.college')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_class_types_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Type',
                'verbose_name_plural': 'Class Types',
                'db_table': 'acv2_class_type',
            },
        ),
        migrations.CreateModel(
            name='AcV2Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(db_index=True, max_length=64)),
                ('subject_name', models.CharField(max_length=255)),
                ('class_type_name', models.CharField(default='THEORY', max_length=50)),
                ('question_paper_type', models.CharField(blank=True, max_length=50, null=True)),
                ('co_count', models.IntegerField(default=5)),
                ('co_titles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academic_v2.acv2classtype')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_courses', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_courses', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'acv2_course',
            },
        ),
        migrations.CreateModel(
            name='AcV2ExamAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam', models.CharField(max_length=50)),
                ('exam_display_name', models.CharField(blank=True, max_length=100)),
                ('qp_type', models.CharField(blank=True, max_length=50)),
                ('max_marks', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('covered_cos', models.JSONField(blank=True, default=list)),
                ('qp_pattern', models.JSONField(blank=True, default=dict)),
                ('allow_customize', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20)),
                ('draft_data', models.JSONField(blank=True, default=dict)),
                ('published_data', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('has_pending_edit_request', models.BooleanField(default=False)),
                ('edit_window_until', models.DateTimeField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_saved_exams', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_published_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Assignment',
                'verbose_name_plural': 'Exam Assignments',
                'db_table': 'acv2_exam_assignment',
            },
        ),
        migrations.CreateModel(
            name='AcV2UserPatternOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(max_length=50)),
                ('pattern', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pattern_overrides', to='academic_v2.acv2course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_pattern_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Pattern Override',
                'verbose_name_plural': 'User Pattern Overrides',
                'db_table': 'acv2_user_pattern_override',
            },
        ),
        migrations.CreateModel(
            name='AcV2StudentMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=255)),
                ('co1_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('co2_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('co3_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('co4_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('co5_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weighted_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('question_marks', models.JSONField(blank=True, default=dict)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_exempted', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='academic_v2.acv2examassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_marks', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
                'db_table': 'acv2_student_mark',
            },
        ),
        migrations.CreateModel(
            name='AcV2SemesterConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publish_control_enabled', models.BooleanField(default=True)),
                ('approval_workflow', models.JSONField(blank=True, default=list)),
                ('approval_window_minutes', models.IntegerField(default=120)),
                ('open_from', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('auto_publish_on_due', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_config', to='academics.semester')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_semester_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semester Configuration',
                'verbose_name_plural': 'Semester Configurations',
                'db_table': 'acv2_semester_config',
            },
        ),
        migrations.CreateModel(
            name='AcV2Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic_v2.acv2course')),
                ('faculty_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_sections', to=settings.AUTH_USER_MODEL)),
                ('teaching_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_sections', to='academics.teachingassignment')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'acv2_section',
            },
        ),
        migrations.CreateModel(
            name='AcV2QpPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qp_type', models.CharField(max_length=50)),
                ('pattern', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acv2_qp_patterns', to='academics.batch')),
                ('class_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qp_patterns', to='academic_v2.acv2classtype')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acv2_qp_patterns', to='college.college')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_qp_patterns_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QP Pattern',
                'verbose_name_plural': 'QP Patterns',
                'db_table': 'acv2_qp_pattern',
            },
        ),
        migrations.CreateModel(
            name='AcV2InternalMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=255)),
                ('weighted_marks', models.JSONField(blank=True, default=dict)),
                ('co1_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('co2_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('co3_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('co4_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('co5_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('final_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_mark', models.DecimalField(decimal_places=2, default=40, max_digits=6)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='academic_v2.acv2section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_internal_marks', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Internal Mark',
                'verbose_name_plural': 'Internal Marks',
                'db_table': 'acv2_internal_mark',
            },
        ),
        migrations.AddField(
            model_name='acv2examassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='academic_v2.acv2section'),
        ),
        migrations.CreateModel(
            name='AcV2EditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HOD_PENDING', 'Pending HOD Approval'), ('IQAC_PENDING', 'Pending IQAC Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('current_stage', models.IntegerField(default=1)),
                ('approval_history', models.JSONField(blank=True, default=list)),
                ('approved_until', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('exam_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='academic_v2.acv2examassignment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edit Request',
                'verbose_name_plural': 'Edit Requests',
                'db_table': 'acv2_edit_request',
            },
        ),
        migrations.AddConstraint(
            model_name='acv2userpatternoverride',
            constraint=models.UniqueConstraint(fields=('course', 'exam_type', 'created_by'), name='unique_acv2_user_pattern_per_course_exam_user'),
        ),
        migrations.AddIndex(
            model_name='acv2studentmark',
            index=models.Index(fields=['exam_assignment', 'reg_no'], name='acv2_studen_exam_as_521f96_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2studentmark',
            index=models.Index(fields=['student'], name='acv2_studen_student_c729ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='acv2studentmark',
            constraint=models.UniqueConstraint(fields=('exam_assignment', 'student'), name='unique_acv2_student_mark_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='acv2section',
            constraint=models.UniqueConstraint(fields=('course', 'teaching_assignment'), name='unique_acv2_section_per_course_ta'),
        ),
        migrations.AddIndex(
            model_name='acv2qppattern',
            index=models.Index(fields=['qp_type', 'class_type'], name='acv2_qp_pat_qp_type_11fae1_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2qppattern',
            index=models.Index(fields=['batch', 'qp_type'], name='acv2_qp_pat_batch_i_4e56e5_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2internalmark',
            index=models.Index(fields=['section', 'reg_no'], name='acv2_intern_section_25bed4_idx'),
        ),
        migrations.AddConstraint(
            model_name='acv2internalmark',
            constraint=models.UniqueConstraint(fields=('section', 'student'), name='unique_acv2_internal_mark_per_section_student'),
        ),
        migrations.AddIndex(
            model_name='acv2examassignment',
            index=models.Index(fields=['section', 'exam'], name='acv2_exam_a_section_739a69_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2examassignment',
            index=models.Index(fields=['status'], name='acv2_exam_a_status_1bc29b_idx'),
        ),
        migrations.AddConstraint(
            model_name='acv2examassignment',
            constraint=models.UniqueConstraint(fields=('section', 'exam'), name='unique_acv2_exam_per_section'),
        ),
        migrations.AddIndex(
            model_name='acv2editrequest',
            index=models.Index(fields=['status', 'requested_at'], name='acv2_edit_r_status_d434bc_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2editrequest',
            index=models.Index(fields=['exam_assignment', 'status'], name='acv2_edit_r_exam_as_151009_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2editrequest',
            index=models.Index(fields=['requested_by', 'status'], name='acv2_edit_r_request_17557d_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2course',
            index=models.Index(fields=['subject_code', 'semester'], name='acv2_course_subject_262be9_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2course',
            index=models.Index(fields=['class_type_name'], name='acv2_course_class_t_44aab9_idx'),
        ),
        migrations.AddConstraint(
            model_name='acv2course',
            constraint=models.UniqueConstraint(fields=('subject', 'semester'), name='unique_acv2_course_per_subject_semester'),
        ),
        migrations.AddConstraint(
            model_name='acv2classtype',
            constraint=models.UniqueConstraint(condition=models.Q(('college__isnull', False)), fields=('name', 'college'), name='unique_acv2_class_type_per_college'),
        ),
        migrations.AddConstraint(
            model_name='acv2classtype',
            constraint=models.UniqueConstraint(condition=models.Q(('college__isnull', True)), fields=('name',), name='unique_acv2_class_type_global'),
        ),
    ]
