# Generated by Django 4.2.28 on 2026-04-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0003_acv2qppattern_name_default_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='acv2editrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acv2examassignment',
            name='edit_window_until_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acv2semesterconfig',
            name='approval_until_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acv2semesterconfig',
            name='edit_request_validity_hours',
            field=models.IntegerField(default=24),
        ),
    ]
