# Generated by Django 4.2.28 on 2026-04-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0005_acv2draftmark'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='acv2draftmark',
            new_name='acv2_draft__exam_as_11d6fe_idx',
            old_name='acv2_draft__exam_as_2eb8ce_idx',
        ),
        migrations.RenameIndex(
            model_name='acv2draftmark',
            new_name='acv2_draft__student_f9d545_idx',
            old_name='acv2_draft__student_c8312f_idx',
        ),
    ]
