# Generated by Django 4.2.28 on 2026-04-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0006_rename_acv2_draft__exam_as_2eb8ce_idx_acv2_draft__exam_as_11d6fe_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acv2semesterconfig',
            name='seal_animation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acv2semesterconfig',
            name='seal_image',
            field=models.ImageField(blank=True, null=True, upload_to='academic_v2/seals/'),
        ),
        migrations.AddField(
            model_name='acv2semesterconfig',
            name='seal_watermark_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
