# Generated by Django 4.2.28 on 2026-04-19 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_v2', '0007_acv2semesterconfig_seal_animation_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2QpType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acv2_qp_types', to='college.college')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_qp_types_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QP Type',
                'verbose_name_plural': 'QP Types',
                'db_table': 'acv2_qp_type',
            },
        ),
        migrations.CreateModel(
            name='AcV2QpAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qp_assignments', to='academic_v2.acv2classtype')),
                ('exam_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qp_assignments', to='academic_v2.acv2examassignment')),
                ('qp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic_v2.acv2qptype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_qp_assignments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QP Assignment',
                'verbose_name_plural': 'QP Assignments',
                'db_table': 'acv2_qp_assignment',
            },
        ),
        migrations.CreateModel(
            name='AcV2Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('btl_level', models.IntegerField(blank=True, choices=[(1, 'BTL 1'), (2, 'BTL 2'), (3, 'BTL 3'), (4, 'BTL 4'), (5, 'BTL 5'), (6, 'BTL 6')], null=True)),
                ('co_number', models.IntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qp_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academic_v2.acv2qppattern')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_questions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'acv2_question',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['qp_pattern', 'order'], name='acv2_questi_qp_patt_1e8305_idx'), models.Index(fields=['co_number'], name='acv2_questi_co_numb_afae8a_idx'), models.Index(fields=['is_enabled'], name='acv2_questi_is_enab_a4a7a6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='acv2question',
            constraint=models.UniqueConstraint(fields=('qp_pattern', 'order'), name='unique_question_order_per_pattern'),
        ),
        migrations.AddIndex(
            model_name='acv2qptype',
            index=models.Index(fields=['is_active', 'college'], name='acv2_qp_typ_is_acti_65c73d_idx'),
        ),
        migrations.AddConstraint(
            model_name='acv2qptype',
            constraint=models.UniqueConstraint(condition=models.Q(('college__isnull', False)), fields=('name', 'college'), name='unique_acv2_qp_type_per_college'),
        ),
        migrations.AddConstraint(
            model_name='acv2qptype',
            constraint=models.UniqueConstraint(condition=models.Q(('college__isnull', False)), fields=('code', 'college'), name='unique_acv2_qp_type_code_per_college'),
        ),
        migrations.AddIndex(
            model_name='acv2qpassignment',
            index=models.Index(fields=['class_type', 'qp_type'], name='acv2_qp_ass_class_t_932be9_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2qpassignment',
            index=models.Index(fields=['is_active'], name='acv2_qp_ass_is_acti_9445d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='acv2qpassignment',
            constraint=models.UniqueConstraint(fields=('class_type', 'qp_type', 'exam_assignment'), name='unique_qp_assignment'),
        ),
    ]
