# Generated by Django 4.2.28 on 2026-04-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0008_add_qp_type_question_assignment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='acv2qptype',
            name='class_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qp_types', to='academic_v2.acv2classtype'),
        ),
    ]
