# Generated by Django 4.2.28 on 2026-04-21 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_v2', '0012_backfill_qp_assignments_from_patterns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weigthts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qp_type', models.CharField(db_index=True, max_length=50)),
                ('exam', models.CharField(db_index=True, max_length=100)),
                ('exam_display_name', models.CharField(blank=True, default='', max_length=150)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('co_weights', models.JSONField(blank=True, default=dict)),
                ('default_cos', models.JSONField(blank=True, default=list)),
                ('mark_manager_enabled', models.BooleanField(default=False)),
                ('mm_co_weights_with_exam', models.JSONField(blank=True, default=dict)),
                ('mm_co_weights_without_exam', models.JSONField(blank=True, default=dict)),
                ('mm_exam_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights_rows', to='academic_v2.acv2classtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_weights_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weights',
                'verbose_name_plural': 'Weights',
                'db_table': 'Weigthts',
                'indexes': [models.Index(fields=['class_type', 'qp_type'], name='Weigthts_class_t_e66afd_idx'), models.Index(fields=['qp_type', 'exam'], name='Weigthts_qp_type_854c4b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='weigthts',
            constraint=models.UniqueConstraint(fields=('class_type', 'qp_type', 'exam'), name='unique_weights_per_class_qp_exam'),
        ),
    ]
