# Generated by Django 4.2.28 on 2026-04-25 07:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('academic_v2', '0014_backfill_weigthts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acv2_cycles', to='college.college')),
            ],
            options={
                'verbose_name': 'Academic Cycle',
                'verbose_name_plural': 'Academic Cycles',
                'db_table': 'acv2_cycle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='acv2qppattern',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qp_patterns', to='academic_v2.acv2cycle'),
        ),
    ]
