# Generated by Django 4.2.28 on 2026-04-27 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0085_add_internal_external_ids'),
        ('academic_v2', '0015_cycle_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2CqiAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('co_numbers', models.JSONField(blank=True, default=list)),
                ('threshold_percent', models.FloatField(default=58.0)),
                ('draft_entries', models.JSONField(blank=True, default=dict)),
                ('draft_updated_by', models.IntegerField(blank=True, null=True)),
                ('draft_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teaching_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_cqi_assignment', to='academics.teachingassignment')),
            ],
            options={
                'verbose_name': 'CQI Assignment',
                'verbose_name_plural': 'CQI Assignments',
                'db_table': 'acv2_cqi_assignment',
            },
        ),
        migrations.CreateModel(
            name='AcV2CqiAttained',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('co_numbers', models.JSONField(blank=True, default=list)),
                ('entries', models.JSONField(blank=True, default=dict)),
                ('published_by', models.IntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teaching_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_cqi_attained', to='academics.teachingassignment')),
            ],
            options={
                'verbose_name': 'CQI Attained',
                'verbose_name_plural': 'CQI Attained',
                'db_table': 'acv2_cqi_attained',
            },
        ),
        migrations.AddIndex(
            model_name='acv2cqiassignment',
            index=models.Index(fields=['draft_updated_at'], name='acv2_cqi_a_draft_u_5d77e2_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2cqiattained',
            index=models.Index(fields=['published_at'], name='acv2_cqi_a_publish_ef712f_idx'),
        ),
    ]
