# Generated by Django 4.2.28 on 2026-04-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0016_acv2_cqi_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='acv2cqiassignment',
            new_name='acv2_cqi_as_draft_u_5411c8_idx',
            old_name='acv2_cqi_a_draft_u_5d77e2_idx',
        ),
        migrations.RenameIndex(
            model_name='acv2cqiattained',
            new_name='acv2_cqi_at_publish_11d65e_idx',
            old_name='acv2_cqi_a_publish_ef712f_idx',
        ),
    ]
