# Generated by Django 4.2.28 on 2026-05-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0018_acv2cycle_inactive_semester_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='acv2qpassignment',
            name='pass_mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
