# Generated by Django 4.2.28 on 2026-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0019_add_pass_mark_to_qp_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acv2cycle',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Academic Cycle', 'verbose_name_plural': 'Academic Cycles'},
        ),
        migrations.AddField(
            model_name='acv2cycle',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
