# Generated by Django 4.2.28 on 2026-05-18 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0085_add_internal_external_ids'),
        ('academic_v2', '0026_acv2_academic_notification_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2CqiExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qp_type_code', models.CharField(db_index=True, max_length=50)),
                ('exam_code', models.CharField(max_length=50)),
                ('exam_display_name', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cqi_name', models.CharField(blank=True, max_length=255)),
                ('cqi_code', models.CharField(blank=True, max_length=50)),
                ('cycle_id', models.CharField(blank=True, max_length=100)),
                ('cos', models.JSONField(blank=True, default=list)),
                ('considered_exams', models.JSONField(blank=True, default=list)),
                ('custom_vars', models.JSONField(blank=True, default=list)),
                ('global_custom_vars', models.JSONField(blank=True, default=list)),
                ('derived_variables', models.JSONField(blank=True, default=list)),
                ('co_value_expr', models.TextField(blank=True)),
                ('formula', models.TextField(blank=True)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('else_formula', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cqi_exams', to='academic_v2.acv2classtype')),
                ('qp_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cqi_exams', to='academic_v2.acv2qpassignment')),
                ('qp_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cqi_exams', to='academic_v2.acv2qptype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_cqi_exam_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CQI Exam',
                'verbose_name_plural': 'CQI Exams',
                'db_table': 'acv2_cqi_exam',
            },
        ),
        migrations.CreateModel(
            name='AcV2CqiMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('co_number', models.PositiveSmallIntegerField()),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cqi_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academic_v2.acv2cqiexam')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cqi_marks', to='academic_v2.acv2section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_cqi_marks', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'CQI Mark',
                'verbose_name_plural': 'CQI Marks',
                'db_table': 'acv2_cqi_mark',
                'indexes': [models.Index(fields=['cqi_exam', 'section'], name='acv2_cqi_ma_cqi_exa_c2e9ca_idx'), models.Index(fields=['student'], name='acv2_cqi_ma_student_12edba_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='acv2cqimark',
            constraint=models.UniqueConstraint(fields=('cqi_exam', 'section', 'student', 'co_number'), name='unique_acv2_cqi_mark_per_exam_student_co'),
        ),
        migrations.AddIndex(
            model_name='acv2cqiexam',
            index=models.Index(fields=['class_type', 'qp_type_code', 'order'], name='acv2_cqi_ex_class_t_ad2ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='acv2cqiexam',
            index=models.Index(fields=['class_type', 'qp_type_code', 'exam_code'], name='acv2_cqi_ex_class_t_5fccbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='acv2cqiexam',
            constraint=models.UniqueConstraint(fields=('class_type', 'qp_type_code', 'exam_code'), name='unique_acv2_cqi_exam_per_ct_qpt_exam'),
        ),
    ]
