# Generated by GitHub Copilot on 2026-05-18

from django.db import migrations


def forwards(apps, schema_editor):
    AcV2ClassType = apps.get_model('academic_v2', 'AcV2ClassType')
    AcV2CqiExam = apps.get_model('academic_v2', 'AcV2CqiExam')
    AcV2QpType = apps.get_model('academic_v2', 'AcV2QpType')

    for ct in AcV2ClassType.objects.all().iterator():
        ea_list = ct.exam_assignments or []
        if not isinstance(ea_list, list) or not ea_list:
            continue

        global_vars = getattr(ct, 'cqi_global_custom_vars', [])
        if not isinstance(global_vars, list):
            global_vars = []

        for idx, ea in enumerate(ea_list):
            if not isinstance(ea, dict):
                continue
            if str(ea.get('kind') or '').strip().lower() != 'cqi' and ea.get('is_cqi') is not True:
                continue

            qp_type_code = str(ea.get('qp_type') or '').strip()
            if not qp_type_code:
                continue

            exam_code = str(ea.get('exam') or '').strip()
            exam_display = str(ea.get('exam_display_name') or '').strip()
            if not exam_code and exam_display:
                exam_code = exam_display
            if not exam_code:
                continue

            cqi = ea.get('cqi') if isinstance(ea.get('cqi'), dict) else {}
            qp_type_obj = (
                AcV2QpType.objects.filter(is_active=True, code__iexact=qp_type_code)
                .order_by('-class_type_id')
                .first()
            )

            defaults = {
                'qp_type': qp_type_obj,
                'exam_display_name': exam_display,
                'order': int(ea.get('order') or (idx + 1)),
                'is_active': bool(ea.get('enabled', True)),
                'cqi_name': str(cqi.get('name') or ''),
                'cqi_code': str(cqi.get('code') or ''),
                'cycle_id': str(cqi.get('cycle_id') or ''),
                'cos': cqi.get('cos', []) if isinstance(cqi.get('cos'), list) else [],
                'considered_exams': cqi.get('exams', []) if isinstance(cqi.get('exams'), list) else [],
                'custom_vars': cqi.get('custom_vars', []) if isinstance(cqi.get('custom_vars'), list) else [],
                'global_custom_vars': global_vars,
                'derived_variables': cqi.get('derived_variables', []) if isinstance(cqi.get('derived_variables'), list) else [],
                'co_value_expr': str(cqi.get('co_value_expr') or ''),
                'formula': str(cqi.get('formula') or ''),
                'conditions': cqi.get('conditions', []) if isinstance(cqi.get('conditions'), list) else [],
                'else_formula': str(cqi.get('else_formula') or ''),
                'updated_by': None,
            }

            AcV2CqiExam.objects.update_or_create(
                class_type=ct,
                qp_type_code=qp_type_code,
                exam_code=exam_code,
                defaults=defaults,
            )


def backwards(apps, schema_editor):
    # Non-destructive: keep any CQI exam rows (could have been edited after backfill).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0027_acv2cqiexam_acv2cqimark_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
