# Generated by Django 4.2.28 on 2026-05-18 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_v2', '0028_backfill_cqi_exams_from_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='acv2cqiattained',
            name='edit_window_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acv2cqiattained',
            name='has_pending_edit_request',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AcV2CqiEditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HOD_PENDING', 'Pending HOD Approval'), ('IQAC_PENDING', 'Pending IQAC Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('current_stage', models.IntegerField(default=1)),
                ('approval_history', models.JSONField(blank=True, default=list)),
                ('approved_until', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cqi_attained', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='academic_v2.acv2cqiattained')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_cqi_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_cqi_reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CQI Edit Request',
                'verbose_name_plural': 'CQI Edit Requests',
                'db_table': 'acv2_cqi_edit_request',
                'indexes': [models.Index(fields=['status', 'requested_at'], name='acv2_cqi_ed_status_f79a76_idx'), models.Index(fields=['cqi_attained', 'status'], name='acv2_cqi_ed_cqi_att_b222a5_idx')],
            },
        ),
    ]
