# Generated by Django 4.2.28 on 2026-05-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0029_cqi_edit_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='acv2cqiassignment',
            name='cap_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
