# Generated by Django 4.2.28 on 2026-05-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0030_cqi_cap_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acv2cqiassignment',
            name='cap_enabled',
        ),
    ]
