# Generated by Django 4.2.28 on 2026-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0031_remove_acv2cqiassignment_cap_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2MyMarksSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='DEFAULT', max_length=50, unique=True)),
                ('viewing_enabled', models.BooleanField(default=False)),
                ('require_profile_photo', models.BooleanField(default=False)),
                ('require_mobile_number', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'My Marks Setting',
                'verbose_name_plural': 'My Marks Settings',
                'db_table': 'acv2_my_marks_setting',
            },
        ),
    ]
