# Generated by Django 4.2.28 on 2026-05-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0033_alter_acv2mymarkssetting_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acv2mymarkssetting',
            name='student_pass_mark',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='acv2mymarkssetting',
            name='student_pass_mark_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acv2mymarkssetting',
            name='student_pass_mark_out_of',
            field=models.IntegerField(default=100),
        ),
    ]
