# Generated by Django 4.2.28 on 2026-05-25 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0085_add_internal_external_ids'),
        ('academic_v2', '0034_add_student_pass_mark_to_my_marks_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acv2mymarkssetting',
            name='student_pass_mark',
        ),
        migrations.RemoveField(
            model_name='acv2mymarkssetting',
            name='student_pass_mark_enabled',
        ),
        migrations.RemoveField(
            model_name='acv2mymarkssetting',
            name='student_pass_mark_out_of',
        ),
        migrations.CreateModel(
            name='VisualAdminStaffLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_url', models.TextField(blank=True, default='')),
                ('use_course_urls', models.BooleanField(default=False, help_text='If True, per-course links are used instead of the overall URL.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_admin_link', to='academics.staffprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_admin_staff_link_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visual Admin Staff Link',
                'verbose_name_plural': 'Visual Admin Staff Links',
                'db_table': 'visual_admin_staff_link',
            },
        ),
        migrations.CreateModel(
            name='VisualAdminCourseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='academic_v2.visualadminstafflink')),
                ('teaching_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_admin_course_links', to='academics.teachingassignment')),
            ],
            options={
                'verbose_name': 'Visual Admin Course Link',
                'verbose_name_plural': 'Visual Admin Course Links',
                'db_table': 'visual_admin_course_link',
                'unique_together': {('staff_link', 'teaching_assignment')},
            },
        ),
    ]
