# Generated by Django 4.2.28 on 2026-05-25 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0035_visual_admin_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2PublishSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(default='DEFAULT', max_length=40, unique=True)),
                ('must_fill_all_cells', models.BooleanField(default=False, help_text='Block publish if any non-absent student has an empty mark cell.')),
                ('publish_progress_duration', models.PositiveSmallIntegerField(default=4, help_text='Seconds the publish progress animation plays (1–30).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publish Setting',
                'verbose_name_plural': 'Publish Settings',
                'db_table': 'acv2_publish_setting',
            },
        ),
    ]
