# Generated by Django 4.2.28 on 2026-07-08 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_v2', '0036_publish_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2GoogleSheetsOAuthCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_user_email', models.EmailField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_uri', models.URLField(blank=True, max_length=512)),
                ('client_id', models.CharField(blank=True, max_length=512)),
                ('client_secret', models.CharField(blank=True, max_length=512)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acv2_google_sheets_oauth_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Sheets OAuth Credential',
                'verbose_name_plural': 'Google Sheets OAuth Credentials',
                'db_table': 'acv2_google_sheets_oauth_credential',
            },
        ),
    ]
