# Generated by Django 5.0.7 on 2026-07-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_v2', '0037_acv2googlesheetsoauthcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2CourseOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acv2_course_outcomes', to='college.college')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_course_outcomes_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Outcome',
                'verbose_name_plural': 'Course Outcomes',
                'db_table': 'acv2_course_outcome',
                'ordering': ['display_order', 'number'],
            },
        ),
        migrations.AddConstraint(
            model_name='acv2courseoutcome',
            constraint=models.UniqueConstraint(condition=models.Q(('college__isnull', False)), fields=('number', 'college'), name='unique_acv2_co_number_per_college'),
        ),
        migrations.AddConstraint(
            model_name='acv2courseoutcome',
            constraint=models.UniqueConstraint(condition=models.Q(('college__isnull', True)), fields=('number',), name='unique_acv2_co_number_global'),
        ),
    ]
