# Generated by Django 4.2.28 on 2026-07-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0087_alter_staffprofile_staff_id'),
        ('academic_v2', '0039_acv2_semester_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='acv2internalmark',
            name='co6_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='acv2semestergroup',
            name='semesters',
            field=models.ManyToManyField(blank=True, related_name='acv2_semester_groups', through='academic_v2.AcV2SemesterGroupMembership', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='acv2studentmark',
            name='co6_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
