# Generated by Django 4.2.28 on 2026-07-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0042_acv2academicnotificationsetting_row_filled_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='acv2googlesheetlink',
            new_name='acv2_google_spreads_5762d7_idx',
            old_name='acv2_googl_spreads_5035d0_idx',
        ),
        migrations.RenameIndex(
            model_name='acv2googlesheetlink',
            new_name='acv2_google_is_acti_aa9ebd_idx',
            old_name='acv2_googl_is_acti_261a95_idx',
        ),
    ]
