# Generated by Django 4.2.28 on 2026-08-27 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0096_remove_sectionadvisor_unique_active_advisor_per_section_year_and_more'),
        ('academic_v2', '0043_rename_acv2_googl_spreads_5035d0_idx_acv2_google_spreads_5762d7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2CoAttainment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('co_numbers', models.JSONField(blank=True, default=list)),
                ('columns_config', models.JSONField(blank=True, default=list)),
                ('column_averages', models.JSONField(blank=True, default=dict)),
                ('student_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teaching_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acv2_co_attainment', to='academics.teachingassignment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_co_attainments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CO Attainment',
                'verbose_name_plural': 'CO Attainments',
                'db_table': 'acv2_co_attainment',
                'indexes': [models.Index(fields=['updated_at'], name='acv2_co_att_updated_ff9b77_idx')],
            },
        ),
    ]
