# Generated by Django 4.2.28 on 2026-09-11 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0097_staffprofile_pbas_category_credits'),
        ('academic_v2', '0044_acv2coattainment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2SSAAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('SSA1', 'SSA 1'), ('SSA2', 'SSA 2')], max_length=10)),
                ('rubric_file', models.FileField(blank=True, upload_to='ssa_assignments/rubrics/')),
                ('first_page_file', models.FileField(blank=True, upload_to='ssa_assignments/first_pages/')),
                ('student_topic_file', models.FileField(blank=True, upload_to='ssa_assignments/topics/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssa_assignment', to='academic_v2.acv2examassignment')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssa_assignments_finalized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSA Assignment',
                'verbose_name_plural': 'SSA Assignments',
                'db_table': 'acv2_ssa_assignment',
            },
        ),
        migrations.CreateModel(
            name='AcV2SSASubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=64)),
                ('student_name', models.CharField(max_length=255)),
                ('submitted_file', models.FileField(blank=True, upload_to='ssa_submissions/originals/')),
                ('generated_file', models.FileField(blank=True, upload_to='ssa_submissions/generated/')),
                ('submission_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('SUBMITTED', 'Submitted'), ('UNDER_EVALUATION', 'Under Evaluation'), ('EVALUATED', 'Evaluated')], default='NOT_SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssa_evaluations', to=settings.AUTH_USER_MODEL)),
                ('ssa_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academic_v2.acv2ssaassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssa_submissions', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'SSA Submission',
                'verbose_name_plural': 'SSA Submissions',
                'db_table': 'acv2_ssa_submission',
                'indexes': [models.Index(fields=['ssa_assignment', 'submission_status'], name='acv2_ssa_su_ssa_ass_bd3dda_idx'), models.Index(fields=['student'], name='acv2_ssa_su_student_074f0b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='acv2ssasubmission',
            constraint=models.UniqueConstraint(fields=('ssa_assignment', 'student'), name='unique_ssa_submission_per_student'),
        ),
        migrations.AddConstraint(
            model_name='acv2ssaassignment',
            constraint=models.UniqueConstraint(fields=('exam_assignment',), name='unique_ssa_assignment_per_exam'),
        ),
    ]
