# Generated by Django 4.2.28 on 2026-09-15 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0097_staffprofile_pbas_category_credits'),
        ('academic_v2', '0045_acv2ssaassignment_acv2ssasubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic 2.1 Version',
                'verbose_name_plural': 'Academic 2.1 Versions',
                'db_table': 'acv2_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='acv2classtype',
            name='unique_acv2_class_type_per_college',
        ),
        migrations.RemoveConstraint(
            model_name='acv2classtype',
            name='unique_acv2_class_type_global',
        ),
        migrations.AddField(
            model_name='acv2version',
            name='academic_years',
            field=models.ManyToManyField(blank=True, related_name='acv2_versions', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='acv2version',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acv2_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acv2classtype',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_types', to='academic_v2.acv2version'),
        ),
        migrations.AddField(
            model_name='acv2cycle',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='academic_v2.acv2version'),
        ),
        migrations.AddField(
            model_name='acv2qppattern',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qp_patterns', to='academic_v2.acv2version'),
        ),
        migrations.AddField(
            model_name='acv2qptype',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qp_types', to='academic_v2.acv2version'),
        ),
        migrations.AddConstraint(
            model_name='acv2classtype',
            constraint=models.UniqueConstraint(condition=models.Q(('college__isnull', False)), fields=('name', 'version', 'college'), name='unique_acv2_class_type_per_college_version'),
        ),
        migrations.AddConstraint(
            model_name='acv2classtype',
            constraint=models.UniqueConstraint(condition=models.Q(('college__isnull', True)), fields=('name', 'version'), name='unique_acv2_class_type_version'),
        ),
    ]
