# Generated by Django 4.2.28 on 2026-09-16 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic_v2', '0046_acv2version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcV2FacultyRequestSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(default='DEFAULT', max_length=40, unique=True)),
                ('faculty_request_enabled', models.BooleanField(default=True)),
                ('require_mobile_verification', models.BooleanField(default=False)),
                ('require_profile_photo', models.BooleanField(default=False)),
                ('notify_on_request_sent', models.BooleanField(default=True)),
                ('notify_on_step_approved', models.BooleanField(default=True)),
                ('notify_on_final_approved', models.BooleanField(default=True)),
                ('notify_on_published', models.BooleanField(default=True)),
                ('request_sent_template', models.TextField(default='📋 *Faculty Edit Request Submitted*\nFaculty: *{faculty_name}* ({faculty_id})\nDepartment: {department}\nRequest Type: {request_type}\nDate: {request_date}\nStatus: Submitted for approval.')),
                ('step_approved_template', models.TextField(default='⏳ *Faculty Request - Step Approved*\nFaculty: *{faculty_name}*\nDepartment: {department}\nStep: *{step_name}*\nApproved By: {approved_by}\nDate: {approval_date}\nRemarks: {remarks}')),
                ('final_approved_template', models.TextField(default='✅ *Faculty Request - Final Approval Granted*\nFaculty: *{faculty_name}*\nDepartment: {department}\nApproved By: {approved_by}\nDate: {approval_date}\nRemarks: {remarks}\nEdit window is now open.')),
                ('published_template', models.TextField(default='📢 *Marks / Request Published*\nFaculty: *{faculty_name}* ({faculty_id})\nDepartment: {department}\nRequest Type: {request_type}\nPublished Date: {request_date}\nRemarks: {remarks}\nMarks have been published successfully.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty Request Setting',
                'verbose_name_plural': 'Faculty Request Settings',
                'db_table': 'acv2_faculty_request_setting',
            },
        ),
    ]
