# Generated by Django 4.2.28 on 2026-07-21 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionRegistryMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(help_text='Matches the section_id in the registry', max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Section Registry Meta',
            },
        ),
        migrations.CreateModel(
            name='ConfigExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_reference', models.CharField(blank=True, max_length=512)),
                ('export_type', models.CharField(choices=[('manual', 'Manual'), ('semester_archive', 'Semester Archive')], default='manual', max_length=32)),
                ('academic_year', models.CharField(blank=True, help_text='Only set when semester_archive', max_length=32, null=True)),
                ('semester_label', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('schema_version', models.CharField(default='1.0', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackupSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_id', models.CharField(help_text='References registry section_id', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_reference', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('schema_version', models.CharField(default='1.0', help_text='For future compatibility checks', max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('backup', 'Backup Created'), ('restore', 'Backup Restored'), ('config_export', 'Config Exported'), ('config_import', 'Config Imported')], max_length=32)),
                ('section_id', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True, help_text='Error messages or summary')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_export', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='backups_logs.configexport')),
                ('related_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='backups_logs.backupsnapshot')),
            ],
        ),
    ]
