# Generated by Django 4.2.28 on 2026-07-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsnapshot',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID tracking this operation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configexport',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID tracking this operation', max_length=255, null=True),
        ),
    ]
