# Generated by Django 4.2.28 on 2026-03-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('canva_design_id', models.CharField(max_length=256)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024)),
                ('is_brand_template', models.BooleanField(default=False)),
                ('edit_url', models.URLField(blank=True, max_length=1024)),
                ('saved_by', models.CharField(blank=True, max_length=64)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
