# Generated by Django 4.2.28 on 2026-03-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_api', '0002_canvatemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvaServiceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.BigIntegerField(default=0)),
                ('user_id', models.CharField(blank=True, max_length=256)),
                ('display_name', models.CharField(blank=True, max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canva Service Token',
            },
        ),
    ]
