# Generated by Django 4.2.28 on 2026-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_api', '0003_canvaservicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvaOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=64, unique=True)),
                ('verifier', models.TextField()),
                ('redirect_uri', models.CharField(max_length=1024)),
                ('origin', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canva OAuth State',
            },
        ),
    ]
