# Generated by Django 4.2.28 on 2026-03-14 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template_api', '0004_canvaoauthstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, db_index=True, max_length=512)),
                ('request_method', models.CharField(blank=True, db_index=True, max_length=16)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=256)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branding Event Log',
                'verbose_name_plural': 'Branding Event Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='template_ap_event_t_75f3d7_idx'), models.Index(fields=['status', '-created_at'], name='template_ap_status_705581_idx'), models.Index(fields=['event_id', '-created_at'], name='template_ap_event_i_475aed_idx'), models.Index(fields=['reference_id', '-created_at'], name='template_ap_referen_95e965_idx')],
            },
        ),
    ]
