# Generated by generate_college_migrations.py
# Add nullable college FK to all tenant models in template_api

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('template_api', '0006_merge_20260317_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvatemplate',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='canvatemplates',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='eventposterattachment',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='eventposterattachments',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='brandingeventlog',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='brandingeventlogs',
                to='college.college',
            ),
        ),
    ]
