# Generated by generate_college_migrations.py
# Harden: make college FK non-nullable on all template_api models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('template_api', '0008_backfill_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvatemplate',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='canvatemplates',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='eventposterattachment',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='eventposterattachments',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='brandingeventlog',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='brandingeventlogs',
                to='college.college',
            ),
        ),
    ]
