# Generated by Django 4.2.28 on 2026-02-27 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HodColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_color', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hod_colors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('all_day', models.BooleanField(default=True)),
                ('audience_department', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('year_label', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.CharField(choices=[('iqac', 'IQAC'), ('hod', 'HOD')], max_length=8)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('audience_students', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['start_date'], name='academic_ca_start_d_3fb325_idx'), models.Index(fields=['end_date'], name='academic_ca_end_dat_301af7_idx'), models.Index(fields=['source'], name='academic_ca_source_2303af_idx')],
            },
        ),
    ]
