# Generated by Django 4.2.28 on 2026-03-12 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0062_studentcourseenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_calendar', '0002_academiccalendarevent_branding_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('department_name', models.CharField(blank=True, max_length=256)),
                ('event_type', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=512)),
                ('mode', models.CharField(blank=True, max_length=64)),
                ('expert_category', models.CharField(blank=True, max_length=8)),
                ('is_repeated', models.BooleanField(default=False)),
                ('participants', models.CharField(blank=True, max_length=512)),
                ('coordinator_name', models.CharField(blank=True, max_length=256)),
                ('co_coordinator_name', models.CharField(blank=True, max_length=256)),
                ('chief_guest_name', models.CharField(blank=True, max_length=256)),
                ('chief_guest_designation', models.CharField(blank=True, max_length=256)),
                ('chief_guest_affiliation', models.CharField(blank=True, max_length=256)),
                ('proposal_data', models.JSONField(blank=True, default=dict)),
                ('poster_url', models.TextField(blank=True)),
                ('poster_data_url', models.TextField(blank=True)),
                ('proposal_doc_url', models.TextField(blank=True)),
                ('proposal_doc_name', models.CharField(blank=True, max_length=256)),
                ('canva_design_id', models.CharField(blank=True, max_length=256)),
                ('canva_edit_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('forwarded_to_branding', 'Forwarded to Branding'), ('forwarded_to_hod', 'Forwarded to HOD'), ('hod_approved', 'HOD Approved'), ('forwarded_to_haa', 'Forwarded to HAA'), ('haa_approved', 'HAA Approved'), ('rejected', 'Rejected')], default='draft', max_length=32)),
                ('created_by_name', models.CharField(blank=True, max_length=256)),
                ('branding_reviewed_by_name', models.CharField(blank=True, max_length=256)),
                ('branding_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('branding_note', models.TextField(blank=True)),
                ('hod_approved_by_name', models.CharField(blank=True, max_length=256)),
                ('hod_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hod_note', models.TextField(blank=True)),
                ('haa_approved_by_name', models.CharField(blank=True, max_length=256)),
                ('haa_approved_at', models.DateTimeField(blank=True, null=True)),
                ('haa_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branding_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_proposals', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_proposals', to='academics.department')),
                ('haa_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hod_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='academic_ca_status_1648e3_idx'), models.Index(fields=['department'], name='academic_ca_departm_b98e6a_idx'), models.Index(fields=['created_by'], name='academic_ca_created_fb90f1_idx')],
            },
        ),
    ]
