# Generated by Django 4.2.28 on 2026-03-16 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_calendar', '0003_eventproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproposal',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='final_poster_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_proposals', to=settings.AUTH_USER_MODEL),
        ),
    ]
