# Generated by Django 4.2.28 on 2026-04-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_calendar', '0004_eventproposal_extra_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=16)),
                ('visible_roles', models.JSONField(blank=True, default=list)),
                ('semesters', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_ref', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_assignments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic_calendar.calendareventlabel')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='calendareventlabel',
            index=models.Index(fields=['created_at'], name='academic_ca_created_28aee4_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventassignment',
            index=models.Index(fields=['calendar_ref'], name='academic_ca_calenda_9fb698_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventassignment',
            index=models.Index(fields=['start_date', 'end_date'], name='academic_ca_start_d_d5e885_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventassignment',
            index=models.Index(fields=['event'], name='academic_ca_event_i_2d5044_idx'),
        ),
    ]
