# Generated by Django 4.2.28 on 2026-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0006_academic_calendar_tables'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='academiccalendar',
            new_name='academic_ca_from_da_4cfb83_idx',
            old_name='academic_ca_from_da_45d2fe_idx',
        ),
        migrations.RenameIndex(
            model_name='academiccalendar',
            new_name='academic_ca_to_date_dc291d_idx',
            old_name='academic_ca_to_dat_2d7a0f_idx',
        ),
        migrations.RenameIndex(
            model_name='academiccalendarday',
            new_name='academic_ca_calenda_1ab5ee_idx',
            old_name='academic_ca_calendar_9f2cd9_idx',
        ),
        migrations.RenameIndex(
            model_name='academiccalendarholiday',
            new_name='academic_ca_calenda_fd876a_idx',
            old_name='academic_ca_calendar_d35f4c_idx',
        ),
        migrations.AlterField(
            model_name='academiccalendarday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='academiccalendarholiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
