# Generated by Django 4.2.28 on 2026-08-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0007_rename_academic_ca_from_da_45d2fe_idx_academic_ca_from_da_4cfb83_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academiccalendarday',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='academiccalendarday',
            name='calendar',
        ),
        migrations.AlterUniqueTogether(
            name='academiccalendarholiday',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='academiccalendarholiday',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='calendareventassignment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='calendareventassignment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='calendareventlabel',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AcademicCalendar',
        ),
        migrations.DeleteModel(
            name='AcademicCalendarDay',
        ),
        migrations.DeleteModel(
            name='AcademicCalendarHoliday',
        ),
        migrations.DeleteModel(
            name='CalendarEventAssignment',
        ),
        migrations.DeleteModel(
            name='CalendarEventLabel',
        ),
    ]
