# Generated by generate_college_migrations.py
# Harden: make college FK non-nullable on all academic_calendar models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('academic_calendar', '0009_backfill_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendarevent',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='academiccalendarevents',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='hodcolor',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hodcolors',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='eventproposals',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='calendareventlabel',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='calendareventlabels',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='calendareventassignment',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='calendareventassignments',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='academiccalendars',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='academiccalendarday',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='academiccalendardays',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='academiccalendarholiday',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='academiccalendarholidays',
                to='college.college',
            ),
        ),
    ]
