# Generated by Django 4.2.28 on 2026-08-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('academic_calendar', '0010_harden_college_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academiccalendars', to='college.college'),
        ),
        migrations.AlterField(
            model_name='academiccalendarday',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academiccalendardays', to='college.college'),
        ),
        migrations.AlterField(
            model_name='academiccalendarevent',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academiccalendarevents', to='college.college'),
        ),
        migrations.AlterField(
            model_name='academiccalendarholiday',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academiccalendarholidays', to='college.college'),
        ),
        migrations.AlterField(
            model_name='calendareventassignment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendareventassignments', to='college.college'),
        ),
        migrations.AlterField(
            model_name='calendareventlabel',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendareventlabels', to='college.college'),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventproposals', to='college.college'),
        ),
        migrations.AlterField(
            model_name='hodcolor',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodcolors', to='college.college'),
        ),
    ]
