# Generated by Django 4.2.28 on 2026-04-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0086_staffprofile_date_of_join'),
        ('lms', '0006_studymaterial_co_title_sub_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='shared_courses',
            field=models.ManyToManyField(blank=True, related_name='shared_study_materials', to='academics.course'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='shared_teaching_assignments',
            field=models.ManyToManyField(blank=True, related_name='shared_study_materials', to='academics.teachingassignment'),
        ),
    ]
