# Generated by Django 4.2.28 on 2026-08-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_studymaterial_shared_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='shared_courses',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='shared_teaching_assignments',
        ),
    ]
