# Generated by Django 4.2.28 on 2026-08-19 04:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0092_remove_studentprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(blank=True, help_text='e.g. After CIA 1', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Audit Cycle',
                'verbose_name_plural': 'Audit Cycles',
                'db_table': 'audit_cycle',
                'ordering': ('cycle',),
            },
        ),
        migrations.CreateModel(
            name='AuditDepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted')], default='NOT_STARTED', max_length=16)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('auditors', models.ManyToManyField(blank=True, related_name='audit_assignments', to='academics.staffprofile')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='audits.auditcycle')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_assignments', to='academics.department')),
            ],
            options={
                'verbose_name': 'Audit Department Assignment',
                'verbose_name_plural': 'Audit Department Assignments',
                'db_table': 'audit_department_assignment',
                'ordering': ('cycle__cycle', 'department__code'),
                'unique_together': {('department', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='AuditQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('details', models.CharField(max_length=300)),
                ('documents_checklist', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Audit Question',
                'verbose_name_plural': 'Audit Questions',
                'db_table': 'audit_question',
                'ordering': ('sl_no',),
            },
        ),
        migrations.CreateModel(
            name='AuditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comments', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='audits.auditdepartmentassignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_scores', to='audits.auditquestion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_scores_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Score',
                'verbose_name_plural': 'Audit Scores',
                'db_table': 'audit_score',
                'ordering': ('question__sl_no',),
                'unique_together': {('assignment', 'question')},
            },
        ),
        migrations.CreateModel(
            name='AuditATR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted')], default='PENDING', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atrs', to='audits.auditdepartmentassignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_atrs', to='audits.auditquestion')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_atrs_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit ATR',
                'verbose_name_plural': 'Audit ATRs',
                'db_table': 'audit_atr',
                'ordering': ('question__sl_no',),
                'unique_together': {('assignment', 'question')},
            },
        ),
    ]
