# Generated by Django 4.2.28 on 2026-08-20 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='audit_rubrics/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_rubrics_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Rubric',
                'verbose_name_plural': 'Audit Rubrics',
                'db_table': 'audit_rubric',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_question_sets_created', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(blank=True, related_name='question_sets', to='audits.auditquestion')),
            ],
            options={
                'verbose_name': 'Audit Question Set',
                'verbose_name_plural': 'Audit Question Sets',
                'db_table': 'audit_question_set',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='auditdepartmentassignment',
            name='question_set',
            field=models.ForeignKey(blank=True, help_text='Optional question set; if set, only those questions are used for this audit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='audits.auditquestionset'),
        ),
    ]
