# Generated by Django 5.2.5 on 2026-01-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_attendance_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Regulation Year',
                'verbose_name_plural': 'Regulation Years',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_elective_batch', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to='academics.staffprofile')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='BatchStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_memberships', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Batch Student',
                'verbose_name_plural': 'Batch Students',
            },
        ),
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('period_number', models.PositiveSmallIntegerField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='academics.academicyear')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_timetables', to='academics.batch')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='academics.section')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_timetables', to='academics.staffprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_timetables', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Class Timetable',
                'verbose_name_plural': 'Class Timetables',
            },
        ),
        migrations.CreateModel(
            name='ElectiveOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_offerings', to='academics.academicyear')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_electives', to='academics.staffprofile')),
                ('offering_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_electives', to='academics.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_offerings', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_offerings', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Elective Offering',
                'verbose_name_plural': 'Elective Offerings',
            },
        ),
        migrations.CreateModel(
            name='ElectiveEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_enrollments', to='academics.studentprofile')),
                ('elective_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.electiveoffering')),
            ],
            options={
                'verbose_name': 'Elective Enrollment',
                'verbose_name_plural': 'Elective Enrollments',
            },
        ),
        migrations.CreateModel(
            name='ElectiveOfferingBlockedDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_elective_offerings', to='academics.department')),
                ('elective_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_departments', to='academics.electiveoffering')),
            ],
            options={
                'verbose_name': 'Elective Offering Blocked Department',
                'verbose_name_plural': 'Elective Offering Blocked Departments',
            },
        ),
        migrations.CreateModel(
            name='CurriculumAcademicYearMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_year_mappings', to='academics.academicyear')),
                ('regulation_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_year_mappings', to='academics.regulationyear')),
            ],
            options={
                'verbose_name': 'Curriculum Academic Year Mapping',
                'verbose_name_plural': 'Curriculum Academic Year Mappings',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CORE', 'CORE'), ('PE', 'PE'), ('OE', 'OE'), ('EM', 'EM')], max_length=10)),
                ('classification', models.CharField(choices=[('THEORY', 'THEORY'), ('PRACTICAL', 'PRACTICAL'), ('TCPL', 'TCPL'), ('PMBL', 'PMBL')], max_length=12)),
                ('l', models.PositiveSmallIntegerField(default=0)),
                ('t', models.PositiveSmallIntegerField(default=0)),
                ('p', models.PositiveSmallIntegerField(default=0)),
                ('s', models.PositiveSmallIntegerField(default=0)),
                ('c', models.PositiveSmallIntegerField(default=0)),
                ('cia_marks', models.PositiveSmallIntegerField()),
                ('ese_marks', models.PositiveSmallIntegerField()),
                ('total_marks', models.PositiveSmallIntegerField()),
                ('total_hours', models.PositiveSmallIntegerField()),
                ('exam_pattern', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='academics.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='academics.subject')),
                ('regulation_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='academics.regulationyear')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
            },
        ),
        migrations.CreateModel(
            name='SpecialTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_timetables', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_timetables', to='academics.staffprofile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_timetables', to='academics.section')),
            ],
            options={
                'verbose_name': 'Special Timetable',
                'verbose_name_plural': 'Special Timetables',
            },
        ),
        migrations.CreateModel(
            name='SpecialTimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveSmallIntegerField()),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_timetable_entries', to='academics.batch')),
                ('special_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academics.specialtimetable')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_timetable_entries', to='academics.staffprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_timetable_entries', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Special Timetable Entry',
                'verbose_name_plural': 'Special Timetable Entries',
            },
        ),
        migrations.CreateModel(
            name='TimetableStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.PositiveSmallIntegerField()),
                ('max_periods_per_day', models.PositiveSmallIntegerField()),
                ('period_duration_minutes', models.PositiveSmallIntegerField()),
                ('lunch_after_period', models.PositiveSmallIntegerField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_structures', to='academics.academicyear')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_structures', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Timetable Structure',
                'verbose_name_plural': 'Timetable Structures',
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('is_elective_batch', False), ('section__isnull', True), _connector='OR'), name='batch_elective_section_null'),
        ),
        migrations.AddConstraint(
            model_name='batchstudent',
            constraint=models.UniqueConstraint(fields=('batch', 'student'), name='unique_batch_student'),
        ),
        migrations.AddConstraint(
            model_name='classtimetable',
            constraint=models.UniqueConstraint(fields=('section', 'day_of_week', 'period_number'), name='unique_section_day_period'),
        ),
        migrations.AddConstraint(
            model_name='electiveoffering',
            constraint=models.UniqueConstraint(fields=('subject', 'academic_year', 'semester'), name='unique_elective_subject_year_semester'),
        ),
        migrations.AddConstraint(
            model_name='electiveenrollment',
            constraint=models.UniqueConstraint(fields=('elective_offering', 'student'), name='unique_elective_offering_student'),
        ),
        migrations.AddConstraint(
            model_name='electiveofferingblockeddepartment',
            constraint=models.UniqueConstraint(fields=('elective_offering', 'department'), name='unique_electiveoffering_department_block'),
        ),
        migrations.AddConstraint(
            model_name='curriculumacademicyearmapping',
            constraint=models.UniqueConstraint(fields=('regulation_year', 'academic_year'), name='unique_regulation_academicyear_mapping'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('subject', 'semester', 'regulation_year'), name='unique_curriculum_subject_semester_regulation'),
        ),
        migrations.AddConstraint(
            model_name='specialtimetableentry',
            constraint=models.UniqueConstraint(fields=('special_timetable', 'period_number'), name='unique_specialtimetable_period'),
        ),
        migrations.AddConstraint(
            model_name='timetablestructure',
            constraint=models.UniqueConstraint(fields=('academic_year', 'semester'), name='unique_timetablestructure_year_semester'),
        ),
    ]
