# Generated by Django 5.2.10 on 2026-01-24 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_attendance_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HOD', 'Head of Department'), ('AHOD', 'Assistant HOD')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_roles', to='academics.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_roles', to='academics.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_roles', to='academics.staffprofile')),
            ],
            options={
                'verbose_name': 'Department Role',
                'verbose_name_plural': 'Department Roles',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'HOD')), fields=('department', 'academic_year'), name='unique_active_hod_per_dept_year')],
            },
        ),
        migrations.CreateModel(
            name='SectionAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_advisors', to='academics.academicyear')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_advisories', to='academics.staffprofile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_mappings', to='academics.section')),
            ],
            options={
                'verbose_name': 'Section Advisor',
                'verbose_name_plural': 'Section Advisors',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('section', 'academic_year'), name='unique_active_advisor_per_section_year')],
            },
        ),
        migrations.CreateModel(
            name='StudentMentorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_mentors', to='academics.academicyear')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_mappings', to='academics.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_mappings', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Mentor Mapping',
                'verbose_name_plural': 'Student Mentor Mappings',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'academic_year'), name='unique_active_mentor_per_student_year')],
            },
        ),
    ]
