# Generated by Django 5.2.10 on 2026-01-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_departmentrole_sectionadvisor_studentmentormap'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ALUMNI', 'Alumni'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ALUMNI', 'Alumni'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=16),
        ),
    ]
