# Generated by Django 5.2.10 on 2026-01-25 16:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_staffprofile_status_studentprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='academics.staffprofile')),
            ],
            options={
                'verbose_name': 'Role Assignment',
                'verbose_name_plural': 'Role Assignments',
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('staff', 'role_name'), name='unique_active_role_per_staff')],
            },
        ),
        migrations.CreateModel(
            name='StaffDepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='academics.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='academics.staffprofile')),
            ],
            options={
                'verbose_name': 'Staff Department Assignment',
                'verbose_name_plural': 'Staff Department Assignments',
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('staff',), name='unique_active_dept_per_staff')],
            },
        ),
        migrations.CreateModel(
            name='StudentSectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Section Assignment',
                'verbose_name_plural': 'Student Section Assignments',
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('student',), name='unique_active_section_per_student')],
            },
        ),
    ]
