# Generated by Django 5.2.10 on 2026-02-01 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_roleassignment_staffdepartmentassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='parity',
            field=models.CharField(blank=True, choices=[('ODD', 'Odd'), ('EVEN', 'Even')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.course')),
            ],
            options={
                'unique_together': {('name', 'course')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        # Add nullable batch FK first. A data migration will populate this field
        # (migration 0008_populate_batch_from_semester) and a later migration
        # will make it non-nullable and enforce unique_together.
        migrations.AddField(
            model_name='section',
            name='batch',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.batch'),
        ),
    ]
