# Generated by Django 5.2.10 on 2026-02-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_make_semester_global_and_subject_course'),
    ]

    operations = [
        # Data migration: collapse duplicate Semester rows that share the same
        # `number` into a single canonical Semester. This must run before
        # adding a uniqueness constraint on `number`. Only adjust `Subject`
        # foreign keys; `Section` no longer references `semester`.
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                (lambda Semester, Subject: [
                    (
                        Subject.objects.filter(semester_id=dup.pk).update(semester_id=canon.pk),
                        dup.delete()
                    )
                    for number in set([s.number for s in Semester.objects.all()])
                    for sems in [list(Semester.objects.filter(number=number).order_by('pk'))]
                    for canon in ([sems[0]] if len(sems) > 0 else [])
                    for dup in (sems[1:] if len(sems) > 1 else [])
                ])(
                    apps.get_model('academics', 'Semester'),
                    apps.get_model('academics', 'Subject'),
                )
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.course'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number',)},
        ),
    ]
