# Generated by Django 5.2.10 on 2026-02-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_add_section_academicyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='academic_year',
        ),
    ]
