# Generated by Django 5.2.10 on 2026-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_merge_0016_0017'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentmentormap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='unique_active_mentor_per_student'),
        ),
    ]
