# Generated by Django 5.2.10 on 2026-02-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_backfill_teaching_curriculumrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.semester'),
        ),
    ]
