# Generated by Django 5.2.10 on 2026-02-02 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_alter_dayattendancerecord_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_batches', to='academics.academicyear')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_batches', to='academics.staffprofile')),
                ('students', models.ManyToManyField(related_name='subject_batches', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Subject Batch',
                'verbose_name_plural': 'Student Subject Batches',
            },
        ),
    ]
