# Generated by Django 5.2.10 on 2026-02-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_studentsubjectbatch'),
        ('curriculum', '0005_alter_curriculumdepartment_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectbatch',
            name='curriculum_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_batches', to='curriculum.curriculumdepartment'),
        ),
    ]
