# Generated by Django 5.2.10 on 2026-02-03 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_drop_day_attendance_tables'),
        ('timetable', '0004_remove_timetableassignment_unique_period_day_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.staffprofile')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='timetable.timetableslot')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_attendance_sessions', to='academics.section')),
                ('timetable_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='timetable.timetableassignment')),
            ],
            options={
                'verbose_name': 'Period Attendance Session',
                'verbose_name_plural': 'Period Attendance Sessions',
                'unique_together': {('section', 'period', 'date', 'timetable_assignment')},
            },
        ),
        migrations.CreateModel(
            name='PeriodAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('OD', 'On Duty'), ('LATE', 'Late'), ('LEAVE', 'Leave')], max_length=8)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_attendance_records', to='academics.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academics.periodattendancesession')),
            ],
            options={
                'verbose_name': 'Period Attendance Record',
                'verbose_name_plural': 'Period Attendance Records',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
