# Generated by Django 5.2.11 on 2026-02-07 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_periodattendancesession_periodattendancerecord'),
        ('curriculum', '0007_electivesubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='elective_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments_elective', to='curriculum.electivesubject'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('staff', 'elective_subject', 'section', 'academic_year'), name='unique_staff_elective_section_year'),
        ),
    ]
