# Generated by ChatGPT - add enabled_assessments to TeachingAssignment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_periodattendancesession_periodattendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='enabled_assessments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
