# Generated by Django 6.0.1 on 2026-02-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_teachingassignment_enabled_assessments'),
    ]

    operations = [
        # Previously removed `enabled_assessments` from TeachingAssignment here.
        # Keep the field on TeachingAssignment; do not remove it.
        migrations.AddField(
            model_name='studentmentormap',
            name='enabled_assessments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
