# Generated by Django 5.2.11 on 2026-02-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0031_alter_teachingassignment_section_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
