# Generated by Django 5.2.11 on 2026-02-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_add_analytics_permissions'),
        ('curriculum', '0010_regulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='regulation',
            field=models.ForeignKey(blank=True, help_text='Curriculum regulation this batch follows', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='curriculum.regulation'),
        ),
    ]
