# Generated by Django 6.0.1 on 2026-02-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_special_course_assessment_locking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='specialcourseassessmenteditrequest',
            new_name='academics_s_status_58cf57_idx',
            old_name='academics_s_status_0dfe08_idx',
        ),
    ]
