# Generated by Django 5.2.11 on 2026-02-10 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0034_batch_regulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceUnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_unlock_requests', to='academics.staffprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_unlock_reviews', to='academics.staffprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to='academics.periodattendancesession')),
            ],
            options={
                'verbose_name': 'Attendance Unlock Request',
                'verbose_name_plural': 'Attendance Unlock Requests',
                'ordering': ('-requested_at',),
            },
        ),
    ]
