    # Generated by Django 5.2.11 on 2026-02-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0035_attendanceunlockrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='custom_subject',
            field=models.CharField(blank=True, choices=[('CODE_TANTRA', 'Code Tantra'), ('SPORTS', 'Sports'), ('LIBRARY', 'Library'), ('YOGA', 'Yoga'), ('INTERNSHIP', 'Internship')], max_length=32, null=True),
        ),
    ]
