# Generated by Django 5.2.11 on 2026-02-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0034_rename_academics_s_status_0dfe08_idx_academics_s_status_58cf57_idx'),
        ('academics', '0036_teachingassignment_custom_subject'),
    ]

    operations = [
    ]
