# Generated by Django 6.0.2 on 2026-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0037_merge_20260211_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingassignment',
            name='custom_subject',
            field=models.CharField(blank=True, choices=[('CODE_TANTRA', 'Code Tantra'), ('SPORTS', 'Sports'), ('YOGA', 'Yoga'), ('SPORTS_YOGA', 'SPORTS/YOGA'), ('LIBRARY', 'Library'), ('INTERNSHIP', 'Internship'), ('NPTEL', 'NPTEL'), ('SR', 'SR'), ('HR', 'HR')], max_length=32, null=True),
        ),
    ]
