# Generated by Django 4.2.28 on 2026-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0039_periodattendancesession_teaching_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='mobile_number_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_number_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
