# Generated by Django 4.2.28 on 2026-02-22 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0039_periodattendancesession_teaching_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_sessions', to='academics.staffprofile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance_sessions', to='academics.section')),
            ],
            options={
                'verbose_name': 'Daily Attendance Session',
                'verbose_name_plural': 'Daily Attendance Sessions',
                'ordering': ('-date', 'section__name'),
                'unique_together': {('section', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('OD', 'On Duty'), ('LATE', 'Late')], default='A', max_length=8)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_daily_attendance', to='academics.staffprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academics.dailyattendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_records', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Daily Attendance Record',
                'verbose_name_plural': 'Daily Attendance Records',
                'ordering': ('student__reg_no',),
                'unique_together': {('session', 'student')},
            },
        ),
    ]
