# Generated by Django 4.2.28 on 2026-02-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0040_dailyattendancesession_dailyattendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('OD', 'On Duty'), ('LATE', 'Late'), ('LEAVE', 'Leave')], default='A', max_length=8),
        ),
        migrations.CreateModel(
            name='DailyAttendanceUnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendance_unlock_requests', to='academics.staffprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendance_unlock_reviews', to='academics.staffprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to='academics.dailyattendancesession')),
            ],
            options={
                'verbose_name': 'Daily Attendance Unlock Request',
                'verbose_name_plural': 'Daily Attendance Unlock Requests',
                'ordering': ('-requested_at',),
            },
        ),
    ]
