# Generated by Django 4.2.28 on 2026-02-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0040_staffprofile_mobile_number_and_more'),
        ('academics', '0041_alter_dailyattendancerecord_status_and_more'),
    ]

    operations = []
