# Generated by Django 5.2.5 on 2026-02-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0042_merge_0040_staffprofile_0041_dailyattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ALUMNI', 'Alumni'), ('RESIGNED', 'Resigned'), ('DEBAR', 'Debar')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ALUMNI', 'Alumni'), ('RESIGNED', 'Resigned'), ('DEBAR', 'Debar')], default='ACTIVE', max_length=16),
        ),
    ]
