# Generated by Django 5.2.5 on 2026-02-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0044_update_student_staff_status_choices'),
        ('academics', '0045_add_students_permissions'),
    ]

    operations = [
    ]
