# Generated by Django 5.2.5 on 2026-03-01 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0046_merge_20260227_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendancesession',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member who was assigned to take attendance (via swap)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_daily_sessions', to='academics.staffprofile'),
        ),
    ]
