# Generated by Django 5.2.5 on 2026-03-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0047_dailyattendancesession_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceSwapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, help_text='Optional reason for assignment', max_length=500, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Staff who assigned the attendance (original advisor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_daily_swaps', to='academics.staffprofile')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff who received the attendance assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_daily_swaps', to='academics.staffprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_records', to='academics.dailyattendancesession')),
            ],
            options={
                'verbose_name': 'Daily Attendance Swap Record',
                'verbose_name_plural': 'Daily Attendance Swap Records',
                'ordering': ('-assigned_at',),
            },
        ),
    ]
