# Generated by Django 5.2.5 on 2026-03-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0048_dailyattendanceswaprecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAttendanceUnlockRequest',
        ),
    ]
