# Generated by Django 5.2.5 on 2026-03-01 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0049_remove_dailyattendanceunlockrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceunlockrequest',
            name='final_note',
            field=models.TextField(blank=True, help_text='Final reviewer comments'),
        ),
        migrations.AddField(
            model_name='attendanceunlockrequest',
            name='hod_note',
            field=models.TextField(blank=True, help_text='HOD review comments'),
        ),
        migrations.AddField(
            model_name='attendanceunlockrequest',
            name='hod_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceunlockrequest',
            name='hod_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_hod_reviews', to='academics.staffprofile'),
        ),
        migrations.AddField(
            model_name='attendanceunlockrequest',
            name='hod_status',
            field=models.CharField(choices=[('PENDING', 'Pending HOD Approval'), ('HOD_APPROVED', 'HOD Approved - Pending Final Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='attendanceunlockrequest',
            name='note',
            field=models.TextField(blank=True, help_text='Staff request reason'),
        ),
        migrations.AlterField(
            model_name='attendanceunlockrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_final_reviews', to='academics.staffprofile'),
        ),
        migrations.AlterField(
            model_name='attendanceunlockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending HOD Approval'), ('HOD_APPROVED', 'HOD Approved - Pending Final Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
        migrations.CreateModel(
            name='DailyAttendanceUnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Staff request reason')),
                ('hod_status', models.CharField(choices=[('PENDING', 'Pending HOD Approval'), ('HOD_APPROVED', 'HOD Approved - Pending Final Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hod_note', models.TextField(blank=True, help_text='HOD review comments')),
                ('status', models.CharField(choices=[('PENDING', 'Pending HOD Approval'), ('HOD_APPROVED', 'HOD Approved - Pending Final Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('final_note', models.TextField(blank=True, help_text='Final reviewer comments')),
                ('hod_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_hod_reviews', to='academics.staffprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendance_unlock_requests', to='academics.staffprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_final_reviews', to='academics.staffprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to='academics.dailyattendancesession')),
            ],
            options={
                'verbose_name': 'Daily Attendance Unlock Request',
                'verbose_name_plural': 'Daily Attendance Unlock Requests',
                'ordering': ('-requested_at',),
            },
        ),
    ]
