# Generated by Django 5.2.11 on 2026-03-07 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0051_period_attendance_swap"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubjectbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff who created this batch",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_batches",
                to="academics.staffprofile",
            ),
        ),
    ]
