# Generated by Django 4.2.28 on 2026-03-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0051_period_attendance_swap'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Batch Year',
                'verbose_name_plural': 'Batch Years',
                'ordering': ('-name',),
            },
        ),
    ]
