# Generated by Django 4.2.28 on 2026-03-04 18:07

from django.db import migrations


def seed_batchyear(apps, schema_editor):
    """Populate BatchYear with one deduplicated row per unique Batch.name."""
    Batch = apps.get_model('academics', 'Batch')
    BatchYear = apps.get_model('academics', 'BatchYear')

    seen = set()
    # Order by name so we pick up the first start_year/end_year consistently
    for batch in Batch.objects.order_by('name', 'id'):
        if batch.name in seen:
            continue
        seen.add(batch.name)
        BatchYear.objects.get_or_create(
            name=batch.name,
            defaults={
                'start_year': batch.start_year,
                'end_year': batch.end_year,
            },
        )


def reverse_seed(apps, schema_editor):
    # On reverse just remove all BatchYear rows that came from Batch names
    Batch = apps.get_model('academics', 'Batch')
    BatchYear = apps.get_model('academics', 'BatchYear')
    names = set(Batch.objects.values_list('name', flat=True))
    BatchYear.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0052_add_batchyear_model'),
    ]

    operations = [
        migrations.RunPython(seed_batchyear, reverse_seed),
    ]
