# Generated by Django 5.2.11 on 2026-03-07 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0052_studentsubjectbatch_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchAttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Topic covered in this session",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Session duration in minutes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Lock to prevent further edits"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="academics.studentsubjectbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_batch_attendance_sessions",
                        to="academics.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Attendance Session",
                "verbose_name_plural": "Batch Attendance Sessions",
                "ordering": ("-date", "-created_at"),
                "unique_together": {("batch", "date", "created_at")},
            },
        ),
        migrations.CreateModel(
            name="BatchAttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Present"),
                            ("A", "Absent"),
                            ("OD", "On Duty"),
                            ("LATE", "Late"),
                            ("LEAVE", "Leave"),
                        ],
                        default="P",
                        max_length=8,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now=True)),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_batch_attendance",
                        to="academics.staffprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_attendance_records",
                        to="academics.studentprofile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="academics.batchattendancesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Attendance Record",
                "verbose_name_plural": "Batch Attendance Records",
                "ordering": ("student__reg_no",),
                "unique_together": {("session", "student")},
            },
        ),
    ]
