# Generated by Django 5.2.11 on 2026-03-08 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0053_batchattendancesession_batchattendancerecord"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="batchattendancesession",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="batchattendancesession",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="batchattendancesession",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="studentsubjectbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff who created this batch",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_batches",
                to="academics.staffprofile",
            ),
        ),
        migrations.AlterField(
            model_name="studentsubjectbatch",
            name="staff",
            field=models.ForeignKey(
                help_text="Staff assigned to handle this batch",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_batches",
                to="academics.staffprofile",
            ),
        ),
        migrations.DeleteModel(
            name="BatchAttendanceRecord",
        ),
        migrations.DeleteModel(
            name="BatchAttendanceSession",
        ),
    ]
