# Generated by Django 4.2.28 on 2026-03-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0053_seed_batchyear_from_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_year',
            field=models.ForeignKey(blank=True, help_text='Shared batch year label (source of truth for the name)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='academics.batchyear'),
        ),
    ]
