# Generated by Django 4.2.28 on 2026-03-04 18:13

from django.db import migrations


def backfill(apps, schema_editor):
    """Set batch_year FK on every Batch row by matching on name."""
    Batch = apps.get_model('academics', 'Batch')
    BatchYear = apps.get_model('academics', 'BatchYear')

    # Build a name → BatchYear lookup for efficiency
    by_map = {by.name: by for by in BatchYear.objects.all()}

    for batch in Batch.objects.filter(batch_year__isnull=True):
        by = by_map.get(batch.name)
        if not by:
            # Create missing BatchYear on the fly
            by = BatchYear.objects.create(
                name=batch.name,
                start_year=batch.start_year,
                end_year=batch.end_year,
            )
            by_map[batch.name] = by
        batch.batch_year = by
        batch.save(update_fields=['batch_year'])


def reverse_backfill(apps, schema_editor):
    Batch = apps.get_model('academics', 'Batch')
    Batch.objects.update(batch_year=None)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0054_add_batchyear_fk_to_batch'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse_backfill),
    ]
