# Generated by Django 4.2.28 on 2026-03-05 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0055_backfill_batch_batchyear_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_sh_main',
            field=models.BooleanField(default=False, help_text='True for the S&H department that manages Year-1 sections.'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='For S&H sub-departments, points to the parent S&H department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='academics.department'),
        ),
        migrations.AddField(
            model_name='section',
            name='managing_department',
            field=models.ForeignKey(blank=True, help_text='Override managing department for Year-1 S&H sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sections', to='academics.department'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='home_department',
            field=models.ForeignKey(blank=True, help_text='Permanent degree department (unchanged during Year-1 S&H placement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_students', to='academics.department'),
        ),
    ]
