# Generated by Django 5.2.11 on 2026-03-08 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0055_backfill_created_by_for_batches"),
        ("timetable", "0005_specialtimetable_specialtimetableentry"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="periodattendancesession",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="periodattendancesession",
            name="subject_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Batch for batch-wise attendance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_sessions",
                to="academics.studentsubjectbatch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="periodattendancesession",
            unique_together={
                ("section", "period", "date", "teaching_assignment", "subject_batch")
            },
        ),
    ]
