# Generated by Django 4.2.28 on 2026-03-05 08:23

from django.db import migrations


SH_SUB_DEPTS = [
    {'code': 'SH-MATHS', 'name': 'Maths',     'short_name': 'Maths'},
    {'code': 'SH-ENG',   'name': 'English',   'short_name': 'English'},
    {'code': 'SH-TAM',   'name': 'Tamil',     'short_name': 'Tamil'},
    {'code': 'SH-PHY',   'name': 'Physics',   'short_name': 'Physics'},
    {'code': 'SH-CHEM',  'name': 'Chemistry', 'short_name': 'Chemistry'},
]


def create_sh_sub_depts(apps, schema_editor):
    Department = apps.get_model('academics', 'Department')
    sh = Department.objects.filter(code='S&H').first()
    if sh is None:
        return
    # Mark S&H as the main S&H department
    sh.is_sh_main = True
    sh.save(update_fields=['is_sh_main'])
    for data in SH_SUB_DEPTS:
        Department.objects.get_or_create(
            code=data['code'],
            defaults={
                'name': data['name'],
                'short_name': data['short_name'],
                'parent_id': sh.pk,
            },
        )


def remove_sh_sub_depts(apps, schema_editor):
    Department = apps.get_model('academics', 'Department')
    Department.objects.filter(code__in=[d['code'] for d in SH_SUB_DEPTS]).delete()
    Department.objects.filter(code='S&H').update(is_sh_main=False)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0056_sh_year1_fields'),
    ]

    operations = [
        migrations.RunPython(create_sh_sub_depts, remove_sh_sub_depts),
    ]
