# Generated by Django 4.2.28 on 2026-03-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0057_sh_subdept_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Set this when there is no Course (e.g. S&H Year-1 batches).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_batches', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Required for regular degree batches. Leave blank for S&H / dept-only batches.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.course'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('name', 'course'), name='unique_batch_name_course'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True)), fields=('name', 'department'), name='unique_batch_name_department'),
        ),
    ]
