# Generated by Django 4.2.28 on 2026-03-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0058_batch_course_nullable_dept_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
