# Generated by Django 5.2.11 on 2026-03-11 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0059_merge_20260309_0937"),
        ("timetable", "0006_periodswaprequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceAssignmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Attendance"),
                            ("PERIOD", "Period Attendance"),
                        ],
                        default="DAILY",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "daily_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_requests",
                        to="academics.dailyattendancesession",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="For period attendance only",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.timetableslot",
                    ),
                ),
                (
                    "period_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_requests",
                        to="academics.periodattendancesession",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Staff requesting to assign attendance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_attendance_requests",
                        to="academics.staffprofile",
                    ),
                ),
                (
                    "requested_to",
                    models.ForeignKey(
                        help_text="Staff being requested to take attendance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_attendance_requests",
                        to="academics.staffprofile",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_assignment_requests",
                        to="academics.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Assignment Request",
                "verbose_name_plural": "Attendance Assignment Requests",
                "ordering": ("-created_at",),
            },
        ),
    ]
