# Generated by Django 4.2.28 on 2026-03-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0059_staffprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
