# Generated by Django 5.2.5 on 2026-03-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_merge_20260310_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchyear',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this batch year is currently active'),
        ),
    ]
