# Generated by Django 4.2.28 on 2026-03-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_merge_20260310_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Course Enrollment',
                'verbose_name_plural': 'Student Course Enrollments',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
