# Generated by Django 5.2.5 on 2026-03-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0062_add_is_active_to_batchyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchyear',
            name='is_active',
        ),
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this batch is currently active for this department'),
        ),
    ]
