# Generated by Django 4.2.28 on 2026-03-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0060_attendanceassignmentrequest'),
        ('academics', '0063_move_is_active_from_batchyear_to_batch'),
    ]

    operations = [
    ]
