# Generated by Django 4.2.28 on 2026-03-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_studentprofile_profile_image'),
        ('academics', '0064_merge_20260312_1541'),
    ]

    operations = [
    ]
