# Generated by Django 4.2.28 on 2026-03-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0064_merge_20260311_1455'),
        ('academics', '0065_merge_20260312_1546'),
    ]

    operations = [
    ]
