# Generated by Django 4.2.28 on 2026-03-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0066_merge_20260312_1549'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentsectionassignment',
            name='unique_active_section_per_student',
        ),
        migrations.AddField(
            model_name='studentsectionassignment',
            name='section_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary (Dept-Core)')], default='PRIMARY', help_text='PRIMARY = main section; SECONDARY = core-dept section for Year-1 dept-core subjects.', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='studentsectionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('student', 'section_type'), name='unique_active_section_per_student_type'),
        ),
    ]
