# Generated by Django 4.2.28 on 2026-03-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0062_staffprofile_rfid_uid'),
        ('academics', '0067_studentsectionassignment_section_type'),
    ]

    operations = [
    ]
