# Generated by Django 4.2.28 on 2026-04-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0068_merge_20260313_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='login_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Random 6-digit code for external staff login.', max_length=6),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ALUMNI', 'Alumni'), ('RESIGNED', 'Resigned'), ('EXTERNAL', 'External')], default='ACTIVE', max_length=16),
        ),
    ]
