# Generated by GitHub Copilot on 2026-03-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0069_dailyattendanceunlockrequest_bulk_group_id'),
        ('academics', '0071_studentsubjectbatch_section'),
    ]

    operations = [
    ]
