# Generated by Django 4.2.28 on 2026-04-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0074_ext_staff_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='extstaffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Department working in', max_length=255),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='faculty_id',
            field=models.CharField(blank=True, default='', help_text='Faculty ID', max_length=64),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='gender',
            field=models.CharField(blank=True, default='', help_text='Gender', max_length=20),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='mobile',
            field=models.CharField(blank=True, default='', help_text='Mobile number', max_length=20),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='phd_status',
            field=models.CharField(blank=True, default='', help_text='PhD Status', max_length=64),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='qualification',
            field=models.CharField(blank=True, default='', help_text='Qualification', max_length=255),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='teaching',
            field=models.CharField(blank=True, default='', help_text='Teaching role, e.g., Teaching Faculty', max_length=128),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='total_experience',
            field=models.CharField(blank=True, default='', help_text='Total experience', max_length=64),
        ),
    ]
