# Generated by Django 4.2.28 on 2026-04-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0075_add_ext_staff_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='extstaffprofile',
            name='salutation',
            field=models.CharField(blank=True, default='', help_text='Salutation, e.g., Dr., Mr., Ms.', max_length=20),
        ),
    ]
