# Generated by Django 4.2.28 on 2026-04-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0076_add_ext_staff_salutation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extstaffprofile',
            name='qualification',
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', help_text='Account holder name', max_length=255),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='account_number',
            field=models.CharField(blank=True, default='', help_text='Bank account number', max_length=64),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='bank_branch_name',
            field=models.CharField(blank=True, default='', help_text='Bank branch name (full form)', max_length=255),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Name of the bank', max_length=255),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='engg_college_experience',
            field=models.CharField(blank=True, default='', help_text='Experience at Engineering College only, in years', max_length=64),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', help_text='IFSC code', max_length=20),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='passbook_proof',
            field=models.FileField(blank=True, help_text='Scanned copy of passbook front page', null=True, upload_to='ext_staff_passbook/'),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='pg_specialization',
            field=models.CharField(blank=True, default='', help_text='PG with Specialization, e.g., M.E/M.Tech - Structural Engineering', max_length=255),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='ug_specialization',
            field=models.CharField(blank=True, default='', help_text='UG with Specialization, e.g., B.E/B.Tech - Mechanical Engineering', max_length=255),
        ),
    ]
