# Generated by Django 4.2.28 on 2026-04-02 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0077_ext_staff_new_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtStaffFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(db_index=True, help_text='Unique code for the registration form URL.', max_length=32, unique=True)),
                ('form_title', models.CharField(default='External Staff Registration', help_text='Form title displayed to users', max_length=255)),
                ('form_description', models.TextField(blank=True, default='', help_text='Form description/instructions')),
                ('is_accepting_responses', models.BooleanField(default=False, help_text='Whether the form is currently accepting responses')),
                ('field_config', models.JSONField(default=list, help_text='Configuration for form fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ext_staff_form_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ext_staff_form_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Staff Form Settings',
                'verbose_name_plural': 'External Staff Form Settings',
            },
        ),
    ]
