# Generated by Django 4.2.28 on 2026-04-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0079_change_ext_uid_to_6_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='extstaffprofile',
            name='college_name',
            field=models.CharField(blank=True, default='', help_text='College name where staff is working', max_length=255),
        ),
    ]
