# Generated by Django 4.2.28 on 2026-04-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0080_add_college_name_to_ext_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extstaffprofile',
            name='organisation',
        ),
    ]
