# Generated by Django 4.2.28 on 2026-04-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0069_staffprofile_login_code_alter_staffprofile_status'),
        ('academics', '0082_staffprofile_internal_id'),
    ]

    operations = [
    ]
