# Generated by Django 4.2.28 on 2026-04-06 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0083_merge_20260405_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='internal_id',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='login_code',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(db_index=True, help_text='Exactly 6 numeric digits (e.g. 100001).', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_staff_id', message='Staff ID must be exactly 6 numeric digits.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ALUMNI', 'Alumni'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=16),
        ),
    ]
