# Generated by Django 4.2.28 on 2026-04-26 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0083_merge_20260424_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='internal_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Internal ID must be numeric digits.', regex='^\\d+$')]),
        ),
    ]
