# Generated by Django 4.2.28 on 2026-07-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('academics', '0083_merge_20260715_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='college',
            field=models.ForeignKey(blank=True, help_text='College this staff member belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='college.college'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.ForeignKey(blank=True, help_text='College this student belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='college.college'),
        ),
    ]
