# Generated by Django 4.2.28 on 2026-05-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0084_alter_staffprofile_internal_id'),
        ('academics', '0085_add_internal_external_ids'),
    ]

    operations = [
    ]
