# Generated by Django 4.2.28 on 2026-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0086_merge_20260530_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(db_index=True, help_text='Staff ID (format not restricted).', max_length=64, unique=True),
        ),
    ]
