# Generated by Django 4.2.28 on 2026-08-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0087_alter_staffprofile_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the mixed section (e.g., Lab Group A, Project Batch 1)', max_length=128)),
                ('description', models.TextField(blank=True, help_text='Additional details about this mixed section')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mixed section is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, help_text='Academic year this mixed section is active in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mixed_sections', to='academics.academicyear')),
                ('batch', models.ForeignKey(help_text='The batch this mixed section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mixed_sections', to='academics.batch')),
                ('sections', models.ManyToManyField(help_text='Regular sections that are part of this mixed section', related_name='mixed_sections', to='academics.section')),
            ],
            options={
                'verbose_name': 'Mixed Section',
                'verbose_name_plural': 'Mixed Sections',
                'ordering': ('batch', 'name'),
                'unique_together': {('name', 'batch')},
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mixed_section',
            field=models.ForeignKey(blank=True, help_text='Optional mixed section assignment for cross-section activities', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.mixedsection'),
        ),
    ]
