# Generated by Django 4.2.28 on 2026-08-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0088_mixedsection_studentprofile_mixed_section'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectionadvisor',
            name='unique_active_advisor_per_section_year',
        ),
        migrations.AddField(
            model_name='sectionadvisor',
            name='mixed_section',
            field=models.ForeignKey(blank=True, help_text='Mixed section assigned to this advisor. Either section or mixed_section must be selected, not both.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_mappings', to='academics.mixedsection'),
        ),
        migrations.AlterField(
            model_name='sectionadvisor',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Regular section assigned to this advisor. Either section or mixed_section must be selected, not both.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_mappings', to='academics.section'),
        ),
        migrations.AddConstraint(
            model_name='sectionadvisor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('section__isnull', False)), fields=('section', 'academic_year'), name='unique_active_advisor_per_section_year'),
        ),
        migrations.AddConstraint(
            model_name='sectionadvisor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('mixed_section__isnull', False)), fields=('mixed_section', 'academic_year'), name='unique_active_advisor_per_mixed_section_year'),
        ),
    ]
