# Generated by Django 4.2.28 on 2026-08-14 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0089_remove_sectionadvisor_unique_active_advisor_per_section_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixedsection',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester this mixed section belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixed_sections', to='academics.semester'),
        ),
    ]
