# Generated by Django 4.2.28 on 2026-08-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0090_mixedsection_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='pbas_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pbas_credit',
            field=models.IntegerField(default=0),
        ),
    ]
