# Generated by Django 4.2.28 on 2026-08-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0090_systemtransitionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Permanent residential address.', max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, default='', help_text="Father's full name.", max_length=128),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_phone',
            field=models.CharField(blank=True, default='', help_text="Father's phone number.", max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, default='', help_text="Mother's full name.", max_length=128),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_phone',
            field=models.CharField(blank=True, default='', help_text="Mother's phone number.", max_length=20),
        ),
    ]
