# Generated by Django 4.2.28 on 2026-08-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0084_staffprofile_college_studentprofile_college'),
        ('academics', '0091_student_parent_details'),
    ]

    operations = [
    ]
