# Generated by Django 4.2.28 on 2026-08-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0091_student_parent_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_phone',
        ),
    ]
