# Generated by Django 4.2.28 on 2026-08-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0092_merge_20260806_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_phone',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='internal_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated 6-digit numeric unique ID.', max_length=6, null=True, unique=True),
        ),
    ]
