# Generated by Django 4.2.28 on 2026-08-09 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0092_remove_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchyear',
            name='graduated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this batch was marked as graduated.', null=True),
        ),
        migrations.AddField(
            model_name='batchyear',
            name='graduated_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this batch as graduated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduated_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchyear',
            name='is_graduated',
            field=models.BooleanField(db_index=True, default=False, help_text='True when all students in this batch have completed their programme. Graduated batches are excluded from semester shifts and advisor assignment.'),
        ),
    ]
