# Generated by Django 4.2.28 on 2026-08-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0090_mixedsection_semester'),
        ('academics', '0092_remove_studentprofile_address_and_more'),
    ]

    operations = [
    ]
