# Generated by GitHub Copilot for college-scoped academic data

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0093_remove_studentprofile_address_and_more'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='departments',
                blank=True,
                null=True,
                to='college.college',
                help_text='College associated with this department for college-scoped management.',
            ),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=16),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('college', 'code'), name='academics_department_college_code_uniq'),
        ),
        migrations.AddField(
            model_name='batch',
            name='college',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='batches',
                blank=True,
                null=True,
                to='college.college',
                help_text='College associated with this batch for college-scoped management.',
            ),
        ),
    ]
