# Generated by Django 4.2.28 on 2026-08-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0091_staffprofile_pbas_credit_studentprofile_pbas_credit'),
        ('academics', '0093_merge_20260817_1438'),
    ]

    operations = [
    ]
