# Generated by Django 4.2.28 on 2026-08-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('academics', '0094_add_college_to_department_and_batch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='academics_department_college_code_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('college', 'code')},
        ),
    ]
