# Generated by Django 4.2.28 on 2026-08-24 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0094_merge_20260819_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemtransitionlog',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='systemtransitionlog',
            name='performed_by',
        ),
        migrations.RemoveConstraint(
            model_name='sectionadvisor',
            name='unique_active_advisor_per_section_year',
        ),
        migrations.RemoveConstraint(
            model_name='sectionadvisor',
            name='unique_active_advisor_per_mixed_section_year',
        ),
        migrations.RenameField(
            model_name='extstaffprofile',
            old_name='external_id',
            new_name='ext_uid',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='date_of_join',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='pbas_credit',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='pbas_credit',
        ),
        migrations.RemoveField(
            model_name='studentsubjectbatch',
            name='elective_subject',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='login_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Random 6-digit code for external staff login.', max_length=6),
        ),
        migrations.AlterField(
            model_name='mixedsection',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester for this mixed section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixed_sections', to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='sectionadvisor',
            name='mixed_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_mappings', to='academics.mixedsection'),
        ),
        migrations.AlterField(
            model_name='sectionadvisor',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_mappings', to='academics.section'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='internal_id',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Internal ID must be exactly 6 digits (numeric only).', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ALUMNI', 'Alumni'), ('RESIGNED', 'Resigned'), ('EXTERNAL', 'External')], default='ACTIVE', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='sectionadvisor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('section', 'academic_year'), name='unique_active_advisor_per_section_year'),
        ),
        migrations.DeleteModel(
            name='SystemTransitionLog',
        ),
    ]
