# Generated by Django 4.2.28 on 2026-08-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0095_remove_systemtransitionlog_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectionadvisor',
            name='unique_active_advisor_per_section_year',
        ),
        migrations.RenameField(
            model_name='extstaffprofile',
            old_name='ext_uid',
            new_name='external_id',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='login_code',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pbas_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pbas_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mixedsection',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester this mixed section belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixed_sections', to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='sectionadvisor',
            name='mixed_section',
            field=models.ForeignKey(blank=True, help_text='Mixed section assigned to this advisor. Either section or mixed_section must be selected, not both.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_mappings', to='academics.mixedsection'),
        ),
        migrations.AlterField(
            model_name='sectionadvisor',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Regular section assigned to this advisor. Either section or mixed_section must be selected, not both.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_mappings', to='academics.section'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='internal_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated 6-digit numeric unique ID.', max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(db_index=True, help_text='Staff ID (format not restricted).', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ALUMNI', 'Alumni'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='sectionadvisor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('section__isnull', False)), fields=('section', 'academic_year'), name='unique_active_advisor_per_section_year'),
        ),
        migrations.AddConstraint(
            model_name='sectionadvisor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('mixed_section__isnull', False)), fields=('mixed_section', 'academic_year'), name='unique_active_advisor_per_mixed_section_year'),
        ),
    ]
