# Generated by Django 4.2.28 on 2026-08-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('academics', '0095_remove_department_academics_department_college_code_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academicyears', to='college.college'),
        ),
        migrations.AddField(
            model_name='attendanceassignmentrequest',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendanceassignmentrequests', to='college.college'),
        ),
        migrations.AddField(
            model_name='attendanceunlockrequest',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendanceunlockrequests', to='college.college'),
        ),
        migrations.AddField(
            model_name='batchyear',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batchyears', to='college.college'),
        ),
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='college.college'),
        ),
        migrations.AddField(
            model_name='dailyattendancerecord',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyattendancerecords', to='college.college'),
        ),
        migrations.AddField(
            model_name='dailyattendancesession',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyattendancesessions', to='college.college'),
        ),
        migrations.AddField(
            model_name='dailyattendanceswaprecord',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyattendanceswaprecords', to='college.college'),
        ),
        migrations.AddField(
            model_name='dailyattendanceunlockrequest',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyattendanceunlockrequests', to='college.college'),
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmentroles', to='college.college'),
        ),
        migrations.AddField(
            model_name='extstaffformsettings',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extstaffformsettings', to='college.college'),
        ),
        migrations.AddField(
            model_name='extstaffprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extstaffprofiles', to='college.college'),
        ),
        migrations.AddField(
            model_name='periodattendancerecord',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodattendancerecords', to='college.college'),
        ),
        migrations.AddField(
            model_name='periodattendancesession',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodattendancesessions', to='college.college'),
        ),
        migrations.AddField(
            model_name='periodattendanceswaprecord',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodattendanceswaprecords', to='college.college'),
        ),
        migrations.AddField(
            model_name='program',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='college.college'),
        ),
        migrations.AddField(
            model_name='rfreadergate',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfreadergates', to='college.college'),
        ),
        migrations.AddField(
            model_name='rfreaderscan',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfreaderscans', to='college.college'),
        ),
        migrations.AddField(
            model_name='rfreaderstudent',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfreaderstudents', to='college.college'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roleassignments', to='college.college'),
        ),
        migrations.AddField(
            model_name='section',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='college.college'),
        ),
        migrations.AddField(
            model_name='sectionadvisor',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionadvisors', to='college.college'),
        ),
        migrations.AddField(
            model_name='semester',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='college.college'),
        ),
        migrations.AddField(
            model_name='specialcourseassessmenteditrequest',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialcourseassessmenteditrequests', to='college.college'),
        ),
        migrations.AddField(
            model_name='specialcourseassessmentselection',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialcourseassessmentselections', to='college.college'),
        ),
        migrations.AddField(
            model_name='staffdepartmentassignment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffdepartmentassignments', to='college.college'),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentcourseenrollments', to='college.college'),
        ),
        migrations.AddField(
            model_name='studentmentormap',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentmentormaps', to='college.college'),
        ),
        migrations.AddField(
            model_name='studentsectionassignment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentsectionassignments', to='college.college'),
        ),
        migrations.AddField(
            model_name='studentsubjectbatch',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentsubjectbatchs', to='college.college'),
        ),
        migrations.AddField(
            model_name='subject',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='college.college'),
        ),
        migrations.AddField(
            model_name='systemtransitionlog',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systemtransitionlogs', to='college.college'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachingassignments', to='college.college'),
        ),
    ]
