# Generated by Django 4.2.28 on 2026-08-11 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0096_academicyear_college_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batch',
            name='unique_batch_name_department',
        ),
        migrations.AddField(
            model_name='batch',
            name='is_graduated',
            field=models.BooleanField(default=False, help_text='True if this batch has graduated'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Optional. Course associated with this batch.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional. Department associated with this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_batches', to='academics.department'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True), ('department__isnull', False)), fields=('name', 'department'), name='unique_batch_name_department'),
        ),
    ]
