# Generated by Django 4.2.28 on 2026-09-15 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0097_staffprofile_pbas_category_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('details', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='academics.academicyear')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Transition Log',
                'verbose_name_plural': 'System Transition Logs',
                'ordering': ('-performed_at',),
            },
        ),
    ]
