# Generated by Django 4.2.28 on 2026-08-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0097_remove_batch_unique_batch_name_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchyear',
            name='is_graduated',
            field=models.BooleanField(default=False, help_text='True if this common batch year has graduated'),
        ),
    ]
