# Generated by Django 4.2.28 on 2026-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('academics', '0098_batchyear_is_graduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('college', 'name', 'department', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('college', 'name')},
        ),
    ]
