# Generated by Django 4.2.28 on 2026-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0099_alter_program_name_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batch',
            name='unique_batch_name_course',
        ),
        migrations.RemoveConstraint(
            model_name='batch',
            name='unique_batch_name_department',
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('name', 'course', 'college'), name='unique_batch_name_course_college'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True), ('department__isnull', False)), fields=('name', 'department', 'college'), name='unique_batch_name_department_college'),
        ),
    ]
