# Generated by Django 4.2.28 on 2026-08-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('academics', '0100_fix_batch_uniqueness_college_scoped'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('college', 'name', 'parity')},
        ),
    ]
