# Generated by Django 5.2.10 on 2026-02-01 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0022_section_semester'),
        ('curriculum', '0005_alter_curriculumdepartment_semester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timetable Template',
                'verbose_name_plural': 'Timetable Templates',
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('index', models.PositiveSmallIntegerField(default=1)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_break', models.BooleanField(default=False)),
                ('is_lunch', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=64, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timetabletemplate')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'ordering': ('template', 'day', 'index'),
            },
        ),
        migrations.CreateModel(
            name='TimetableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_text', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_assignments', to='academics.academicyear')),
                ('curriculum_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_assignments', to='curriculum.curriculumdepartment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_assignments', to='academics.section')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_assignments', to='academics.staffprofile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timetable.timetableslot')),
            ],
            options={
                'verbose_name': 'Timetable Assignment',
                'verbose_name_plural': 'Timetable Assignments',
                'constraints': [models.UniqueConstraint(fields=('slot', 'section', 'academic_year'), name='unique_slot_section_year')],
            },
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('template', 'day', 'index'), name='unique_slot_per_template_day_index'),
        ),
    ]
