# Generated by Django 5.2.10 on 2026-02-01 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_section_semester'),
        ('curriculum', '0005_alter_curriculumdepartment_semester_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableslot',
            options={'ordering': ('template', 'index'), 'verbose_name': 'Period Definition', 'verbose_name_plural': 'Period Definitions'},
        ),
        migrations.RemoveConstraint(
            model_name='timetableassignment',
            name='unique_slot_section_year',
        ),
        migrations.RemoveConstraint(
            model_name='timetableslot',
            name='unique_slot_per_template_day_index',
        ),
        migrations.RenameField(
            model_name='timetableassignment',
            old_name='slot',
            new_name='period',
        ),
        migrations.RemoveField(
            model_name='timetableassignment',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='day',
        ),
        migrations.AddField(
            model_name='timetableassignment',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetabletemplate',
            name='parity',
            field=models.CharField(choices=[('BOTH', 'Both'), ('ODD', 'Odd'), ('EVEN', 'Even')], default='BOTH', max_length=4),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='timetable.timetabletemplate'),
        ),
        migrations.AddConstraint(
            model_name='timetableassignment',
            constraint=models.UniqueConstraint(fields=('period', 'day', 'section'), name='unique_period_day_section'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('template', 'index'), name='unique_period_per_template_index'),
        ),
    ]
