# Generated by Django 5.2.10 on 2026-02-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_timetableslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetabletemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
