# Generated by Django 5.2.10 on 2026-02-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_studentsubjectbatch_curriculum_row'),
        ('curriculum', '0005_alter_curriculumdepartment_semester_and_more'),
        ('timetable', '0003_timetabletemplate_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetableassignment',
            name='unique_period_day_section',
        ),
        migrations.AddField(
            model_name='timetableassignment',
            name='subject_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_assignments', to='academics.studentsubjectbatch'),
        ),
        migrations.AddConstraint(
            model_name='timetableassignment',
            constraint=models.UniqueConstraint(fields=('period', 'day', 'section', 'subject_batch'), name='unique_period_day_section_batch'),
        ),
    ]
