# Generated by Django 5.2.11 on 2026-02-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0031_alter_teachingassignment_section_nullable'),
        ('curriculum', '0009_alter_electivechoice_id'),
        ('timetable', '0004_remove_timetableassignment_unique_period_day_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.staffprofile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_timetables', to='academics.section')),
            ],
            options={
                'verbose_name': 'Special Timetable',
                'verbose_name_plural': 'Special Timetables',
                'permissions': (('manage_special_timetable', 'Can manage special timetable'),),
            },
        ),
        migrations.CreateModel(
            name='SpecialTimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject_text', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.curriculumdepartment')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_entries', to='timetable.timetableslot')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.staffprofile')),
                ('subject_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.studentsubjectbatch')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.specialtimetable')),
            ],
            options={
                'verbose_name': 'Special Timetable Entry',
                'verbose_name_plural': 'Special Timetable Entries',
                'constraints': [models.UniqueConstraint(fields=('timetable', 'date', 'period'), name='unique_special_entry_per_timetable_date_period')],
            },
        ),
    ]
