# Generated by Django 4.2.28 on 2026-06-01 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0028_dynamic_class_type_validation'),
        ('academics', '0087_alter_staffprofile_staff_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0006_periodswaprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('GENERATED', 'Generated'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], default='GENERATING', max_length=20)),
                ('generation_algorithm', models.CharField(default='CONSTRAINT_SOLVER', help_text='Algorithm used for generation', max_length=64)),
                ('error_message', models.TextField(blank=True, help_text='Error details if generation failed')),
                ('total_assignments', models.PositiveIntegerField(default=0)),
                ('constraint_violations', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_timetables', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_timetables', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='generated_timetables', to='academics.department')),
                ('sections', models.ManyToManyField(blank=True, related_name='generated_timetables', to='academics.section')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_timetables', to='timetable.timetabletemplate')),
            ],
            options={
                'verbose_name': 'Generated Timetable',
                'verbose_name_plural': 'Generated Timetables',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness_score', models.DecimalField(decimal_places=2, default=5.0, help_text='Score 0-10: Higher is better, used for ranking teachers for same subject', max_digits=5)),
                ('ranking', models.PositiveSmallIntegerField(default=1, help_text='Ranking among teachers for this subject (1=preferred)')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0, help_text='Years teaching this specific subject')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary teacher for this subject (preferred for assignment)')),
                ('can_teach_lab', models.BooleanField(default=True)),
                ('can_teach_theory', models.BooleanField(default=True)),
                ('can_teach_tutorial', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_mappings', to='academics.academicyear')),
                ('curriculum_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_mappings', to='curriculum.curriculumdepartment')),
                ('section', models.ForeignKey(blank=True, help_text='Leave blank for department-wide mapping', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_mappings', to='academics.section')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='academics.staffprofile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_mappings', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Teacher Subject Mapping',
                'verbose_name_plural': 'Teacher Subject Mappings',
                'ordering': ['ranking', '-effectiveness_score'],
            },
        ),
        migrations.CreateModel(
            name='TeacherConstraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weekly_hours', models.PositiveSmallIntegerField(default=24, help_text='Maximum hours per week this teacher can handle')),
                ('max_consecutive_periods', models.PositiveSmallIntegerField(default=3, help_text='Maximum consecutive periods without a break')),
                ('available_days', models.JSONField(blank=True, default=list, help_text='Days available (1-7: Mon-Sun). Empty means all days available.')),
                ('unavailable_periods', models.JSONField(blank=True, default=list, help_text='Period IDs when teacher is unavailable')),
                ('prefers_morning', models.BooleanField(default=False)),
                ('prefers_afternoon', models.BooleanField(default=False)),
                ('prefers_no_first_hour', models.BooleanField(default=False)),
                ('prefers_no_last_hour', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_constraints', to='academics.staffprofile')),
            ],
            options={
                'verbose_name': 'Teacher Constraint',
                'verbose_name_plural': 'Teacher Constraints',
            },
        ),
        migrations.CreateModel(
            name='SubjectRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_hours', models.PositiveSmallIntegerField(default=0)),
                ('lab_hours', models.PositiveSmallIntegerField(default=0)),
                ('tutorial_hours', models.PositiveSmallIntegerField(default=0)),
                ('practical_hours', models.PositiveSmallIntegerField(default=0)),
                ('requires_consecutive_slots', models.BooleanField(default=False, help_text='Lab/practical must be in consecutive periods')),
                ('consecutive_slot_count', models.PositiveSmallIntegerField(default=2, help_text='Number of consecutive periods needed for labs')),
                ('lab_slot_duration_minutes', models.PositiveSmallIntegerField(default=60, help_text='Duration of each lab period in minutes')),
                ('cannot_be_first_period', models.BooleanField(default=False)),
                ('cannot_be_last_period', models.BooleanField(default=False)),
                ('preferred_days', models.JSONField(blank=True, default=list, help_text='Preferred days (1-7: Mon-Sun). Empty means any day.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_row', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_requirements', to='curriculum.curriculumdepartment')),
                ('subject', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_requirements', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Requirement',
                'verbose_name_plural': 'Subject Requirements',
            },
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='timetable.generatedtimetable')),
            ],
            options={
                'verbose_name': 'Generation Log',
                'verbose_name_plural': 'Generation Logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='teachersubjectmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('curriculum_row__isnull', False)), fields=('staff', 'curriculum_row', 'section', 'academic_year'), name='unique_staff_curriculum_section_year_mapping'),
        ),
        migrations.AddConstraint(
            model_name='teachersubjectmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('curriculum_row__isnull', True), ('subject__isnull', False)), fields=('staff', 'subject', 'section', 'academic_year'), name='unique_staff_subject_section_year_mapping'),
        ),
    ]
