# Generated by Django 4.2.28 on 2026-06-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_generatedtimetable_teachersubjectmapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationlog',
            name='generated_timetable',
        ),
        migrations.RemoveField(
            model_name='subjectrequirements',
            name='curriculum_row',
        ),
        migrations.RemoveField(
            model_name='subjectrequirements',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacherconstraints',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='teachersubjectmapping',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='teachersubjectmapping',
            name='curriculum_row',
        ),
        migrations.RemoveField(
            model_name='teachersubjectmapping',
            name='section',
        ),
        migrations.RemoveField(
            model_name='teachersubjectmapping',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='teachersubjectmapping',
            name='subject',
        ),
        migrations.DeleteModel(
            name='GeneratedTimetable',
        ),
        migrations.DeleteModel(
            name='GenerationLog',
        ),
        migrations.DeleteModel(
            name='SubjectRequirements',
        ),
        migrations.DeleteModel(
            name='TeacherConstraints',
        ),
        migrations.DeleteModel(
            name='TeacherSubjectMapping',
        ),
    ]
