# Generated by Django 4.2.28 on 2026-08-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_remove_generationlog_generated_timetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('venue_type', models.CharField(choices=[('LAB', 'Laboratory'), ('THEORY', 'Theory Hall'), ('SEMINAR', 'Seminar Hall'), ('COMPUTER', 'Computer Lab'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('capacity', models.PositiveSmallIntegerField(default=0, help_text='Optional max student capacity (0 = unlimited)')),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_venue_name'),
        ),
        migrations.AddField(
            model_name='timetableassignment',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_assignments', to='timetable.venue'),
        ),
    ]
