# Generated by Django 4.2.28 on 2026-08-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_venue_venue_unique_venue_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableassignment',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
