# Generated by Django 4.2.28 on 2026-08-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('timetable', '0009_harden_college_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodswaprequest',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodswaprequests', to='college.college'),
        ),
        migrations.AlterField(
            model_name='specialtimetable',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialtimetables', to='college.college'),
        ),
        migrations.AlterField(
            model_name='specialtimetableentry',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialtimetableentrys', to='college.college'),
        ),
        migrations.AlterField(
            model_name='timetableassignment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetableassignments', to='college.college'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetableslots', to='college.college'),
        ),
        migrations.AlterField(
            model_name='timetabletemplate',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetabletemplates', to='college.college'),
        ),
    ]
