# Generated by Django 4.2.28 on 2026-09-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_remove_timetableassignment_venue_delete_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableConfigRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(max_length=32)),
                ('day', models.CharField(max_length=32)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_rows', to='timetable.timetabletemplate')),
            ],
            options={
                'verbose_name': 'Timetable Config Row',
                'verbose_name_plural': 'Timetable Config Rows',
            },
        ),
        migrations.CreateModel(
            name='TimetableConfigColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('period', models.CharField(blank=True, max_length=32, null=True)),
                ('timing', models.CharField(blank=True, max_length=64, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_columns', to='timetable.timetabletemplate')),
            ],
            options={
                'verbose_name': 'Timetable Config Column',
                'verbose_name_plural': 'Timetable Config Columns',
            },
        ),
    ]
