# Generated by Django 4.2.28 on 2026-09-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_timetableconfigrow_timetableconfigcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTypeException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=64, unique=True)),
                ('individual_periods', models.IntegerField(default=1)),
                ('paired_periods', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Class Type Exception',
                'verbose_name_plural': 'Class Type Exceptions',
            },
        ),
        migrations.CreateModel(
            name='CreditAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_value', models.IntegerField(unique=True)),
                ('periods', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Credit Allocation',
                'verbose_name_plural': 'Credit Allocations',
            },
        ),
        migrations.CreateModel(
            name='GroupAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(help_text='Frontend generated ID', max_length=64, unique=True)),
                ('group_name', models.CharField(max_length=128)),
                ('selected_years', models.JSONField(blank=True, default=list)),
                ('selected_departments', models.JSONField(blank=True, default=list)),
                ('selected_section_keys', models.JSONField(blank=True, default=list)),
                ('selected_mixed_section_keys', models.JSONField(blank=True, default=list)),
                ('exception_courses', models.JSONField(blank=True, default=list)),
                ('individual_periods', models.IntegerField(default=1)),
                ('paired_periods', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group Allocation',
                'verbose_name_plural': 'Group Allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueExceptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(help_text='Frontend generated ID', max_length=64, unique=True)),
                ('venue_name', models.CharField(max_length=256)),
                ('group_ids', models.JSONField(blank=True, default=list, help_text='Array of GroupAllocation frontend_ids')),
                ('capacity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Venue Exception Rule',
                'verbose_name_plural': 'Venue Exception Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
