# Generated by Django 4.2.28 on 2026-09-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_classtypeexception_creditallocation_groupallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExceptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(help_text='Frontend generated ID', max_length=64, unique=True)),
                ('course_code', models.CharField(max_length=128)),
                ('course_name', models.CharField(blank=True, default='', max_length=256)),
                ('individual_periods', models.IntegerField(default=1)),
                ('paired_periods', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Exception Rule',
                'verbose_name_plural': 'Course Exception Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
