# Generated by Django 4.2.28 on 2026-09-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_courseexceptionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexceptionrule',
            name='selected_departments',
            field=models.JSONField(blank=True, default=list, help_text='List of department codes'),
        ),
        migrations.AddField(
            model_name='courseexceptionrule',
            name='selected_section_keys',
            field=models.JSONField(blank=True, default=list, help_text='List of section keys/ids'),
        ),
        migrations.AddField(
            model_name='courseexceptionrule',
            name='semester',
            field=models.IntegerField(blank=True, help_text='Semester number e.g. 1-8', null=True),
        ),
    ]
