# Generated by Django 4.2.28 on 2026-09-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_courseexceptionrule_selected_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupallocation',
            name='color',
            field=models.CharField(blank=True, default='#EFF6FF', help_text='Custom pastel background color', max_length=32),
        ),
    ]
