# Generated by Django 4.2.28 on 2026-09-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_groupallocation_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPeriodRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(help_text='Frontend generated ID', max_length=64, unique=True)),
                ('title', models.CharField(help_text='Title / Name for this special period', max_length=128)),
                ('color', models.CharField(blank=True, default='#EFF6FF', help_text='Custom pastel background color', max_length=32)),
                ('selected_years', models.JSONField(blank=True, default=list)),
                ('selected_departments', models.JSONField(blank=True, default=list)),
                ('selected_section_keys', models.JSONField(blank=True, default=list)),
                ('selected_mixed_section_keys', models.JSONField(blank=True, default=list)),
                ('exception_courses', models.JSONField(blank=True, default=list)),
                ('individual_periods', models.IntegerField(default=1)),
                ('paired_periods', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Special Period Rule',
                'verbose_name_plural': 'Special Period Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
