# Generated by Django 5.2.10 on 2026-01-24 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_attendance_models'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Application Type',
                'verbose_name_plural': 'Application Types',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('staff_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='academics.staffprofile')),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='academics.studentprofile')),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.applicationtype')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('FILE', 'File'), ('NUMBER', 'Number'), ('SELECT', 'Select')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='applications.applicationtype')),
            ],
            options={
                'ordering': ('application_type', 'order', 'field_key'),
                'unique_together': {('application_type', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flows', to='applications.applicationtype')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_flows', to='academics.department')),
                ('override_roles', models.ManyToManyField(blank=True, related_name='override_flows', to='accounts.role')),
            ],
            options={
                'unique_together': {('application_type', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('can_override', models.BooleanField(default=False)),
                ('auto_skip_if_unavailable', models.BooleanField(default=False)),
                ('approval_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='applications.approvalflow')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='accounts.role')),
            ],
            options={
                'ordering': ('approval_flow', 'order'),
                'unique_together': {('approval_flow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='applications.application')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='applications.approvalstep')),
            ],
            options={
                'ordering': ('-acted_at',),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_applications', to='applications.approvalstep'),
        ),
        migrations.CreateModel(
            name='ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='applications.application')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='applications.applicationfield')),
            ],
            options={
                'indexes': [models.Index(fields=['application', 'field'], name='application_applica_29ea28_idx')],
                'unique_together': {('application', 'field')},
            },
        ),
        migrations.CreateModel(
            name='RoleApplicationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_all', models.BooleanField(default=False)),
                ('can_override_flow', models.BooleanField(default=False)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='applications.applicationtype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_permissions', to='accounts.role')),
            ],
            options={
                'unique_together': {('role', 'application_type')},
            },
        ),
    ]
