# Generated by Django 5.2.10 on 2026-01-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_add_formversion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationformversion',
            unique_together={('application_type', 'version')},
        ),
    ]
