# Generated by Django 4.2.28 on 2026-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_flow_sla_and_gatepass_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('DATE', 'Date'), ('TIME', 'Time'), ('DATE IN OUT', 'Date In Out'), ('BOOLEAN', 'Boolean'), ('FILE', 'File'), ('NUMBER', 'Number'), ('SELECT', 'Select')], max_length=20),
        ),
    ]
