# Generated by Django 4.2.28 on 2026-03-14 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0011_alter_applicationfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gatepass_in_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='gatepass_in_scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatepass_in_scans', to=settings.AUTH_USER_MODEL),
        ),
    ]
