# Generated by GitHub Copilot on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_application_gatepass_in_scanned_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="gatepass_in_scanned_mode",
            field=models.CharField(choices=[("ONLINE", "Online"), ("OFFLINE", "Offline")], default="ONLINE", max_length=10),
        ),
        migrations.AddField(
            model_name="application",
            name="gatepass_scanned_mode",
            field=models.CharField(choices=[("ONLINE", "Online"), ("OFFLINE", "Offline")], default="ONLINE", max_length=10),
        ),
    ]
