# Generated by Django 4.2.28 on 2026-04-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_approvalstep_stage_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_submit', models.BooleanField(default=True)),
                ('submit_template', models.TextField(default='Hello {applicant_name},\nYour {application_type} application #{application_id} has been submitted successfully.\nStatus: Pending at {current_role}.\n{link}', help_text='Template for submission notification to applicant.')),
                ('notify_on_status_change', models.BooleanField(default=True)),
                ('approve_template', models.TextField(default='Hello {applicant_name},\nGood news! Your {application_type} application #{application_id} has been approved by {actor_name} ({actor_role}).\n{remarks}\nNext stage: {next_role}.\n{link}', help_text='Template for approval notification to applicant.')),
                ('reject_template', models.TextField(default='Hello {applicant_name},\nYour {application_type} application #{application_id} has been rejected by {actor_name} ({actor_role}).\n{remarks}\n{link}', help_text='Template for rejection notification to applicant.')),
                ('notify_on_forward', models.BooleanField(default=True)),
                ('forward_approver_template', models.TextField(default='Hello {approver_name},\nA {application_type} application #{application_id} is waiting for your approval.\nApplicant: {applicant_name}\nPending at: {current_role}\n{link}', help_text='Template for forward notification to next approver.')),
                ('forward_applicant_template', models.TextField(default='Hello {applicant_name},\nYour {application_type} application #{application_id} has been forwarded to {next_role} for review.\n{link}', help_text='Template for forward notification to applicant.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='applications.applicationtype')),
            ],
            options={
                'verbose_name': 'Application Notification Settings',
                'verbose_name_plural': 'Application Notification Settings',
            },
        ),
    ]
