# Generated by Django 4.2.28 on 2026-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationnotificationsettings',
            name='cancel_template',
            field=models.TextField(default='Hello {applicant_name},\nYour {application_type} application #{application_id} has been cancelled successfully.\n{link}', help_text='Template for cancellation confirmation notification to applicant.'),
        ),
        migrations.AddField(
            model_name='applicationnotificationsettings',
            name='notify_on_cancel',
            field=models.BooleanField(default=True),
        ),
    ]
