# Generated by Django 4.2.28 on 2026-08-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_cancel_notification_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationNotificationSettings',
        ),
    ]
