# Generated by generate_college_migrations.py
# Add nullable college FK to all tenant models in applications

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('applications', '0018_cancel_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applicationtypes',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='applicationfield',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applicationfields',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='application',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applications',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applicationdatas',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='approvalflows',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='approvalsteps',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='approvalactions',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='roleapplicationpermission',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='roleapplicationpermissions',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='applicationrolehierarchy',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applicationrolehierarchys',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='applicationrolehierarchystage',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applicationrolehierarchystages',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='applicationrolehierarchystagerole',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applicationrolehierarchystageroles',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='applicationrolehierarchystageuser',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applicationrolehierarchystageusers',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='applicationformversion',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applicationformversions',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='applicationattachment',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applicationattachments',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='applicationnotificationsettings',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applicationnotificationsettings',
                to='college.college',
            ),
        ),
    ]
