# Generated by Django 6.0.1 on 2026-01-30 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_titles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(default='')),
                ('options', models.JSONField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('btl', models.IntegerField(blank=True, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('chapter', models.CharField(blank=True, max_length=255, null=True)),
                ('course_outcomes', models.CharField(blank=True, max_length=255, null=True)),
                ('course_outcomes_numbers', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('source_file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('excel_type', models.CharField(blank=True, max_length=64, null=True)),
                ('course_code', models.CharField(blank=True, max_length=64, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_questions', to=settings.AUTH_USER_MODEL)),
                ('title_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question_bank.questionbanktitle')),
            ],
        ),
    ]
