# Generated by Django 6.0.1 on 2026-01-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbanktitle',
            name='exam_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='questionbanktitle',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbanktitle',
            name='sections',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbanktitle',
            name='faculty_identifier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
