# Generated by Django 4.2.28 on 2026-08-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('question_bank', '0005_harden_college_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbankquestion',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionbankquestions', to='college.college'),
        ),
        migrations.AlterField(
            model_name='questionbanktitle',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionbanktitles', to='college.college'),
        ),
    ]
