# Generated by Django 4.2.28 on 2026-07-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Machine-readable feature code (e.g. obe, coe)', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable feature name', max_length=128)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this feature provides')),
                ('category', models.CharField(blank=True, help_text='Grouping category (e.g. Academics, HR)', max_length=64)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name for frontend display', max_length=64)),
                ('is_default', models.BooleanField(default=False, help_text='If True, enabled by default for new colleges')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Catalog',
                'verbose_name_plural': 'Feature Catalog',
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CollegeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_features', to='college.college')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_entries', to='college.featurecatalog')),
            ],
            options={
                'verbose_name': 'College Feature',
                'verbose_name_plural': 'College Features',
                'ordering': ['feature__sort_order', 'feature__category'],
                'unique_together': {('college', 'feature')},
            },
        ),
    ]
