# Generated by Django 4.2.28 on 2026-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_featurecatalog_collegefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecatalog',
            name='applicable_roles',
            field=models.CharField(blank=True, default='', help_text='Comma-separated roles this feature is relevant to, e.g. STUDENT,FACULTY', max_length=255),
        ),
        migrations.AddField(
            model_name='featurecatalog',
            name='sidebar_keys',
            field=models.CharField(blank=True, default='', help_text='Comma-separated sidebar keys controlled by this feature', max_length=512),
        ),
    ]
