# Generated by Django 4.2.28 on 2026-07-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_role_features'),
        ('college', '0003_add_roles_and_sidebar_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecatalog',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions granted when this feature is assigned to a role', related_name='features', to='accounts.permission'),
        ),
    ]
