# Generated by Django 4.2.28 on 2026-08-29 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_merge_20260806_1234'),
        ('college', '0005_college_logo_banner_imagefields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_roles', to='college.college')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_roles', to='accounts.role')),
            ],
            options={
                'verbose_name': 'College Role',
                'verbose_name_plural': 'College Roles',
                'ordering': ['role__name'],
                'unique_together': {('college', 'role')},
            },
        ),
    ]
