# Generated by Django 4.2.28 on 2026-08-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_add_college_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro'), ('PREMIUM', 'Premium')], default='BASIC', help_text='Subscription tier for this college: BASIC, PRO, or PREMIUM', max_length=16),
        ),
    ]
