# Generated by Django 4.2.28 on 2026-03-07 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Leave, OD, Permission', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this request type')),
                ('is_active', models.BooleanField(default=True, help_text='Only active templates can be used')),
                ('form_schema', models.JSONField(default=list, help_text='Array of field definitions: [{name, type, label, required, options}, ...]')),
                ('allowed_roles', models.JSONField(default=list, help_text='List of role names that can submit this request type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Request Template',
                'verbose_name_plural': 'Request Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(default=dict, help_text="User responses matching the template's form_schema")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('current_step', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requests', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='staff_requests.requesttemplate')),
            ],
            options={
                'verbose_name': 'Staff Request',
                'verbose_name_plural': 'Staff Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(help_text='Sequential order (1, 2, 3...)')),
                ('approver_role', models.CharField(help_text="Role name of the approver (e.g., 'HOD', 'HR', 'PRINCIPAL')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='staff_requests.requesttemplate')),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
                'ordering': ['template', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(help_text='Which approval step this action relates to')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_request_approval_logs', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='staff_requests.staffrequest')),
            ],
            options={
                'verbose_name': 'Approval Log',
                'verbose_name_plural': 'Approval Logs',
                'ordering': ['step_order', 'action_date'],
            },
        ),
        migrations.AddIndex(
            model_name='staffrequest',
            index=models.Index(fields=['status', 'current_step'], name='staff_reque_status_ee9bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='staffrequest',
            index=models.Index(fields=['applicant', 'status'], name='staff_reque_applica_2b3eb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('template', 'step_order')},
        ),
    ]
