# Generated by Django 4.2.28 on 2026-03-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttemplate',
            options={'ordering': ['name'], 'permissions': (('manage_templates', 'Full control over creating and editing forms/workflows'),), 'verbose_name': 'Request Template', 'verbose_name_plural': 'Request Templates'},
        ),
        migrations.AlterModelOptions(
            name='staffrequest',
            options={'ordering': ['-created_at'], 'permissions': (('view_all_requests', 'Global view access to monitor all staff requests'), ('approve_requests', 'Access to the Pending Approvals dashboard')), 'verbose_name': 'Staff Request', 'verbose_name_plural': 'Staff Requests'},
        ),
    ]
