# Generated by Django 4.2.28 on 2026-03-07 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_requests', '0002_alter_requesttemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttemplate',
            name='leave_policy',
            field=models.JSONField(blank=True, default=dict, help_text='Leave and attendance policy configuration'),
        ),
        migrations.CreateModel(
            name='StaffLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(help_text="Leave type name (e.g., 'Casual Leave', 'COL', 'OD', 'LOP')", max_length=100)),
                ('balance', models.FloatField(default=0.0, help_text='Current balance for this leave type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Leave Balance',
                'verbose_name_plural': 'Staff Leave Balances',
                'ordering': ['staff', 'leave_type'],
                'unique_together': {('staff', 'leave_type')},
            },
        ),
    ]
