# Generated by Django 4.2.28 on 2026-03-07 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_requests', '0002_alter_requesttemplate_options_and_more'),
    ]

    operations = [
        # Model removed - operations commented out to fix migration conflict
        # migrations.RemoveConstraint(
        #     model_name='staffleaveledger',
        #     name='unique_staff_category',
        # ),
        # migrations.RenameIndex(
        #     model_name='staffleaveledger',
        #     new_name='staff_reque_staff_i_2322b3_idx',
        #     old_name='staff_reque_staff_id_categ_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='staffleaveledger',
        #     new_name='staff_reque_staff_i_6d023f_idx',
        #     old_name='staff_reque_staff_id_balanc_idx',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='staffleaveledger',
        #     unique_together={('staff', 'category_name')},
        # ),
    ]
