# Generated by Django 4.2.28 on 2026-03-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0003_requesttemplate_leave_policy_staffleavebalance'),
        ('staff_requests', '0004_remove_staffleaveledger_unique_staff_category_and_more'),
    ]

    operations = [
    ]
