# Generated by Django 4.2.28 on 2026-03-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0005_merge_20260307_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttemplate',
            name='attendance_action',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for attendance status changes on approval'),
        ),
    ]
