# Generated by Django migration for staff_requests

from django.db import migrations


def create_late_entry_template(apps, schema_editor):
    """Create the Late Entry Permission template with approval steps."""
    RequestTemplate = apps.get_model('staff_requests', 'RequestTemplate')
    ApprovalStep = apps.get_model('staff_requests', 'ApprovalStep')
    
    # Create or get the template
    template, created = RequestTemplate.objects.get_or_create(
        name='Late Entry Permission',
        defaults={
            'description': 'Request permission for late entry with specified time duration. If approved, attendance status changes from absent to present.',
            'is_active': True,
            'form_schema': [
                {
                    'name': 'date',
                    'type': 'date',
                    'label': 'Date',
                    'required': True,
                    'help_text': 'Date of late entry'
                },
                {
                    'name': 'shift',
                    'type': 'select',
                    'label': 'Shift',
                    'required': True,
                    'options': [
                        {'value': 'morning', 'label': 'Morning'},
                        {'value': 'evening', 'label': 'Evening'}
                    ],
                    'help_text': 'Which shift you will be late for'
                },
                {
                    'name': 'late_duration',
                    'type': 'select',
                    'label': 'Expected Late Duration',
                    'required': True,
                    'options': [
                        {'value': '10', 'label': '10 minutes'},
                        {'value': '30', 'label': '30 minutes'},
                        {'value': '60', 'label': '1 hour'},
                        {'value': '90', 'label': '1.5 hours'},
                        {'value': '120', 'label': '2 hours'}
                    ],
                    'help_text': 'How late you expect to be'
                },
                {
                    'name': 'reason',
                    'type': 'textarea',
                    'label': 'Reason',
                    'required': True,
                    'help_text': 'Reason for late entry'
                }
            ],
            'allowed_roles': ['STAFF', 'FACULTY', 'HOD', 'ASSISTANT', 'CLERK'],
            'leave_policy': {
                'action': 'neutral',  # No leave balance deduction
            },
            'attendance_action': {
                'change_status': True,
                'from_status': 'absent',
                'to_status': 'present',
                'apply_to_dates': ['date'],  # Apply to the 'date' field
                'date_format': 'YYYY-MM-DD',
                'add_notes': True,
                'notes_template': 'Late Entry Permission: {shift} shift, {late_duration} mins late'
            }
        }
    )
    
    # Create approval steps
    ApprovalStep.objects.get_or_create(
        template=template,
        step_order=1,
        defaults={'approver_role': 'HOD'}
    )
    
    ApprovalStep.objects.get_or_create(
        template=template,
        step_order=2,
        defaults={'approver_role': 'HR'}
    )


def delete_late_entry_template(apps, schema_editor):
    """Delete the Late Entry Permission template (for rollback)."""
    RequestTemplate = apps.get_model('staff_requests', 'RequestTemplate')
    RequestTemplate.objects.filter(name='Late Entry Permission').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0006_requesttemplate_attendance_action'),
    ]

    operations = [
        migrations.RunPython(create_late_entry_template, delete_late_entry_template),
    ]
