# Generated by Django 4.2.28 on 2026-03-09 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_requests', '0007_create_late_entry_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffFormUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this form has been used in current period')),
                ('reset_period_start', models.DateField(help_text='Start date of current tracking period')),
                ('reset_period_end', models.DateField(help_text='End date of current tracking period')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this form was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_usages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_usages', to='staff_requests.requesttemplate')),
            ],
            options={
                'verbose_name': 'Staff Form Usage',
                'verbose_name_plural': 'Staff Form Usages',
                'ordering': ['staff', 'template'],
                'unique_together': {('staff', 'template', 'reset_period_start')},
            },
        ),
    ]
