# Generated by Django 5.2.5 on 2026-03-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0008_requesttemplate_ledger_policy_staffformusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttemplate',
            name='ledger_policy',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy ledger policy configuration'),
        ),
    ]
