# Generated by Django 4.2.28 on 2026-03-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0009_add_ledger_policy_field'),
    ]

    operations = [
    ]
