# Generated by Django 4.2.28 on 2026-03-11 18:54

from django.db import migrations


def load_default_templates(apps, schema_editor):
    """
    Load 10 default request templates (5 normal + 5 SPL) with all configurations.
    Clears old templates and recreates with fresh 10.
    
    This includes:
    - Form schemas
    - Approval workflows
    - Leave policies
    - Attendance actions
    - Role permissions
    """
    RequestTemplate = apps.get_model('staff_requests', 'RequestTemplate')
    ApprovalStep = apps.get_model('staff_requests', 'ApprovalStep')

    # Delete old templates and recreate with fresh 10
    print('Clearing old templates...')
    RequestTemplate.objects.all().delete()
    print('✓ Cleared old templates')

    # Common form schemas
    # Insert `others_category` before `reason` so fresh installs include the dropdown
    leave_form_schema = [
        {"name": "others_category", "type": "select", "label": "Category", "required": False, "options": ["General", "Personal", "Other"], "placeholder": "Select category", "help_text": "Optional: Categorize your leave request"},
        {"name": "reason", "type": "text", "label": "Reason", "required": True, "help_text": "Provide reason for leave request"},
        {"name": "from_date", "type": "date", "label": "From Date", "required": True, "help_text": "Start date of leave/request. Holidays and Sundays will be excluded from the count."},
        {"name": "from_noon", "type": "select", "label": "From Noon", "options": ["Full day", "FN", "AN"], "required": True, "help_text": "Select FN (morning) or AN (afternoon) for start date"},
        {"name": "to_date", "type": "date", "label": "To Date", "required": False, "help_text": "End date (optional, leave empty for same day). Holidays and Sundays will be excluded."},
        {"name": "to_noon", "type": "select", "label": "To Noon", "options": ["Full day", "FN", "AN"], "required": False, "help_text": "Select FN or AN for end date (optional)"}
    ]
    
    # Late entry now uses shift + late_duration instead of an explicit time field
    # Auto-approval logic: 10 mins FN is auto-approved if morning_in is within (dept_cutoff, dept_cutoff+10min]
    late_entry_form_schema = [
        {"name": "reason", "type": "text", "label": "Reason", "required": True, "help_text": "Reason for late entry"},
        {"name": "from_date", "type": "date", "label": "Date", "required": True, "help_text": "Date of late entry"},
        {"name": "shift", "type": "select", "label": "Shift", "required": True, "options": ["FN", "AN"], "help_text": "FN (morning) or AN (afternoon) shift"},
        {"name": "late_duration", "type": "select", "label": "Late Duration", "required": True, "options": ["10 mins", "1 hr"], "help_text": "10 mins (auto-approved for FN only if in-time is within cutoff+10min window) or 1 hr (normal approval)"}
    ]
    
    od_form_schema = [
        {"name": "type", "type": "select", "label": "OD Type", "options": ["ODB - Basic", "ODR - Research", "ODP - Professional", "ODO - Out Reach"], "required": True, "help_text": "Select the type of official duty"},
        {"name": "reason", "type": "text", "label": "Reason", "required": True, "help_text": "Provide details of official duty"},
        {"name": "from_date", "type": "date", "label": "From Date", "required": True, "help_text": "Start date of official duty. Holidays and Sundays will be excluded."},
        {"name": "from_noon", "type": "select", "label": "From Noon", "options": ["Full Day ", "FN ", "AN"], "required": True, "help_text": "Select FN (morning) or AN (afternoon) for start date"},
        {"name": "to_date", "type": "date", "label": "To Date", "required": False, "help_text": "End date (optional, leave empty for same day). Holidays and Sundays will be excluded."},
        {"name": "to_noon", "type": "select", "label": "To Noon", "options": ["Full Day ", "FN ", "AN"], "required": False, "help_text": "Select FN or AN for end date (optional)"}
    ]
    
    # Role definitions
    COMMON_ROLES = ["STAFF", "FACULTY", "ASSISTANT", "CLERK"]
    SPL_ROLES = ["IQAC", "HR", "PS", "HOD", "CFSW", "EDC", "COE", "HAA"]
    
    # Template configurations
    templates_config = [
        # Normal Templates (5)
        {
            "name": "Casual Leave",
            "description": "Staffs can apply leave",
            "is_active": True,
            "form_schema": leave_form_schema,
            "allowed_roles": COMMON_ROLES,
            "ledger_policy": {},
            "leave_policy": {
                "action": "deduct",
                "from_date": "2026-01-01",
                "to_date": "2026-12-31",
                "split_date": "2026-07-01",
                "attendance_status": "CL",
                "allotment_per_role": {"STAFF": 12, "HOD": 12},
                "reset_duration": "monthly",
                "overdraft_name": "LOP"
            },
            "attendance_action": {
                "change_status": True,
                "from_status": "absent",
                "to_status": "present",
                "apply_to_dates": ["from_date", "to_date"],
                "date_format": "YYYY-MM-DD",
                "add_notes": True,
                "notes_template": "Leave approved"
            },
            "approval_steps": ["HOD", "HR"]
        },
        {
            "name": "Compensatory leave",
            "description": "Staffs can apply",
            "is_active": True,
            "form_schema": leave_form_schema,
            "allowed_roles": COMMON_ROLES,
            "ledger_policy": {},
            # Compensatory leave should be treated as an earn action so it appears on holidays
            "leave_policy": {"action": "earn", "attendance_status": "COL"},
            "attendance_action": {
                "change_status": True,
                "from_status": "absent",
                "to_status": "present",
                "apply_to_dates": ["from_date", "to_date"],
                "date_format": "YYYY-MM-DD",
                "add_notes": True,
                "notes_template": "COL Leave approved"
            },
            "approval_steps": ["HOD", "HR"]
        },
        {
            "name": "Late Entry Permission",
            "description": "Staff can apply for late entry permission",
            "is_active": True,
            "form_schema": late_entry_form_schema,
            "allowed_roles": COMMON_ROLES,
            "ledger_policy": {},
            "leave_policy": {
                "action": "neutral",
                "reset_period": "monthly"
            },
            "attendance_action": {
                "change_status": True,
                "from_status": "absent",
                "to_status": "present",
                "apply_to_dates": ["from_date"],
                "date_format": "YYYY-MM-DD",
                "add_notes": True,
                "notes_template": "Late Entry approved ({shift}, {late_duration})"
            },
            "approval_steps": ["HOD", "HR"]
        },
        {
            "name": "ON duty",
            "description": "staffs will apply",
            "is_active": True,
            "form_schema": od_form_schema,
            "allowed_roles": COMMON_ROLES,
            "ledger_policy": {},
            "leave_policy": {"action": "neutral", "attendance_status": "OD"},
            "attendance_action": {
                "change_status": True,
                "from_status": "absent",
                "to_status": "present",
                "apply_to_dates": ["from_date", "to_date"],
                "date_format": "YYYY-MM-DD",
                "add_notes": True,
                "notes_template": "OD approved"
            },
            "approval_steps": ["HOD", "HR"]
        },
        {
            "name": "Others",
            "description": "staffs will apply",
            "is_active": True,
            "form_schema": leave_form_schema,
            "allowed_roles": COMMON_ROLES,
            "ledger_policy": {},
            "leave_policy": {"action": "neutral"},
            "attendance_action": {},
            "approval_steps": ["HOD", "HR"]
        },
        
        # SPL Templates (5)
        {
            "name": "Casual Leave - SPL",
            "description": "Leave for special administrative roles",
            "is_active": True,
            "form_schema": leave_form_schema,
            "allowed_roles": SPL_ROLES,
            "ledger_policy": {},
            "leave_policy": {
                "action": "deduct",
                "from_date": "2026-01-01",
                "to_date": "2026-12-31",
                "split_date": "2026-07-01",
                "attendance_status": "CL",
                "allotment_per_role": {"STAFF": 12, "HOD": 12},
                "reset_duration": "monthly",
                "overdraft_name": "LOP"
            },
            "attendance_action": {
                "change_status": True,
                "from_status": "absent",
                "to_status": "present",
                "apply_to_dates": ["from_date", "to_date"],
                "date_format": "YYYY-MM-DD",
                "add_notes": True,
                "notes_template": "Leave approved"
            },
            "approval_steps": ["PRINCIPAL"]
        },
        {
            "name": "Compensatory leave - SPL",
            "description": "COL for special administrative roles",
            "is_active": True,
            "form_schema": leave_form_schema,
            "allowed_roles": SPL_ROLES,
            "ledger_policy": {},
            "leave_policy": {"action": "earn", "attendance_status": "COL"},
            "attendance_action": {
                "change_status": True,
                "from_status": "absent",
                "to_status": "present",
                "apply_to_dates": ["from_date", "to_date"],
                "date_format": "YYYY-MM-DD",
                "add_notes": True,
                "notes_template": "COL Leave approved"
            },
            "approval_steps": ["PRINCIPAL"]
        },
        {
            "name": "Late Entry Permission - SPL",
            "description": "Late entry for special administrative roles",
            "is_active": True,
            "form_schema": late_entry_form_schema,
            "allowed_roles": SPL_ROLES,
            "ledger_policy": {},
            "leave_policy": {
                "action": "neutral",
                "reset_period": "monthly"
            },
            "attendance_action": {
                "change_status": True,
                "from_status": "absent",
                "to_status": "present",
                "apply_to_dates": ["from_date"],
                "date_format": "YYYY-MM-DD",
                "add_notes": True,
                "notes_template": "Late Entry approved ({shift}, {late_duration})"
            },
            "approval_steps": ["PRINCIPAL"]
        },
        {
            "name": "ON duty - SPL",
            "description": "OD for special administrative roles",
            "is_active": True,
            "form_schema": od_form_schema,
            "allowed_roles": SPL_ROLES,
            "ledger_policy": {},
            "leave_policy": {"action": "neutral", "attendance_status": "OD"},
            "attendance_action": {
                "change_status": True,
                "from_status": "absent",
                "to_status": "present",
                "apply_to_dates": ["from_date", "to_date"],
                "date_format": "YYYY-MM-DD",
                "add_notes": True,
                "notes_template": "OD approved"
            },
            "approval_steps": ["PRINCIPAL"]
        },
        {
            "name": "Others - SPL",
            "description": "Other requests for special administrative roles",
            "is_active": True,
            "form_schema": leave_form_schema,
            "allowed_roles": SPL_ROLES,
            "ledger_policy": {},
            "leave_policy": {"action": "neutral"},
            "attendance_action": {},
            "approval_steps": ["PRINCIPAL"]
        }
    ]
    
    # Create templates and approval steps
    print('Creating/updating 10 default templates...')
    for config in templates_config:
        approval_steps = config.pop('approval_steps')
        template_name = config['name']
        
        # Use update_or_create to update existing templates or create new ones
        template, created = RequestTemplate.objects.update_or_create(
            name=template_name,
            defaults=config
        )
        
        if created:
            print(f'  ✓ Created: {template.name}')
        else:
            print(f'  ✓ Updated: {template.name}')
        
        # Delete existing approval steps and create new ones
        ApprovalStep.objects.filter(template=template).delete()
        
        # Create approval steps
        for step_order, approver_role in enumerate(approval_steps, start=1):
            ApprovalStep.objects.create(
                template=template,
                step_order=step_order,
                approver_role=approver_role
            )
    
    print('✓ Successfully created/updated 10 default templates (5 normal + 5 SPL)')


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0010_seed_default_templates'),
    ]

    operations = [
        migrations.RunPython(load_default_templates, reverse_code=migrations.RunPython.noop),
    ]
