# Generated by Django 4.2.28 on 2026-07-31 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_requests', '0017_alter_eventattendingapprovallog_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBudgetCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('normal', 'Normal Events'), ('conference', 'Conference Events')], help_text='Normal Events or Conference Events', max_length=20)),
                ('designation', models.CharField(help_text='Staff designation this condition applies to', max_length=200)),
                ('exp_condition', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('==', '==')], default='>=', help_text='Comparison operator for experience', max_length=2)),
                ('exp_value', models.FloatField(default=0, help_text='Experience threshold in years (2.2 = 2 yrs 2 months)')),
                ('amount', models.FloatField(default=0, help_text='Budget amount in INR to apply to matching staff')),
                ('from_date', models.DateField(help_text='Condition validity start date (auto-filled from active Academic Calendar)')),
                ('to_date', models.DateField(help_text='Condition validity end date (auto-filled from active Academic Calendar)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_budget_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Budget Condition',
                'verbose_name_plural': 'Event Budget Conditions',
                'ordering': ['event_type', 'designation', 'exp_value'],
            },
        ),
    ]
