# Generated by Django 4.2.28 on 2026-07-31 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0018_event_budget_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendingform',
            name='custom_event_details',
            field=models.JSONField(blank=True, help_text='Stores manual event details if not linked to OD form', null=True),
        ),
        migrations.AddField(
            model_name='eventattendingform',
            name='event_proof',
            field=models.FileField(blank=True, help_text='Proof document for standalone event forms', null=True, upload_to='event_proofs/'),
        ),
        migrations.AlterField(
            model_name='eventattendingform',
            name='on_duty_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attending_forms', to='staff_requests.staffrequest'),
        ),
    ]
