# Generated by Django 4.2.28 on 2026-08-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0020_eventbudgetcondition_exp_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbudgetcondition',
            name='exp_condition',
            field=models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('==', '==')], default='>=', help_text='Comparison operator applied to exp_value (upper/exact bound)', max_length=2),
        ),
        migrations.AlterField(
            model_name='eventbudgetcondition',
            name='exp_from',
            field=models.FloatField(blank=True, default=None, help_text="Optional lower-bound experience in years (inclusive). E.g. exp_from=5, exp_condition='<', exp_value=8 → 5 ≤ exp < 8. Leave blank for open-ended conditions like '> 8 years'.", null=True),
        ),
        migrations.AlterField(
            model_name='eventbudgetcondition',
            name='exp_value',
            field=models.FloatField(default=0, help_text='Experience upper/exact bound in years (2.2 = 2 yrs 2 months)'),
        ),
    ]
