# Generated by Django 4.2.28 on 2026-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0021_alter_eventbudgetcondition_exp_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendingfile',
            name='expense_type',
            field=models.CharField(choices=[('travel', 'Travel'), ('food', 'Food'), ('other', 'Other'), ('fees', 'Fees'), ('advance', 'Advance Receipt')], max_length=20),
        ),
    ]
