# Generated by generate_college_migrations.py
# Backfill college_id on staff_requests models to the primary college

from django.db import migrations


def _get_primary_college_id(apps):
    College = apps.get_model('college', 'College')
    c = College.objects.filter(is_active=True).order_by('id').first()
    if c is None:
        c = College.objects.create(code='PRIMARY', name='Primary College', short_name='PRIMARY', is_active=True)
    return c.id


def backfill(apps, schema_editor):
    cid = _get_primary_college_id(apps)
    model_names = [
            'ApprovalLog',
            'ApprovalStep',
            'EventAttendingApprovalLog',
            'EventAttendingApprovalWorkflow',
            'EventAttendingFile',
            'EventAttendingForm',
            'EventBudgetCondition',
            'RequestTemplate',
            'StaffEventDeclaration',
            'StaffFormUsage',
            'StaffLeaveBalance',
            'StaffRequest',
            'VacationConfirmSlot',
            'VacationEntitlementRule',
            'VacationSemester',
            'VacationSlot',
    ]
    for name in model_names:
        Model = apps.get_model('staff_requests', name)
        Model.objects.filter(college__isnull=True).update(college_id=cid)


def reverse_backfill(apps, schema_editor):
    model_names = [
            'ApprovalLog',
            'ApprovalStep',
            'EventAttendingApprovalLog',
            'EventAttendingApprovalWorkflow',
            'EventAttendingFile',
            'EventAttendingForm',
            'EventBudgetCondition',
            'RequestTemplate',
            'StaffEventDeclaration',
            'StaffFormUsage',
            'StaffLeaveBalance',
            'StaffRequest',
            'VacationConfirmSlot',
            'VacationEntitlementRule',
            'VacationSemester',
            'VacationSlot',
    ]
    for name in model_names:
        Model = apps.get_model('staff_requests', name)
        Model.objects.all().update(college_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('staff_requests', '0022_add_college_fk'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse_backfill),
    ]
