# Generated by Django 4.2.28 on 2026-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0022_add_advance_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendingfile',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', help_text='How to display this proof in the PDF: portrait (1 per page) or landscape (2 per page)', max_length=10),
        ),
    ]
