# Generated by Django 4.2.28 on 2026-08-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_requests', '0023_add_orientation_to_event_attending_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendingapprovallog',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='eventattendingapprovallog',
            name='event_form',
        ),
        migrations.DeleteModel(
            name='EventAttendingApprovalWorkflow',
        ),
        migrations.RemoveField(
            model_name='eventattendingfile',
            name='event_form',
        ),
        migrations.RemoveField(
            model_name='eventattendingform',
            name='on_duty_request',
        ),
        migrations.RemoveField(
            model_name='eventattendingform',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='eventbudgetcondition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='staffeventdeclaration',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='vacationconfirmslot',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='vacationconfirmslot',
            name='semester_ref',
        ),
        migrations.DeleteModel(
            name='VacationEntitlementRule',
        ),
        migrations.RemoveField(
            model_name='vacationslot',
            name='semester_ref',
        ),
        migrations.DeleteModel(
            name='EventAttendingApprovalLog',
        ),
        migrations.DeleteModel(
            name='EventAttendingFile',
        ),
        migrations.DeleteModel(
            name='EventAttendingForm',
        ),
        migrations.DeleteModel(
            name='EventBudgetCondition',
        ),
        migrations.DeleteModel(
            name='StaffEventDeclaration',
        ),
        migrations.DeleteModel(
            name='VacationConfirmSlot',
        ),
        migrations.DeleteModel(
            name='VacationSemester',
        ),
        migrations.DeleteModel(
            name='VacationSlot',
        ),
    ]
