# Generated by Django 4.2.28 on 2026-09-03 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineApprovalFlowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Discipline Flow', max_length=128)),
                ('roles', models.JSONField(default=list, help_text='Ordered array of role strings through which the incident travels.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discipline Approval Flow Config',
                'verbose_name_plural': 'Discipline Approval Flow Configs',
            },
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='current_role',
            field=models.CharField(blank=True, default='', help_text='Current approver role waiting for action', max_length=100),
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='current_step_index',
            field=models.PositiveIntegerField(default=0, help_text='Index in flow_roles where the request currently is'),
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fine amount in Rupees', max_digits=10),
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='fine_fixed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='fine_fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_fixed_discipline_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='flow_roles',
            field=models.JSONField(default=list, help_text='Snapshot of the roles path for this incident'),
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='has_fine',
            field=models.BooleanField(default=False, help_text='True if a fine has been fixed for this incident'),
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='receipt_document',
            field=models.FileField(blank=True, null=True, upload_to='discipline/receipts/'),
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='receipt_document_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='receipt_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disciplineincidentlog',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplineincidentlog',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('PENDING_FINE_PAYMENT', 'Pending Fine Payment'), ('RECEIPT_UPLOADED', 'Receipt Uploaded'), ('IN_APPROVAL', 'In Approval'), ('ACTION_TAKEN', 'Action Taken'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='REPORTED', max_length=32),
        ),
        migrations.CreateModel(
            name='DisciplineIncidentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('REPORTED', 'Incident Reported'), ('FINE_FIXED', 'Fine Fixed'), ('FINE_MODIFIED', 'Fine Modified'), ('RECEIPT_UPLOADED', 'Receipt Uploaded'), ('FORWARDED', 'Forwarded to Next Approver'), ('APPROVED', 'Approved & Completed'), ('REJECTED', 'Rejected')], max_length=32)),
                ('role_performed', models.CharField(blank=True, default='', max_length=100)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('document_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='discipline.disciplineincidentlog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
