"""Initial migration for coder app."""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0087_alter_staffprofile_staff_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='coder/thumbnails/')),
                ('academic_year', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DRAFT', 'Draft')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coder_courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Code Course', 'verbose_name_plural': 'Code Courses', 'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='CodeCourseIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incharge_assignments', to='coder.codecourse')),
                ('user', models.ForeignKey(help_text='Faculty/staff user who has CODE_COURSE_INCHARGE role', on_delete=django.db.models.deletion.CASCADE, related_name='coder_incharge_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coder_incharge_assignments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Course Incharge', 'verbose_name_plural': 'Course Incharges', 'unique_together': {('course', 'user')}},
        ),
        migrations.CreateModel(
            name='CodeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. CSE-A, IT-B', max_length=64)),
                ('academic_year', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='coder.codecourse')),
                ('idcs_section', models.ForeignKey(blank=True, help_text='Linked IDCS section for automatic student enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coder_classes', to='academics.section')),
            ],
            options={'verbose_name': 'Code Class', 'verbose_name_plural': 'Code Classes', 'unique_together': {('course', 'name')}},
        ),
        migrations.CreateModel(
            name='CodeSectionIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_incharge_assignments', to='coder.codeclass')),
                ('user', models.ForeignKey(help_text='User with CODE_SECTION_INCHARGE role', on_delete=django.db.models.deletion.CASCADE, related_name='coder_section_incharge_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coder_section_incharge_assignments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Section Incharge', 'verbose_name_plural': 'Section Incharges', 'unique_together': {('code_class', 'user')}},
        ),
        migrations.CreateModel(
            name='CodeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coder_enrollments', to='academics.studentprofile')),
                ('code_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='coder.codeclass')),
            ],
            options={'verbose_name': 'Code Enrollment', 'verbose_name_plural': 'Code Enrollments', 'unique_together': {('student', 'code_class')}},
        ),
        migrations.CreateModel(
            name='CodeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('session_type', models.CharField(choices=[('MCQ', 'MCQ'), ('LAB', 'Lab'), ('PROJECT', 'Project')], default='LAB', max_length=16)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='coder.codecourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coder_sessions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Code Session', 'verbose_name_plural': 'Code Sessions', 'ordering': ('course', 'order')},
        ),
        migrations.CreateModel(
            name='CodeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('assessment_type', models.CharField(choices=[('MCQ', 'MCQ'), ('CODING', 'Coding')], max_length=16)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='coder.codesession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coder_assessments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Code Assessment', 'verbose_name_plural': 'Code Assessments', 'ordering': ('session', 'created_at')},
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question (target column from Excel)')),
                ('correct_answer', models.TextField()),
                ('wrong_ans1', models.TextField()),
                ('wrong_ans2', models.TextField()),
                ('wrong_ans3', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='coder.codeassessment')),
            ],
            options={'verbose_name': 'MCQ Question', 'verbose_name_plural': 'MCQ Questions', 'ordering': ('assessment', 'order')},
        ),
        migrations.CreateModel(
            name='CodingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported_languages', models.JSONField(default=list, help_text='List of supported file extensions e.g. [".java", ".py"]')),
                ('time_limit_seconds', models.PositiveIntegerField(default=10)),
                ('memory_limit_mb', models.PositiveIntegerField(default=256)),
                ('cpu_limit', models.FloatField(default=0.5, help_text='Docker CPU limit (cores)')),
                ('entry_point', models.CharField(blank=True, default='', help_text='Main file to execute e.g. src/Main.java', max_length=256)),
                ('build_command', models.CharField(blank=True, default='', help_text='Build command e.g. javac -d . src/Main.java', max_length=512)),
                ('run_command', models.CharField(blank=True, default='', help_text='Run command e.g. java Main', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_project', to='coder.codeassessment')),
            ],
            options={'verbose_name': 'Coding Project', 'verbose_name_plural': 'Coding Projects'},
        ),
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_locked', models.BooleanField(default=False, help_text='If locked, students cannot create files inside this folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='coder.codingproject')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_folders', to='coder.projectfolder')),
            ],
            options={'verbose_name': 'Project Folder', 'verbose_name_plural': 'Project Folders', 'unique_together': {('project', 'parent', 'name')}},
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, default='')),
                ('is_locked', models.BooleanField(default=False, help_text='If locked, students cannot delete or rename this file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='coder.codingproject')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='coder.projectfolder')),
            ],
            options={'verbose_name': 'Project File', 'verbose_name_plural': 'Project Files', 'unique_together': {('project', 'folder', 'name')}},
        ),
        migrations.CreateModel(
            name='LockedCodeRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_line', models.PositiveIntegerField()),
                ('end_line', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_regions', to='coder.projectfile')),
            ],
            options={'verbose_name': 'Locked Code Region', 'verbose_name_plural': 'Locked Code Regions', 'ordering': ('file', 'start_line')},
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden test cases are NOT sent to student browser')),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='coder.codeassessment')),
            ],
            options={'verbose_name': 'Test Case', 'verbose_name_plural': 'Test Cases', 'ordering': ('assessment', 'order')},
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPILING', 'Compiling'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ERROR', 'Error'), ('REJECTED', 'Rejected'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=16)),
                ('score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('failed_tests', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result_details', models.JSONField(default=dict, help_text='Per-test results — hidden test details are NOT included')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coder.codeassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coder_submissions', to='academics.studentprofile')),
            ],
            options={'verbose_name': 'Code Submission', 'verbose_name_plural': 'Code Submissions', 'ordering': ('-submitted_at',)},
        ),
        migrations.CreateModel(
            name='MCQSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('answers', models.JSONField(default=dict, help_text='{question_id: submitted_answer_text}')),
                ('score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('result_details', models.JSONField(default=list, help_text="Per-question result — does NOT expose correct answers")),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_submissions', to='coder.codeassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_submissions', to='academics.studentprofile')),
            ],
            options={'verbose_name': 'MCQ Submission', 'verbose_name_plural': 'MCQ Submissions', 'ordering': ('-submitted_at',)},
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_sessions', models.JSONField(default=list, help_text='List of completed CodeSession IDs')),
                ('in_progress_sessions', models.JSONField(default=list, help_text='List of in-progress CodeSession IDs')),
                ('overall_score', models.FloatField(default=0)),
                ('total_possible_score', models.FloatField(default=0)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='coder.codecourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coder_progress', to='academics.studentprofile')),
            ],
            options={'verbose_name': 'Student Progress', 'verbose_name_plural': 'Student Progress', 'unique_together': {('student', 'course')}},
        ),
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_run_only', models.BooleanField(default=False, help_text='True = Run (public tests only); False = Submit (full evaluation)')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout')], default='QUEUED', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='coder.codeassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coder_executions', to='academics.studentprofile')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='coder.codesubmission')),
            ],
            options={'verbose_name': 'Code Execution', 'verbose_name_plural': 'Code Executions', 'ordering': ('-started_at',)},
        ),
    ]
