# Generated by Django 4.2.28 on 2026-08-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0003_single_file_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexecutionsession',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='codeexecutionsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='codingproject',
            name='runtime_version',
            field=models.CharField(default='21', help_text='Runtime version e.g. 21 for Java 21', max_length=16),
        ),
    ]
