# Generated by Django 4.2.28 on 2026-08-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_codeexecutionsession_source_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockedcoderegion',
            name='end_column',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lockedcoderegion',
            name='start_column',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
