# Generated by Django 5.2.10 on 2026-01-28 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0007_roleassignment_staffdepartmentassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=32)),
                ('semester', models.PositiveSmallIntegerField()),
                ('course_code', models.CharField(max_length=64)),
                ('course_name', models.CharField(max_length=255)),
                ('class_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab')], default='THEORY', max_length=16)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('l', models.PositiveSmallIntegerField(default=0)),
                ('t', models.PositiveSmallIntegerField(default=0)),
                ('p', models.PositiveSmallIntegerField(default=0)),
                ('s', models.PositiveSmallIntegerField(default=0)),
                ('c', models.PositiveSmallIntegerField(default=0)),
                ('internal_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('external_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('for_all_departments', models.BooleanField(default=True)),
                ('editable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='master_curricula', to='academics.department')),
            ],
            options={
                'verbose_name': 'Curriculum Master',
                'verbose_name_plural': 'Curriculum Masters',
                'unique_together': {('regulation', 'semester', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=32)),
                ('semester', models.PositiveSmallIntegerField()),
                ('course_code', models.CharField(max_length=64)),
                ('course_name', models.CharField(max_length=255)),
                ('class_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab')], default='THEORY', max_length=16)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('l', models.PositiveSmallIntegerField(default=0)),
                ('t', models.PositiveSmallIntegerField(default=0)),
                ('p', models.PositiveSmallIntegerField(default=0)),
                ('s', models.PositiveSmallIntegerField(default=0)),
                ('c', models.PositiveSmallIntegerField(default=0)),
                ('internal_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('external_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('question_paper_type', models.CharField(default='QP1', max_length=64)),
                ('editable', models.BooleanField(default=False)),
                ('overridden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_rows', to='academics.department')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_rows', to='curriculum.curriculummaster')),
            ],
            options={
                'verbose_name': 'Department Curriculum',
                'verbose_name_plural': 'Department Curricula',
                'unique_together': {('department', 'regulation', 'semester', 'course_code')},
            },
        ),
    ]
