# Generated by Django 5.2.10 on 2026-02-01 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_curriculumdepartment_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('AUDIT', 'Audit')], default='THEORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_rows', to='curriculum.curriculummaster'),
        ),
        migrations.AlterField(
            model_name='curriculummaster',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('AUDIT', 'Audit')], default='THEORY', max_length=16),
        ),
    ]
