# Generated by Django 5.2.10 on 2026-02-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_section_semester'),
        ('curriculum', '0004_alter_curriculumdepartment_class_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_curricula', to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='curriculummaster',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_curricula', to='academics.semester'),
        ),
    ]
