# Generated by Django 5.2.11 on 2026-02-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_curriculumdepartment_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumdepartment',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculummaster',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
