# Generated by Django 5.2.11 on 2026-02-07 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_periodattendancesession_periodattendancerecord'),
        ('curriculum', '0006_curriculumdepartment_is_elective_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=32)),
                ('course_code', models.CharField(blank=True, max_length=64, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('class_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('AUDIT', 'Audit')], default='THEORY', max_length=16)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('is_elective', models.BooleanField(default=True)),
                ('l', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('t', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('p', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('s', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('c', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('internal_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('external_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('question_paper_type', models.CharField(default='QP1', max_length=64)),
                ('editable', models.BooleanField(default=False)),
                ('overridden', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_elective_subjects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_subjects', to='academics.department')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_options', to='curriculum.curriculumdepartment')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elective_subjects', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Elective Subject',
                'verbose_name_plural': 'Elective Subjects',
                'unique_together': {('parent', 'course_code')},
            },
        ),
    ]
