# Generated by Django 5.2.11 on 2026-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_add_electivechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivechoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
