# Generated by Django 5.2.11 on 2026-02-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_regulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='question_paper_type',
            field=models.CharField(blank=True, default='QP1', max_length=64),
        ),
        migrations.AlterField(
            model_name='electivesubject',
            name='question_paper_type',
            field=models.CharField(blank=True, default='QP1', max_length=64),
        ),
    ]
