# Generated by Django 5.2.11 on 2026-02-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_special_courses_enabled_assessments'),
        ('curriculum', '0012_electivechoice_import_permission'),
    ]

    operations = [
    ]
