# Generated by Django 6.0.2 on 2026-02-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_merge_20260211_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivesubject',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special')], default='THEORY', max_length=16),
        ),
    ]
