# Generated by Django 6.0.2 on 2026-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_alter_electivesubject_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special')], default='THEORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='curriculummaster',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special')], default='THEORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='electivesubject',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special')], default='THEORY', max_length=16),
        ),
    ]
