# Generated by Django 4.2.28 on 2026-02-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_alter_curriculumdepartment_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumdepartment',
            name='mnemonic',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
