# Generated by Django 5.2.5 on 2026-02-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_curriculumdepartment_mnemonic'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculummaster',
            name='qp_type',
            field=models.CharField(blank=True, choices=[('QP1', 'QP1'), ('QP2', 'QP2'), ('ASPR', 'ASPR')], default='QP1', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('THEORY_PMBL', 'Theory (PMBL)'), ('LAB', 'Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PRBL', 'PRBL'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special')], default='THEORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='question_paper_type',
            field=models.CharField(blank=True, choices=[('QP1', 'QP1'), ('QP2', 'QP2'), ('ASPR', 'ASPR')], default='QP1', max_length=64),
        ),
        migrations.AlterField(
            model_name='curriculummaster',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('THEORY_PMBL', 'Theory (PMBL)'), ('LAB', 'Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PRBL', 'PRBL'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special')], default='THEORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='electivesubject',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('THEORY_PMBL', 'Theory (PMBL)'), ('LAB', 'Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PRBL', 'PRBL'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special')], default='THEORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='electivesubject',
            name='question_paper_type',
            field=models.CharField(blank=True, choices=[('QP1', 'QP1'), ('QP2', 'QP2'), ('ASPR', 'ASPR')], default='QP1', max_length=64),
        ),
    ]
