# Generated by Django 5.2.5 on 2026-03-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0051_period_attendance_swap'),
        ('curriculum', '0017_curriculummaster_qp_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Group',
                'verbose_name_plural': 'Department Groups',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='DepartmentGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='academics.department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_mappings', to='curriculum.departmentgroup')),
            ],
            options={
                'verbose_name': 'Department Group Mapping',
                'verbose_name_plural': 'Department Group Mappings',
                'ordering': ('group', 'department'),
                'unique_together': {('group', 'department')},
            },
        ),
    ]
