# Generated by Django 5.2.5 on 2026-03-02 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_departmentgroup_departmentgroupmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivesubject',
            name='department_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_subjects', to='curriculum.departmentgroup'),
        ),
    ]
