# Generated by Django 4.2.28 on 2026-03-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0051_period_attendance_swap'),
        ('curriculum', '0019_electivesubject_department_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumdepartment',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional batch this curriculum applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_curricula', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='curriculummaster',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional batch this curriculum applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_curricula', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='electivesubject',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional batch this elective applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_subjects', to='academics.batch'),
        ),
    ]
