# Generated by Django 4.2.28 on 2026-03-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0052_add_batchyear_model'),
        ('curriculum', '0020_add_batch_to_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional batch year this curriculum applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_curricula', to='academics.batchyear'),
        ),
        migrations.AlterField(
            model_name='curriculummaster',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional batch year this curriculum applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_curricula', to='academics.batchyear'),
        ),
        migrations.AlterField(
            model_name='electivesubject',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional batch year this elective applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_subjects', to='academics.batchyear'),
        ),
    ]
