# Generated by Django 4.2.28 on 2026-03-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_swap_batch_to_batchyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumdepartment',
            name='is_dept_core',
            field=models.BooleanField(default=False, help_text='Mark this subject as a department-core variant for shared Year-1 S&H sections.'),
        ),
        migrations.AddField(
            model_name='curriculummaster',
            name='is_dept_core',
            field=models.BooleanField(default=False, help_text='True for department-specific core subjects taught inside shared (S&H) Year-1 sections. Each department owns an ElectiveSubject child; timetable auto-resolves by home_department.'),
        ),
    ]
