# Generated by Django 4.2.28 on 2026-04-12 12:07

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0027_classtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='class_type',
            field=models.CharField(default='THEORY', max_length=16, validators=[curriculum.models.validate_class_type_code]),
        ),
        migrations.AlterField(
            model_name='curriculummaster',
            name='class_type',
            field=models.CharField(default='THEORY', max_length=16, validators=[curriculum.models.validate_class_type_code]),
        ),
        migrations.AlterField(
            model_name='electivesubject',
            name='class_type',
            field=models.CharField(default='THEORY', max_length=16, validators=[curriculum.models.validate_class_type_code]),
        ),
    ]
