# Generated by Django 5.2.5 on 2026-05-02 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0089_alter_staffprofile_staff_id_validation'),
        ('curriculum', '0029_add_foreign_lang_class_type_and_flc_qp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('THEORY_PMBL', 'Theory (PMBL)'), ('LAB', 'Lab'), ('PURE_LAB', 'Pure Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PRBL', 'PRBL'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special'), ('ENGLISH', 'English')], default='THEORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='curriculummaster',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('THEORY_PMBL', 'Theory (PMBL)'), ('LAB', 'Lab'), ('PURE_LAB', 'Pure Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PRBL', 'PRBL'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special'), ('ENGLISH', 'English')], default='THEORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='electivesubject',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('THEORY_PMBL', 'Theory (PMBL)'), ('LAB', 'Lab'), ('PURE_LAB', 'Pure Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PRBL', 'PRBL'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special'), ('ENGLISH', 'English')], default='THEORY', max_length=16),
        ),
        migrations.CreateModel(
            name='ElectivePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_elective_name', models.CharField(max_length=255)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_polls', to='academics.batchyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_polls', to='curriculum.departmentgroup')),
            ],
            options={
                'verbose_name': 'Elective Poll',
                'verbose_name_plural': 'Elective Polls',
            },
        ),
        migrations.CreateModel(
            name='ElectivePollSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('elective_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_associations', to='curriculum.electivesubject')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_subjects', to='curriculum.electivepoll')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_poll_subjects', to='academics.staffprofile')),
            ],
            options={
                'verbose_name': 'Elective Poll Subject',
                'verbose_name_plural': 'Elective Poll Subjects',
            },
        ),
    ]
