# Generated by Django 5.2.5 on 2026-05-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_alter_curriculumdepartment_class_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electivepoll',
            options={'permissions': [('choose_elective', 'Can choose elective subjects')], 'verbose_name': 'Elective Poll', 'verbose_name_plural': 'Elective Polls'},
        ),
    ]
