# Generated by Django 5.2.5 on 2026-05-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0089_alter_staffprofile_staff_id_validation'),
        ('curriculum', '0031_alter_electivepoll_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivesubject',
            name='blocked_departments',
            field=models.ManyToManyField(blank=True, related_name='blocked_elective_subjects', to='academics.department'),
        ),
    ]
