# Generated by Django 5.2.5 on 2026-05-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_electivesubject_blocked_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electivepoll',
            name='semester',
        ),
    ]
