# Generated by Django 5.2.5 on 2026-05-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0034_add_tamil_and_tam_theory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electivepoll',
            options={
                'permissions': [
                    ('choose_elective', 'Can choose elective subjects'),
                    ('hod_elective_manage', 'Can view elective poll status for department students'),
                ],
                'verbose_name': 'Elective Poll',
                'verbose_name_plural': 'Elective Polls',
            },
        ),
    ]
