# Generated by Django 5.2.5 on 2026-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0035_alter_electivepoll_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivepollsubject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
