# Generated by Django 4.2.28 on 2026-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0036_add_is_active_to_electivepollsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumdepartment',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('THEORY_PMBL', 'Theory (PMBL)'), ('LAB', 'Lab'), ('PURE_LAB', 'Pure Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PRBL', 'PRBL'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special'), ('ENGLISH', 'English')], default='THEORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='curriculummaster',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('THEORY_PMBL', 'Theory (PMBL)'), ('LAB', 'Lab'), ('PURE_LAB', 'Pure Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PRBL', 'PRBL'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special'), ('ENGLISH', 'English')], default='THEORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='electivesubject',
            name='class_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('THEORY_PMBL', 'Theory (PMBL)'), ('LAB', 'Lab'), ('PURE_LAB', 'Pure Lab'), ('TCPL', 'Tcpl'), ('TCPR', 'Tcpr'), ('PRACTICAL', 'Practical'), ('PRBL', 'PRBL'), ('PROJECT', 'Project'), ('AUDIT', 'Audit'), ('SPECIAL', 'Special'), ('ENGLISH', 'English')], default='THEORY', max_length=16),
        ),
    ]
