# Generated by Django 4.2.28 on 2026-07-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0038_alter_curriculumdepartment_unique_together'),
        ('curriculum', '0039_add_lab_pc_qp_type'),
    ]

    operations = [
    ]
