# Generated by GitHub Copilot for college-scoped curriculum regulations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0040_merge_20260711_1246'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='college',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='regulations',
                blank=True,
                null=True,
                to='college.college',
                help_text='College associated with this regulation for college-scoped management.',
            ),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='regulation',
            constraint=models.UniqueConstraint(fields=('college', 'code'), name='curriculum_regulation_college_code_uniq'),
        ),
    ]
