# Generated by Django 4.2.28 on 2026-08-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0029_add_missing_engineering_physics'),
        ('curriculum', '0040_merge_20260711_1246'),
    ]

    operations = [
    ]
