# Generated by Django 4.2.28 on 2026-08-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('curriculum', '0041_add_college_to_regulation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='regulation',
            name='curriculum_regulation_college_code_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='regulation',
            unique_together={('college', 'code')},
        ),
    ]
