# Generated by Django 4.2.28 on 2026-08-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0096_remove_sectionadvisor_unique_active_advisor_per_section_year_and_more'),
        ('curriculum', '0041_merge_20260817_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electivepollsubject',
            name='elective_subject',
        ),
        migrations.RemoveField(
            model_name='electivepollsubject',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='electivepollsubject',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='electivesubject',
            name='blocked_departments',
        ),
        migrations.AlterUniqueTogether(
            name='curriculumdepartment',
            unique_together={('department', 'regulation', 'semester', 'course_code')},
        ),
        migrations.DeleteModel(
            name='ElectivePoll',
        ),
        migrations.DeleteModel(
            name='ElectivePollSubject',
        ),
    ]
