# Generated by Django 4.2.28 on 2026-08-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('curriculum', '0046_departmentgroupmapping_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumdepartment',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic schema per-college configuration'),
        ),
        migrations.AddField(
            model_name='curriculummaster',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic schema per-college configuration'),
        ),
        migrations.CreateModel(
            name='CurriculumColumnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="JSON key, e.g. 'credits'", max_length=64)),
                ('label', models.CharField(help_text="Display label, e.g. 'Credits (C)'", max_length=64)),
                ('data_type', models.CharField(choices=[('int', 'Integer'), ('str', 'Text'), ('float', 'Float')], default='str', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_core', models.BooleanField(default=False, help_text='Core columns cannot be deleted, only hidden')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_columns', to='college.college')),
            ],
            options={
                'verbose_name': 'Curriculum Column Config',
                'verbose_name_plural': 'Curriculum Column Configs',
                'ordering': ('sort_order', 'key'),
                'unique_together': {('college', 'key')},
            },
        ),
    ]
