# Generated by Django 4.2.28 on 2026-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0051_migrate_data_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumfieldschema',
            name='is_core',
            field=models.BooleanField(default=False, help_text='Core fields are seeded from original DB columns. They can be hidden but not deleted.'),
        ),
        migrations.AlterField(
            model_name='curriculumfieldschema',
            name='key',
            field=models.CharField(help_text="Unique field key used as JSON key, e.g. 'co_attainment'", max_length=64),
        ),
        migrations.AlterField(
            model_name='curriculumfieldschema',
            name='label',
            field=models.CharField(help_text='Display label shown in column header', max_length=128),
        ),
        migrations.AlterField(
            model_name='curriculumfieldschema',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='For select type: list of option values, e.g. ["A","B","C"]'),
        ),
        migrations.AlterField(
            model_name='curriculumfieldschema',
            name='scope',
            field=models.CharField(choices=[('master', 'Master Only'), ('department', 'Department Only'), ('both', 'Both')], default='both', help_text='Which curriculum type this field applies to.', max_length=16),
        ),
    ]
