# Generated by Django 4.2.28 on 2026-03-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_created_da46df_idx',
            old_name='announcements_a_created_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_source_ad59ff_idx',
            old_name='announcements_a_source_idx',
        ),
        migrations.RenameIndex(
            model_name='announcementcourse',
            new_name='announcemen_announc_1e4c78_idx',
            old_name='announcements_c_announc_idx',
        ),
        migrations.RenameIndex(
            model_name='announcementread',
            new_name='announcemen_announc_06457e_idx',
            old_name='announcements_r_announc_idx',
        ),
        migrations.RenameIndex(
            model_name='announcementread',
            new_name='announcemen_user_id_5d9385_idx',
            old_name='announcements_r_user_id_idx',
        ),
    ]
