# Generated by Django 4.2.28 on 2026-03-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_attachments_and_read_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_source_ad59ff_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_target__b3df8f_idx',
            old_name='announcemen_target__81f6ea_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_departm_42383d_idx',
            old_name='announcemen_departm_5dfc28_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_target__54947e_idx',
            old_name='announcemen_target__27209f_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_is_acti_b68c9c_idx',
            old_name='announcemen_is_acti_04b713_idx',
        ),
        migrations.RenameIndex(
            model_name='announcementreadstatus',
            new_name='announcemen_user_id_031982_idx',
            old_name='announcemen_user_id_32ac91_idx',
        ),
        migrations.RenameIndex(
            model_name='announcementreadstatus',
            new_name='announcemen_announc_e8fea1_idx',
            old_name='announcemen_announc_7e38ac_idx',
        ),
    ]
