# Generated by Django 4.2.28 on 2026-03-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_announcement_cover_image_and_expiry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_expiry__bb5922_idx',
            old_name='announce_expiry_idx',
        ),
    ]
