# Generated by Django 4.2.28 on 2026-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_remove_announcement_theme_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_created_da46df_idx',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_type',
            field=models.CharField(choices=[('ALL', 'All Users'), ('DEPARTMENT', 'Department'), ('CLASS', 'Class'), ('ROLE', 'Role')], default='ALL', max_length=16),
        ),
    ]
