#!/usr/bin/env python3
"""Generate college FK migration files for all tenant apps.

Creates three migrations per app:
  00XX_add_college_fk.py      — AddField (nullable)
  00XX_backfill_college.py    — Data backfill to PRIMARY college
  00XX_harden_college_fk.py   — AlterField (non-nullable)

Run: python3 generate_college_migrations.py --all
"""

import re
import sys
from pathlib import Path
from datetime import datetime

BACKEND = Path("/home/iqac/idcs 3.0/backend")

# Apps processed by the add_college_fk script that need migrations
APPS = [
    'OBE', 'COE', 'timetable', 'feedback', 'academic_calendar',
    'applications', 'announcements', 'certificates', 'lms',
    'staff_requests', 'staff_salary', 'staff_attendance',
    'question_bank', 'idcsscan', 'pbas', 'template_api',
    'academics', 'curriculum',
]

# Models that are GLOBAL (should not appear in college migrations)
GLOBAL_MODELS = {
    'curriculum': {'QuestionPaperType'},
    'template_api': {'CanvaServiceToken', 'CanvaOAuthState'},
    'academics': {'Department', 'Batch', 'StudentProfile', 'StaffProfile'},  # Already have college FK via existing SH migrations
    'pbas': {'PBASSubmission'},  # Already has college FK via existing migration
}


def get_tenant_models(app_name):
    """Parse models.py and return list of (class_name, related_name) for models with college FK."""
    models_file = BACKEND / app_name / 'models.py'
    if not models_file.exists():
        return []

    content = models_file.read_text()
    global_set = GLOBAL_MODELS.get(app_name, set())

    # Find all model classes with a college FK field
    models = []
    # Pattern: class ClassName(models.Model): ... college = models.ForeignKey(... related_name='xxx')
    classes = re.findall(r'^class (\w+)\(.*models\.Model.*\):', content, re.MULTILINE)

    for cls_name in classes:
        if cls_name in global_set:
            continue
        # Check if this class has a college FK field
        # Look for: college = models.ForeignKey('college.College', ... related_name='...')
        # Search in the block after the class definition
        idx = content.find(f'class {cls_name}(')
        if idx < 0:
            continue
        # Look ahead ~50 lines for a college FK
        block = content[idx:idx+3000]
        college_match = re.search(r"college\s*=\s*models\.ForeignKey\('college\.College'", block)
        if college_match:
            # Extract related_name
            rn_match = re.search(r"related_name=['\"](\w+)['\"]", block[:college_match.end()+200])
            related_name = rn_match.group(1) if rn_match else f'{cls_name.lower()}s'
            models.append((cls_name, related_name))

    return models


def get_next_migration_number(app_name):
    """Find the next available migration number for this app."""
    mig_dir = BACKEND / app_name / 'migrations'
    if not mig_dir.exists():
        return 1
    existing = []
    for f in mig_dir.glob('*.py'):
        m = re.match(r'^(\d{4})_', f.name)
        if m:
            existing.append(int(m.group(1)))
    return max(existing, default=0) + 1


def generate_add_migration(app_name, models, number):
    """Generate the AddField migration file."""
    model_ops = []
    for cls_name, related_name in models:
        model_ops.append(f"""        migrations.AddField(
            model_name='{cls_name.lower()}',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='{related_name}',
                to='college.college',
            ),
        ),""")

    content = f'''# Generated by generate_college_migrations.py
# Add nullable college FK to all tenant models in {app_name}

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('{app_name}', '{number-1:04d}_auto'),
    ]

    operations = [
{chr(10).join(model_ops)}
    ]
'''
    return content


def generate_backfill_migration(app_name, models, number):
    """Generate the data backfill migration."""
    model_names = sorted(set(m[0] for m in models))
    updates = ',\n'.join(f"            '{n}'," for n in model_names)

    content = f'''# Generated by generate_college_migrations.py
# Backfill college_id on {app_name} models to the primary college

from django.db import migrations


def _get_primary_college_id(apps):
    College = apps.get_model('college', 'College')
    c = College.objects.filter(is_active=True).order_by('id').first()
    if c is None:
        c = College.objects.create(code='PRIMARY', name='Primary College', short_name='PRIMARY', is_active=True)
    return c.id


def backfill(apps, schema_editor):
    cid = _get_primary_college_id(apps)
    model_names = [
{updates}
    ]
    for name in model_names:
        Model = apps.get_model('{app_name}', name)
        Model.objects.filter(college__isnull=True).update(college_id=cid)


def reverse_backfill(apps, schema_editor):
    model_names = [
{updates}
    ]
    for name in model_names:
        Model = apps.get_model('{app_name}', name)
        Model.objects.all().update(college_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('{app_name}', '{number-1:04d}_add_college_fk'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse_backfill),
    ]
'''
    return content


def generate_harden_migration(app_name, models, number):
    """Generate the harden (non-nullable) migration."""
    model_ops = []
    for cls_name, related_name in models:
        model_ops.append(f"""        migrations.AlterField(
            model_name='{cls_name.lower()}',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='{related_name}',
                to='college.college',
            ),
        ),""")

    content = f'''# Generated by generate_college_migrations.py
# Harden: make college FK non-nullable on all {app_name} models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('{app_name}', '{number-1:04d}_backfill_college'),
    ]

    operations = [
{chr(10).join(model_ops)}
    ]
'''
    return content


def generate_migration_files(app_name, dry_run=False):
    """Create all three migration files for an app."""
    models = get_tenant_models(app_name)
    if not models:
        print(f"  {app_name}: no tenant models found — skipping")
        return

    base = get_next_migration_number(app_name)
    add_num = base
    backfill_num = base + 1
    harden_num = base + 2

    mig_dir = BACKEND / app_name / 'migrations'
    mig_dir.mkdir(parents=True, exist_ok=True)

    # Check if existing college migrations already exist for this app
    existing_college = list(mig_dir.glob('*college*'))
    if existing_college and not dry_run:
        print(f"  {app_name}: college migrations already exist — skipping ({len(existing_college)} files)")
        return

    files = {
        f'{add_num:04d}_add_college_fk.py': generate_add_migration(app_name, models, add_num),
        f'{backfill_num:04d}_backfill_college.py': generate_backfill_migration(app_name, models, backfill_num),
        f'{harden_num:04d}_harden_college_fk.py': generate_harden_migration(app_name, models, harden_num),
    }

    if dry_run:
        print(f"\n  {app_name}: would create {len(files)} files (starting at {add_num:04d})")
        for name in files:
            print(f"    - {name}")
        print(f"    Models: {', '.join(m[0] for m in models)}")
        return

    for fname, content in files.items():
        filepath = mig_dir / fname
        filepath.write_text(content)
        print(f"    Created: {fname}")

    print(f"  {app_name}: created 3 migrations for {len(models)} models (starting at {add_num:04d})")


def main():
    if '--dry-run' in sys.argv:
        dry_run = True
        sys.argv.remove('--dry-run')
    else:
        dry_run = False

    if '--all' in sys.argv:
        for app in APPS:
            print(f"\n{'='*60}")
            print(f"Processing: {app}")
            print(f"{'='*60}")
            try:
                generate_migration_files(app, dry_run=dry_run)
            except Exception as e:
                print(f"  ERROR: {e}")
        print(f"\n{'='*60}")
        print("Done! Run with --dry-run first to preview.")
    elif len(sys.argv) > 1:
        app = sys.argv[1]
        models = get_tenant_models(app)
        print(f"\n{app}: {len(models)} tenant models")
        for cls_name, rn in models:
            print(f"  {cls_name} → related_name='{rn}'")
        generate_migration_files(app, dry_run=dry_run)
    else:
        print("Usage: python3 generate_college_migrations.py --dry-run --all")
        print("       python3 generate_college_migrations.py --all  (create files)")
        print("       python3 generate_college_migrations.py OBE   (single app)")


if __name__ == '__main__':
    main()
