# Generated by Django 4.2.28 on 2026-02-28 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pbas.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PBASCustomDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('accesses', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbas_custom_departments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PBASNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('audience', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('both', 'Both')], default='both', max_length=16)),
                ('input_mode', models.CharField(choices=[('upload', 'Upload'), ('link', 'Link')], default='upload', max_length=16)),
                ('link', models.URLField(blank=True, null=True)),
                ('uploaded_name', models.CharField(blank=True, max_length=255, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('college_required', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pbas.pbascustomdepartment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pbas.pbasnode')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='PBASSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_type', models.CharField(choices=[('upload', 'Upload'), ('link', 'Link')], max_length=16)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=pbas.utils.upload_to_pbas_submission)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbas_submissions', to='college.college')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pbas.pbasnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbas_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='pbas_pbassu_user_id_9fb112_idx'), models.Index(fields=['node', '-created_at'], name='pbas_pbassu_node_id_829100_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pbasnode',
            index=models.Index(fields=['department', 'parent'], name='pbas_pbasno_departm_72b682_idx'),
        ),
        migrations.AddIndex(
            model_name='pbasnode',
            index=models.Index(fields=['parent'], name='pbas_pbasno_parent__2f65c0_idx'),
        ),
    ]
