# Generated by GitHub Copilot on 2026-02-28

from __future__ import annotations

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0042_merge_0040_staffprofile_0041_dailyattendance'),
        ('pbas', '0002_pbascustomdepartment_academic_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBASVerificationTicket',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Draft'), ('mentor_pending', 'Mentor Pending'), ('dept_pending', 'Department Pending')],
                        default='draft',
                        max_length=32,
                    ),
                ),
                ('forwarded_to_mentor_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_to_department_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'department',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='verification_tickets',
                        to='pbas.pbascustomdepartment',
                    ),
                ),
                (
                    'mentor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pbas_verification_tickets',
                        to='academics.staffprofile',
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pbas_verification_tickets',
                        to='academics.studentprofile',
                    ),
                ),
                (
                    'submission',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='verification_ticket',
                        to='pbas.pbassubmission',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
