# Generated by Django 4.2.28 on 2026-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0006_seed_research_and_development_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbasnode',
            name='pbas_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
