# Generated by Django 4.2.28 on 2026-08-18 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pbas', '0007_pbasnode_pbas_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbasnode',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='pbas_approver_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pbassubmission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbas_approved_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pbassubmission',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pbassubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pbassubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
