# Generated by generate_college_migrations.py
# Harden: make college FK non-nullable on all pbas models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('pbas', '0008_backfill_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbascustomdepartment',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pbascustomdepartments',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='pbasnode',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pbasnodes',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='pbasverificationticket',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pbasverificationtickets',
                to='college.college',
            ),
        ),
    ]
