# Generated by Django 4.2.28 on 2026-08-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0009_pbasnodeapproverhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbasnode',
            name='form_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pbassubmission',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pbassubmission',
            name='submission_type',
            field=models.CharField(choices=[('form', 'Form'), ('upload', 'Upload'), ('link', 'Link')], default='form', max_length=16),
        ),
    ]
