# Generated by Django 4.2.28 on 2026-09-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0010_pbasnode_form_schema_pbassubmission_form_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbasnode',
            name='mentor_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
