# Generated by Django 4.2.28 on 2026-09-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0011_pbasnode_mentor_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBASApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_flow', models.JSONField(blank=True, default=list)),
                ('student_flow', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PBAS Approval Flow',
                'verbose_name_plural': 'PBAS Approval Flows',
            },
        ),
    ]
