# Generated by Django 4.2.28 on 2026-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0012_pbasapprovalflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbassubmission',
            name='approval_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pbassubmission',
            name='current_step',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
