# Generated by Django 4.2.28 on 2026-03-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('emi', 'EMI'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryEarnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryFormulaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expressions', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salary Formula Config',
                'verbose_name_plural': 'Salary Formula Config',
            },
        ),
        migrations.CreateModel(
            name='SalaryPFConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_amount', models.FloatField(default=15000.0)),
                ('fixed_pf_amount', models.FloatField(default=1800.0)),
                ('percentage_rate', models.FloatField(default=12.0)),
                ('type1_department_ids', models.JSONField(blank=True, default=list)),
                ('type2_department_ids', models.JSONField(blank=True, default=list)),
                ('type2_constant_value', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salary PF Config',
                'verbose_name_plural': 'Salary PF Config',
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.FloatField(default=0.0)),
                ('allowance', models.FloatField(default=0.0)),
                ('pf_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_declaration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryEMIPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0)),
                ('months', models.PositiveIntegerField(default=1)),
                ('start_month', models.DateField(help_text='Use first day of month')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_plans', to='staff_salary.salarydeductiontype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_emi_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_month', 'staff_id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryMonthlyInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use first day of month')),
                ('earn_values', models.JSONField(blank=True, default=dict)),
                ('deduction_values', models.JSONField(blank=True, default=dict)),
                ('od_new', models.FloatField(default=0.0)),
                ('others', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_monthly_inputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'staff_id'],
                'unique_together': {('staff', 'month')},
            },
        ),
    ]
