# Generated by generate_college_migrations.py
# Harden: make college FK non-nullable on all staff_salary models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('staff_salary', '0007_backfill_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalarydeclaration',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='staffsalarydeclarations',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='salarybankdeclaration',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='salarybankdeclarations',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='salarypfconfig',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='salarypfconfigs',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='salaryformulaconfig',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='salaryformulaconfigs',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='salarydeductiontype',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='salarydeductiontypes',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='salaryearntype',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='salaryearntypes',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='salaryemiplan',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='salaryemiplans',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='salarymonthlyinput',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='salarymonthlyinputs',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='salarymonthpublish',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='salarymonthpublishs',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='salarypublishedreceipt',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='salarypublishedreceipts',
                to='college.college',
            ),
        ),
    ]
