#!/usr/bin/env bash
# =============================================================================
# setup_n8n.sh  —  Download, configure and start n8n for IDCS Canva automation
#
# Usage:
#   chmod +x tools/setup_n8n.sh
#   ./tools/setup_n8n.sh
#
# What this script does:
#   1. Checks for Node.js 18+ (required by n8n)
#   2. Installs n8n globally via npm (if not already installed)
#   3. Creates a local .n8n/ config folder with the correct env settings
#   4. Imports the IDCS Canva Branding Poster workflow
#   5. Starts n8n in the background (http://localhost:5678)
#
# After running this script:
#   - Open http://localhost:5678 and complete first-time n8n setup
#   - The workflow "IDCS Canva Branding Poster Generator" will be pre-imported
#   - Activate it → copy the Production Webhook URL → paste into backend .env
#
# Environment variables written to tools/.n8n.env (source before running n8n):
#   N8N_PORT=5678
#   N8N_HOST=localhost
#   N8N_PROTOCOL=http
#   WEBHOOK_URL=http://localhost:5678/
#   N8N_ENCRYPTION_KEY=<auto-generated>
#   EXECUTIONS_MODE=regular
# =============================================================================
set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
RESET='\033[0m'

info()    { echo -e "${GREEN}[✓]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[!]${RESET} $*"; }
fatale()  { echo -e "${RED}[✗]${RESET} $*"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
N8N_ENV_FILE="$SCRIPT_DIR/.n8n.env"
N8N_DATA_DIR="$SCRIPT_DIR/.n8n_data"
WORKFLOW_FILE="$PROJECT_ROOT/docs/n8n_canva_branding_workflow.json"
BACKEND_ENV="$PROJECT_ROOT/backend/.env"

echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════════${RESET}"
echo -e "${BOLD}  IDCS  ·  n8n Setup for Canva Branding Automation     ${RESET}"
echo -e "${BOLD}═══════════════════════════════════════════════════════${RESET}"
echo ""

# ── 1. Check Node.js ──────────────────────────────────────────────────────────
info "Checking Node.js version…"
if ! command -v node &>/dev/null; then
  fatale "Node.js is not installed. Install Node.js 18+ from https://nodejs.org and re-run."
fi

NODE_VERSION=$(node --version | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
  fatale "Node.js $NODE_VERSION found but n8n requires Node.js 18+. Please upgrade."
fi
info "Node.js v$(node --version) — OK"

# ── 2. Install / update n8n ───────────────────────────────────────────────────
if command -v n8n &>/dev/null; then
  INSTALLED_VERSION=$(n8n --version 2>/dev/null || echo "unknown")
  info "n8n is already installed (version: $INSTALLED_VERSION). Checking for updates…"
  npm update -g n8n 2>/dev/null || warn "Could not auto-update n8n. Continuing with installed version."
else
  info "Installing n8n globally via npm (this may take 2-5 minutes)…"
  npm install -g n8n
  info "n8n installed successfully."
fi

# ── 3. Generate / update .n8n.env ────────────────────────────────────────────
info "Configuring n8n environment…"
mkdir -p "$N8N_DATA_DIR"

if [ ! -f "$N8N_ENV_FILE" ]; then
  # Generate a random 32-char encryption key
  ENCRYPTION_KEY=$(node -e "console.log(require('crypto').randomBytes(24).toString('hex'))")
  cat > "$N8N_ENV_FILE" <<EOF
# ── n8n runtime configuration for IDCS Canva automation ──────────────────────
# Source this file before starting n8n:  source tools/.n8n.env && n8n start
# Or use the start_n8n.sh helper generated by this script.

N8N_PORT=5678
N8N_HOST=0.0.0.0
N8N_PROTOCOL=http
WEBHOOK_URL=http://localhost:5678/
N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
N8N_DEFAULT_BINARY_DATA_MODE=default
EXECUTIONS_MODE=regular
N8N_LOG_LEVEL=info
N8N_DIAGNOSTICS_ENABLED=false
N8N_PERSONALIZATION_ENABLED=false

# ── DATA DIRECTORY ────────────────────────────────────────────────────────────
# Workflows, credentials, and execution logs are stored here.
N8N_USER_FOLDER=${N8N_DATA_DIR}

# ── IDCS BACKEND URL ──────────────────────────────────────────────────────────
# The URL n8n uses to call Django's /api/canva/generate-poster endpoint.
# Change to your production URL (e.g. https://idcs.krgi.co.in) before deploying.
IDCS_BACKEND_URL=http://localhost:8000
EOF
  info "Created $N8N_ENV_FILE with auto-generated encryption key."
else
  warn "$N8N_ENV_FILE already exists — skipping regeneration."
fi

# ── 4. Write backend .env hint ────────────────────────────────────────────────
if [ -f "$BACKEND_ENV" ]; then
  if ! grep -q "N8N_BRANDING_WEBHOOK_URL" "$BACKEND_ENV"; then
    warn "Adding n8n placeholders to backend/.env…"
    cat >> "$BACKEND_ENV" <<'EOF'

# ── n8n Canva Poster Automation ──────────────────────────────────────────────
# Paste the Production Webhook URL from n8n (Receive Event Webhook node) here.
N8N_BRANDING_WEBHOOK_URL=http://localhost:5678/webhook/canva-poster
# Shared secret validated by poster-callback endpoint
N8N_WEBHOOK_SECRET=change_me_to_a_random_secret
# Public URL of this Django backend reachable by n8n
IDCS_BACKEND_URL=http://localhost:8000
# Canva Brand Template ID (copy from Canva URL of the brand template)
CANVA_BRANDING_TEMPLATE_ID=
EOF
    info "Updated backend/.env with n8n placeholders."
  else
    info "backend/.env already has n8n settings — not modified."
  fi
else
  warn "backend/.env not found — skipping (create it manually if needed)."
fi

# ── 5. Write a convenience start script ──────────────────────────────────────
START_SCRIPT="$SCRIPT_DIR/start_n8n.sh"
cat > "$START_SCRIPT" <<'EOF'
#!/usr/bin/env bash
# Start n8n with IDCS configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
set -a; source "$SCRIPT_DIR/.n8n.env"; set +a
echo "Starting n8n on http://localhost:${N8N_PORT:-5678} …"
n8n start
EOF
chmod +x "$START_SCRIPT"
info "Created $START_SCRIPT"

# ── 6. Import the IDCS workflow ───────────────────────────────────────────────
if [ -f "$WORKFLOW_FILE" ]; then
  info "Importing IDCS Canva Branding workflow…"
  # Source env so the N8N_USER_FOLDER is picked up
  set -a; source "$N8N_ENV_FILE"; set +a
  if n8n import:workflow --input="$WORKFLOW_FILE" 2>/dev/null; then
    info "Workflow imported successfully."
  else
    warn "Auto-import failed (n8n may need to be started first)."
    warn "After starting n8n, run:"
    warn "  source tools/.n8n.env && n8n import:workflow --input=docs/n8n_canva_branding_workflow.json"
  fi
else
  warn "Workflow file not found at $WORKFLOW_FILE — skipping import."
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════════${RESET}"
echo -e "${BOLD}  Setup complete!${RESET}"
echo ""
echo -e "  ${GREEN}Start n8n:${RESET}  ./tools/start_n8n.sh"
echo -e "  ${GREEN}UI:${RESET}         http://localhost:5678"
echo ""
echo -e "  ${YELLOW}Next steps:${RESET}"
echo -e "  1. Run: ${BOLD}./tools/start_n8n.sh${RESET}"
echo -e "  2. Open http://localhost:5678 and complete first-time setup"
echo -e "  3. Go to Workflows → open 'IDCS Canva Branding Poster Generator'"
echo -e "  4. Activate the workflow (toggle at top-right)"
echo -e "  5. Copy the ${BOLD}Production Webhook URL${RESET} from the first node"
echo -e "  6. Paste it into ${BOLD}backend/.env${RESET} as N8N_BRANDING_WEBHOOK_URL"
echo -e "  7. Restart Django: python manage.py runserver"
echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════════${RESET}"
