# Generated by Django 4.2.28 on 2026-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bi', '0004_obe_internal_cqi_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimStudent',
            fields=[
                ('student_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('section_id', models.BigIntegerField(null=True)),
                ('section_name', models.CharField(blank=True, max_length=8)),
                ('batch_id', models.BigIntegerField(null=True)),
                ('batch_name', models.CharField(blank=True, max_length=32)),
                ('course_id', models.BigIntegerField(null=True)),
                ('course_name', models.CharField(blank=True, max_length=128)),
                ('program_id', models.BigIntegerField(null=True)),
                ('program_name', models.CharField(blank=True, max_length=32)),
                ('dept_id', models.BigIntegerField(null=True)),
                ('dept_code', models.CharField(blank=True, max_length=16)),
                ('dept_name', models.CharField(blank=True, max_length=128)),
                ('mobile_number_verified_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'BI Student',
                'verbose_name_plural': 'BI Students',
                'db_table': 'bi_dim_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimSubject',
            fields=[
                ('subject_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=32)),
                ('subject_name', models.CharField(max_length=128)),
                ('semester_id', models.BigIntegerField()),
                ('semester_no', models.IntegerField(null=True)),
                ('course_id', models.BigIntegerField(null=True)),
                ('course_name', models.CharField(blank=True, max_length=128)),
                ('program_id', models.BigIntegerField(null=True)),
                ('program_name', models.CharField(blank=True, max_length=32)),
                ('dept_id', models.BigIntegerField(null=True)),
                ('dept_code', models.CharField(blank=True, max_length=16)),
                ('dept_name', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'BI Subject',
                'verbose_name_plural': 'BI Subjects',
                'db_table': 'bi_dim_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTeachingAssignment',
            fields=[
                ('teaching_assignment_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('academic_year_id', models.BigIntegerField(null=True)),
                ('academic_year', models.CharField(blank=True, max_length=32)),
                ('academic_year_parity', models.CharField(blank=True, max_length=8)),
                ('section_id', models.BigIntegerField(null=True)),
                ('section_name', models.CharField(blank=True, max_length=8)),
                ('subject_id', models.BigIntegerField(null=True)),
                ('subject_code', models.CharField(blank=True, max_length=32)),
                ('subject_name', models.CharField(blank=True, max_length=128)),
                ('staff_profile_id', models.BigIntegerField(null=True)),
                ('staff_id', models.CharField(blank=True, max_length=64)),
                ('staff_user_id', models.BigIntegerField(null=True)),
                ('staff_username', models.CharField(blank=True, max_length=150)),
                ('staff_first_name', models.CharField(blank=True, max_length=150)),
                ('staff_last_name', models.CharField(blank=True, max_length=150)),
                ('enabled_assessments', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'BI Teaching Assignment',
                'verbose_name_plural': 'BI Teaching Assignments',
                'db_table': 'bi_dim_teaching_assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactMark',
            fields=[
                ('fact_key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('assessment_key', models.CharField(max_length=32)),
                ('component_key', models.CharField(max_length=32)),
                ('source_table', models.CharField(max_length=64)),
                ('source_id', models.BigIntegerField()),
                ('subject_id', models.BigIntegerField()),
                ('subject_code', models.CharField(max_length=32)),
                ('subject_name', models.CharField(max_length=128)),
                ('student_id', models.BigIntegerField()),
                ('reg_no', models.CharField(max_length=64)),
                ('score', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'BI Mark',
                'verbose_name_plural': 'BI Marks',
                'db_table': 'bi_fact_marks',
                'managed': False,
            },
        ),
    ]
