# Generated by Django 5.2.10 on 2026-03-07 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0058_batch_course_nullable_dept_direct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('STAFF', 'Staff'), ('STUDENT', 'Student')], help_text='Target audience: staff or student', max_length=10)),
                ('type', models.CharField(choices=[('SUBJECT_FEEDBACK', 'Subject Feedback'), ('OPEN_FEEDBACK', 'Open Feedback')], help_text='Type of feedback: subject-specific or open', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', help_text='Status of the feedback form', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User (HOD) who created this form', on_delete=django.db.models.deletion.CASCADE, related_name='created_feedback_forms', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department this feedback form belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_forms', to='academics.department')),
            ],
            options={
                'verbose_name': 'Feedback Form',
                'verbose_name_plural': 'Feedback Forms',
                'db_table': 'feedback_forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question text')),
                ('answer_type', models.CharField(choices=[('STAR', 'Star Rating'), ('TEXT', 'Text Response')], help_text='Type of answer: star rating or text', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_form', models.ForeignKey(help_text='Feedback form this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.feedbackform')),
            ],
            options={
                'verbose_name': 'Feedback Question',
                'verbose_name_plural': 'Feedback Questions',
                'db_table': 'feedback_questions',
                'ordering': ['feedback_form', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_star', models.PositiveSmallIntegerField(blank=True, help_text='Star rating (1-5), used when answer_type is STAR', null=True)),
                ('answer_text', models.TextField(blank=True, help_text='Text response, used when answer_type is TEXT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_form', models.ForeignKey(help_text='Feedback form this response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedbackform')),
                ('question', models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedbackquestion')),
                ('user', models.ForeignKey(help_text='User who submitted this response', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Response',
                'verbose_name_plural': 'Feedback Responses',
                'db_table': 'feedback_responses',
                'ordering': ['-created_at'],
                'unique_together': {('feedback_form', 'question', 'user')},
            },
        ),
    ]
