# Generated by Django 5.2.10 on 2026-03-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0058_batch_course_nullable_dept_direct'),
        ('curriculum', '0021_swap_batch_to_batchyear'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='all_classes',
            field=models.BooleanField(default=False, help_text='True if feedback targets all classes/years in department'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='regulation',
            field=models.ForeignKey(blank=True, help_text='Regulation for student feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_forms', to='curriculum.regulation'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section for student feedback (leave empty for all sections)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_forms', to='academics.section'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester for student feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_forms', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year (1, 2, 3, or 4) for student feedback', null=True),
        ),
    ]
