# Generated by Django 5.2.10 on 2026-03-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0058_batch_course_nullable_dept_direct'),
        ('feedback', '0003_add_multiclass_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section for student feedback (legacy single value)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_forms', to='academics.section'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester for student feedback (legacy single value)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_forms', to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year (1, 2, 3, or 4) for student feedback (legacy single value)', null=True),
        ),
    ]
