# Generated by Django 5.2.10 on 2026-03-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedbackform_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='active',
            field=models.BooleanField(default=True, help_text='If False, form is hidden from students/staff but data is preserved'),
        ),
    ]
