# Generated by Django 5.2.10 on 2026-03-09 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0058_batch_course_nullable_dept_direct'),
        ('feedback', '0005_feedbackform_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='teaching_assignment',
            field=models.ForeignKey(blank=True, help_text='Teaching assignment (subject + staff) for subject-based feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to='academics.teachingassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackresponse',
            unique_together={('feedback_form', 'question', 'user', 'teaching_assignment')},
        ),
    ]
