# Generated by Django 5.2.10 on 2026-03-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0058_batch_course_nullable_dept_direct'),
        ('feedback', '0008_add_subject_feedback_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='subject',
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='teaching_assignment',
            field=models.ForeignKey(blank=True, help_text='Teaching assignment this feedback relates to (for subject feedback). Subject and staff can be accessed via teaching_assignment.subject and teaching_assignment.staff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to='academics.teachingassignment'),
        ),
    ]
