# Generated by Django 5.2.10 on 2026-03-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_remove_feedbackresponse_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='is_subject_based',
            field=models.BooleanField(default=False, help_text='True for subject-based feedback, False for open feedback'),
        ),
    ]
