# Generated by Django 4.2.28 on 2026-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_add_question_type_and_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackquestion',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating'), ('text', 'Text'), ('radio', 'Radio + Comment'), ('rating_radio_comment', 'Rating + Radio + Comment')], default='rating', help_text='Question rendering/validation type. Defaults to rating for backward compatibility.', max_length=50),
        ),
    ]
