# Generated by Django 4.2.28 on 2026-03-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_feedbackquestion_is_mandatory_state_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='allow_hod_view',
            field=models.BooleanField(default=False, help_text='If True, department HOD can view responses for this form (filtered by their department)'),
        ),
    ]
