# Generated by Django 4.2.28 on 2026-03-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0022_add_allow_hod_view_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='If True, student names and register numbers will be hidden from responses and exports'),
        ),
    ]
