# Generated by Django 4.2.28 on 2026-04-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0072_merge_20260322_0001'),
        ('curriculum', '0022_add_is_dept_core'),
        ('feedback', '0023_feedbackform_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='elective_subject',
            field=models.ForeignKey(blank=True, help_text='Elective subject being rated (for PE/OE/EE subjects)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses_elective', to='curriculum.electivesubject'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject being rated (can be from teaching_assignment.subject or elective)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to='academics.subject'),
        ),
    ]
