# Generated by Django 4.2.28 on 2026-04-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_feedbackform_form_name'),
        ('feedback', '0024_feedbackresponse_elective_subject_and_more'),
    ]

    operations = [
    ]
