# Generated by Django 4.2.28 on 2026-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0028_add_section_wise_feedback_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresponse',
            name='answer_star',
            field=models.FloatField(blank=True, help_text='Rating (1-4, supports 0.5 increments), used when answer_type is STAR', null=True),
        ),
    ]
