# Generated by Django 4.2.28 on 2026-08-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0028_add_section_wise_feedback_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackform',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='section_staff_assignments',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='section_wise',
        ),
    ]
