# Generated by generate_college_migrations.py
# Add nullable college FK to all tenant models in feedback

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('feedback', '0028_add_section_wise_feedback_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbackforms',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbackquestions',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='feedbackquestionoption',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbackquestionoptions',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbackresponses',
                to='college.college',
            ),
        ),
        migrations.AddField(
            model_name='feedbackformsubmission',
            name='college',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbackformsubmissions',
                to='college.college',
            ),
        ),
    ]
