# Generated by generate_college_migrations.py
# Harden: make college FK non-nullable on all feedback models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('feedback', '0030_backfill_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbackforms',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='feedbackquestion',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbackquestions',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='feedbackquestionoption',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbackquestionoptions',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbackresponses',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='feedbackformsubmission',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbackformsubmissions',
                to='college.college',
            ),
        ),
    ]
