# Generated by Django 4.2.28 on 2026-08-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('feedback', '0031_harden_college_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackforms', to='college.college'),
        ),
        migrations.AlterField(
            model_name='feedbackformsubmission',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackformsubmissions', to='college.college'),
        ),
        migrations.AlterField(
            model_name='feedbackquestion',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackquestions', to='college.college'),
        ),
        migrations.AlterField(
            model_name='feedbackquestionoption',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackquestionoptions', to='college.college'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackresponses', to='college.college'),
        ),
    ]
