# Generated by Django 4.2.28 on 2026-08-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_seed_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_student_e3640b_idx',
            old_name='certific_studen_14c3b0_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_mentor__2db8de_idx',
            old_name='certific_mentor_6d2d0f_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_file_ha_7ac2ed_idx',
            old_name='certific_file_h_3e2fd1_idx',
        ),
        migrations.RenameIndex(
            model_name='studentachievement',
            new_name='certificate_student_dea15e_idx',
            old_name='achieve_studen_0c92f3_idx',
        ),
    ]
