# Generated by generate_college_migrations.py
# Harden: make college FK non-nullable on all certificates models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_featurecatalog_permissions'),
        ('certificates', '0005_backfill_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='certificates',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='studentachievements',
                to='college.college',
            ),
        ),
        migrations.AlterField(
            model_name='certificateauditlog',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='certificateauditlogs',
                to='college.college',
            ),
        ),
    ]
